### ISSUE TITLE
Update jwt dependency from dgrijalva/jwt-go to golang-jwt/jwt

### ISSUE THREAD

**Issue by Technerder** [jackc/pgx#1046]
[dgrijalva/jwt-gois](https://github.com/dgrijalva/jwt-gois) no longer being maintained as stated in their README, which also recommends that people swap over to [golang-jwt/jwt](https://github.com/golang-jwt/jwt) 

Are there any plans to upgrade from ``dgrijalva/jwt-go`` to ``golang-jwt/jwt`` as of right now?

**Comment by jackc** [comment]
My first though was: why does a database driver have a dependency on a JWT library? As it turns out, there isn't any production dependency. It is there because of how modules include all the dependencies including tests in `go.sum`. It appears it is coming from `go-kit`. https://github.com/jackc/pgx/commit/48f39340b3de35d6ff078679347199941a0d6818 trimmed the `go-kit` dependency so I think this pseudo-dependency should drop entirely at some point.

**Comment by Technerder** [comment]
Ah, I just noticed that this since its usage was flagged in a security test. When do you think it'll be removed from ``go.sum``?

**Comment by jackc** [comment]
I tried to get it out of go.sum, but it turns out that is really hard. Go packages can't have recursive dependencies, but modules can. `pgx` depends on `pgtype`. But the `pgtype` **tests** depend on `pgx`. And since Go modules _helpfully_ include test dependencies we end up where there is no way for the latest version of `pgx` to depend on the latest version of `pgtype` and vice versa. And Go modules recursively follow that chain of dependencies all the way back to prerelease versions of `pgx` v4. 🤦 

In addition, in the `pgtype` module we have a helper package `pgxtype` that legitimately does depend on `pgx`. So even deleting all the tests in `pgtype` wouldn't sever the module dependencies.

At this point I don't know how to break the dependency chain without making breaking changes. But a new major release is a lot of hassle for everyone.

**Comment by jackc** [comment]
And right after I posted my previous message I thought of a workaround. I had to create a sequence of commits that in pgx and pgtype that removed the dependencies even though it was a breaking change, update the test dependencies in the other to use that version, then revert the original change and update to the new one on the other side. Yuck...

Anyway, `v4.13.0` no longer has that dependency.
