### ISSUE TITLE
pgtype: Replace pgtype.Status with boolean Valid

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#1060]
*This is a breaking change that would only be done if there is a new major release.*

Almost all pgtype types use a `Status` column that has `Undefined`, `Null`, and `Present` values. The zero value is `Undefined`. This means that the zero value of these pgtype types is not usable. The original reason for this was to make it easier for ORMs or other helpers to distinguish between "no update requested" and "update to null". However, I don't know of anyone actually using it this way.

The current design has the following downsides:

1. The zero value is not usable. This is not idiomatic Go style.
2. It needlessly is different than how `database/sql` `Null*` types work.

I propose replacing the `Status` column with a boolean `Valid` field to match `database/sql`.

The obvious downside is any code currently using `pgtype` types directly would need to change how they handle nulls. I think it is worthwhile, but it may be worth sticking with the existing system if this change would cause too large an upgrade burden.

Please use the thumbs up or thumbs down reactions and post a comment if you have specific thoughts.

**Comment by netras** [comment]
I just spent a couple of days migrating a mature code base from `lib/pq` to `pgx`. Especially when working with deep-nested JSON data, having to set all `NULL` values to `Status:pgtype.Null` is a real treat. Figuring out which of the hundreds of JSON objects was missing its proper NULL-status took forever.

Since I never benefitet from the `Undefined` status, I am quite biased towards having a usable zero value. I would gladly rewrite my code again to clean this up, if this change is implemented.

**Comment by jackc** [comment]
Done on `v5-dev` branch.
