### ISSUE TITLE
String Slice Unsupported by Exec()

### ISSUE THREAD

**Issue by theory** [jackc/pgx#107]
According to [the docs]():

> pgx maps between int16, int32, int64, float32, float64, and string Go slices and the equivalent PostgreSQL array type.

However, this program:

	package main

	import (
		"database/sql"
		_ "github.com/jackc/pgx/stdlib"
	)

	func main() {
		dsn := "postgres://postgres@localhost/postgres?sslmode=disable"
		db, err := sql.Open("pgx", dsn)
		if err != nil {
			panic(err)
		}

		_, err = db.Exec(`
			CREATE TABLE _things_ (
				tags TEXT[]
			)
		`)
		if err != nil {
			panic(err)
		}
		defer db.Exec("DROP TABLE _things_")

		_, err = db.Exec(
			"INSERT INTO things VALUES($1)",
			[]string{"foo", "bar"},
		)
		if err != nil {
			panic(err)
		}
	}

Emits:

    panic: sql: converting Exec argument #0's type: unsupported type []string, a slice

Am I missing something here?

**Comment by jackc** [comment]
pgx supports it, but the database/sql interface does not. You will need to use the native pgx interface to get slice mapping.

**Comment by theory** [comment]
Is there no way to get database/sql to support it?

I thought I got this when I tried pgx, too, but trying again now it seems to work.

However, pix does not support generic number types like `int`. It has to be `int32` or another one of the explicitly-sized integers. Could PGX be updated to support `int` and `uint`?

**Comment by jackc** [comment]
My guess is database/sql doesn't support it due to cross-database compatibility concerns, but I don't know for sure. database/sql requires all values to passed to and from the database driver to be of certain types. Nothing pgx can do there. The only way I know to get support in database/sql would be to write a type that implements the database/sql Scanner interface. Unfortunately, that would mean parsing the text format, so it would lose the performance advantages of the binary protocol.

If you want/need to use database/sql, but you also want to use some pgx features you can use get a pgx *Conn on demand from from the database/sql pool. See https://godoc.org/github.com/jackc/pgx/stdlib.

The reason specific number types are required is otherwise it is possible for code to succeed or fail based on what the value of the number is. Requiring it to be the correctly sized integer ensures if it ever works it will always work.

**Comment by theory** [comment]
> The reason specific number types are required is otherwise it is possible for code to succeed or fail based on what the value of the number is. Requiring it to be the correctly sized integer ensures if it ever works it will always work.

True, but it also makes it harder to use a more general code design. I tried messing with it, and a bunch of tests failed because I had to use `int32 ` for the mapped database values and my tests used constant values, like `3`, which the compiler makes into `int`. And apparently you can't compare an `int32` to an `int`.

It'd be great if pgx could support `int` as an alias for `int32` and `uint` as an alias for `uint32`. Anyone who ran into size issues would be encouraged to use the specific sizes.

**Comment by jackc** [comment]
Are you trying to use `int` as an argument to `Query` or `Exec` or as a `Scan` destination? Some of those should actually work the way you want (though I have an issue to reconsider this if/when there is a v3 of pgx #105).

**Comment by theory** [comment]
Scan. The error:

    Scan cannot decode into *int

Is there a way to get it to do the scan?

Also, is there a way to add an Encoder or Decoder for third-party objects? [UUID](https://github.com/pborman/uuid), for example.

**Comment by jackc** [comment]
Yeah, Scan is strict. Query and Exec support receiving int to enable integer literals to be passed as arguments without a type coercion. But Scan doesn't.

You can scan and decode third-party objects by doing a named type.

```go
type Foo external.Foo

func (f *Foo) Scan(...)
```

You then type convert whenever you are using it as an argument to Query, Exec, or Scan.

**Comment by theory** [comment]
That could be a PITA. Maybe it could at least recognize and use the database/sql/driver Valuer and database/sql Scanner interfaces?

**Comment by jackc** [comment]
It might be possible. It probably would be forced to use the text protocol, so it might not be as efficient.

**Comment by jackc** [comment]
9f9a9779ac794e885f6fbb04935724f03149f092 adds compatibility with the standard database/sql.Scanner and database/sql/driver.Valuer interfaces for custom types. See https://github.com/jackc/pgx/blob/master/query_test.go#L913 for an example.
