### ISSUE TITLE
How To Implement Default Postgres->User Type Handler For JSONB

### ISSUE THREAD

**Issue by jnikitin-r7** [jackc/pgx#1073]
Hi, I'm upgrading from pgx 3.1.0 to pgx 4.13.0.

I have a custom struct that I unmarshall Postgres rows into with old PGX.
```
type Object struct {
	...
	Value interface{} `db:"value"`
	...
}
```

When I upgraded and ran the tests, I no longer get a string back, but rather a []uint8 ([]byte).

I seems to have traced it down to stdlib/sql.go where this happens.

Before when we Postgres type was jsonb, it transformed it into Text.

```
r.values[i] = &pgtype.GenericText{}
```

Now it initializes the default pgtype.JSONB

```
case pgtype.JSONBOID:
	var d pgtype.JSONB
	scanPlan := ci.PlanScan(dataTypeOID, format, &d)
	r.valueFuncs[i] = func(src []byte) (driver.Value, error) {
		err := scanPlan.Scan(ci, dataTypeOID, format, src, &d)
		if err != nil {
			return nil, err
		}
	return d.Value()
```

It seems like PGX will initialize its own JSONB type with its own decoder. I would still like to somehow keep old behavior through config. As in, override handling of the `pgtype.JSONBOID` oid. We are using build targets and I would rather not change the types everywhere - `interface{}` ones .

Thank you!

Summary: the default behavior of how data is copied from Postgres changed when the struct type is `interface{}`. Before PGX converted it into string, but now it its a []byte.

**Comment by jackc** [comment]
So the problem is the driver now returns `jsonb` as `[]byte` instead of `string`? It's been a couple years since the `v3` to `v4` development but I think the reason for that change was to avoid forcing a string allocation and then potentially another allocation in the application to convert back to `[]byte` for unmarshalling.

If that is the issue, I don't think it can be changed at this point nor should be. It has been this way for 2 years and has better performance.
