### ISSUE TITLE
Structure binding

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#11]
Need some easy to use way of reading data from a query directly into structs.

Possibilities:
- reflection
- generated binding classes
- pass in function as query data reader

**Comment by elumalai** [comment]
@jackc  Scan works for simple structs. Code generation from sql definition won't work, since most of the queries are not that straight forward. Right now we are doing the scan manually. It is not really convenient if the table has more columns. Also restructuring the fields eats up lot of time if we introduce columns later.  

Any possibilities to reconsider ?

**Comment by jackc** [comment]
I'm not sure if this belongs in the database driver layer or not. Seems like their are multiple approaches and perhaps it belongs in a library that sits above pgx.

I'm currently experimenting with using code generation to make CRUD easier ([pgxdata](https://github.com/jackc/pgxdata) - definitely not usable yet). That may become useful at some point.

I'm not a fan of using reflection for structure binding, so I don't see that landing in core pgx.

Any particular approach you were looking for?

**Comment by elumalai** [comment]
I agree with you concern about reflection. We avoided reflection as much as possible in our application and scanning fields manually. But after some period of time, we felt majority of our code base is for scanning. Most of the database queries involves multiple tables, I am not sure about the code generation approach either.
