### ISSUE TITLE
Means for dealing with session level state problems.

### ISSUE THREAD

**Issue by josephglanville** [jackc/pgx#110]
Hi @jackc,

I encountered a problem with prepared queries and migrations that led me to think about how to deal with this class of problems with pgx.
Specifically my problem is we pre-prepare all queries on all connections using the `ConnPool` `AfterConnect` hook.
If then another instance of my program runs a database migration that alters the type of a column these prepared queries will become invalid if they make use of this column and return:
```
ERROR: cached plan must not change result type (SQLSTATE 0A000)
```

The issue here is that this is a session state error. To correct this I would need to either deallocate that query and re-prepare it or close that connection and allow the connection pool to establish a new one.
pgx currently doesn't provide any good interfaces for accomplishing this for queries that occur within a transaction. I have wrapped the `ConnPool` and can handle it on standard `Exec`/`Query` but the Tx object takes full control over the connection and wants to call `Release` on it itself.

Do you have any ideas on how we could incorporate a hook or something that would be called on `Exec`/`Query` on a `Tx` that would then store a flag to call `Close` on the connection before `Release`? (because `Rollback` will probably be called after returning the `Error` anyways)

**Comment by josephglanville** [comment]
I pushed up a proposed solution here: #111

I then use this hook to check if the error is a one which I consider to be a session state problem and if so call `conn.Close`, which will cause new connections to be spawned as the query is retried.

**Comment by jackc** [comment]
This is a tricky problem.

A connection-wide on error handler has a few downsides. 1. We need to be sure to call it every place an error could occur not just Query and Exec (like ListenForNotification?) 2. It moves the error handling away from where the error occurred -- it feels like an exception handler -- not very Go-like.

That said, I don't have any ideas that I really like better either. Here's some of the things I've been considering though:

1. Prepared statements on ConnPool. This was requested back in #68. If this were in place it might be a simple solution to re-prepare statements that have changed.
2. Exposing Conn on Tx. Don't really like this because the Conn and Tx state could really get confused.
3. Exposing a CloseConn method on Tx. Better than the above idea, but still feels a little off.
4. Adding a Reset method to ConnPool that would close all connections and reestablish them as needed. This might be fairly clean.

Also, just out of curiosity, what sort of column type changes can be fixed by a re-prepare, but don't require a different Go type to be Scan'ed or Exec'ed? I would expect you would need to change the Go program as well.

**Comment by josephglanville** [comment]
4. Is definitely something I considered but I still hit the wall of how do I handle this a the connection pool level without handling at every point where I call Exec/Query or unpack a Row that contains an error?

As for when you change a column type that doesn't make a query invalid.. in my specific case it was a matter of changing from an enum to a varchar column with foreign key to a table with values populated with the previous contents of the enum. This scans to and from a string type still but is a different postgresql type.

**Comment by jackc** [comment]
I'm really struggling to think of a general purpose solution that solves this problem.

I looked some more into the `Conn` error handler approach and there are about 10 additional methods that would need to hook into that. That could be difficult to reason about. Another issue is this error handler would probably only capable of closing the `Conn`. Anything else would be very difficult to do reliably because the handler could be called from very different contexts (e.g. outside of a transaction it could make new queries, inside a transaction it could not, and it's hard to even guess what the state of the connection would be inside of a `Rows` `Scan` error).

I still don't have anything I really do like, but here's a few more ideas to throw at the wall and see if anything sticks.

1. Restructuring prepared statements to be lazy, whether on the `ConnPool` or not. The pgx send prepared statement path could directly detect the "cached plan must not change" error and deallocate the prepared statement. It would lazily be recreated next time. Though, this might run into the issue of being unable to deallocate the prepared statement while in a failed transaction.
2. Making pgx `Conn`, `ConnPool`, `Tx`, and `Rows` more easy to wrap/extend. I'm not sure exactly what this would entail, but it might enable solving this problem at the app layer (as well as enabling a previously requested feature of automatically retrying queries on connection loss).
3. The app could use listen/notify. The migration would send a notification that the app would listen for. When it detects this notification it resets the `ConnPool`.
4. Presumably, there are other database migrations that cannot be handled by a simple re-prepare. Wouldn't this mean a system is already in place to update/restart your server on certain updates. Couldn't that just be used here and skip the app having to deal with it at all?

**Comment by josephglanville** [comment]
For my case 1. would work well.
2. Would also be great in general as it's often nice to wrap the pgx external interface in order to DRY up some application level patterns and error handling.
The issue still remains with that approach is that if you don't expose additional interfaces on `Tx` you can't safely do anything with session level state.
3. This is a definite posibility. Will need to add something to reset the `ConnPool`.
4. I think is a last resort option. While you will have the occasional disruptive update the idea is that if there is a zero downtime way to do it that should be preferred.

**Comment by jackc** [comment]
I just added a Reset method to ConnPool. That should get us part way to a solution.

I think making pgx easier to wrap is the best long-term solution. Still thinking about what that actually means though.

**Comment by josephglanville** [comment]
@jackc I ended up implementing the listen/notify solution with the new `ConnPool.Reset()` which works very well for my use case. Do you want to keep this issue open for discussions of long term solutions to the broader class of session state problems?

**Comment by jackc** [comment]
Yes, let's leave it open. I think there is more to improve here, just not sure what yet.

**Comment by jackc** [comment]
After thinking about it a bit more, I have reconsidered adding a `Conn()` method to `*Tx`. I've also added a `AfterClose()` hook. This hook will be called after the transaction is completed (regardless of commit or rollback and success or failure) but before the connection is returned to the pool. This gives a chance to do any session-level fixes, or more likely just call `Close()` on the `Conn` (the connection pool will automatically discard any closed connections when they are released).

I also added `AfterClose()` and `Conn()` to `*Rows`. This should make it easier to add custom behavior to `Query` when called from `ConnPool`.

These changes are on `master` only, I haven't merged them into the stable `v2` branch yet.

**Comment by cbandy** [comment]
@josephglanville wrote:

> While you will have the occasional disruptive update the idea is that if there is a zero downtime way to do it that should be preferred.

I thought I'd mention that server-side functions may be another option. iiuc, these can change at the same moment as the schema, while continuing to provide a stable interface to your application.

**Comment by jackc** [comment]
I think I'm happy now with the above mentioned enhancements to pgx extensibility. I'm going to close this issue now. Let's start a new issue for any concrete extension point requests.
