### ISSUE TITLE
MinCons and MaxCons not evaluated correctly in 4.14.0

### ISSUE THREAD

**Issue by fasmat** [jackc/pgx#1117]
Hi,

I just updated from 4.13.0 to 4.14.0 and I'm now receiving errors that I wasn't receiving before. Here is an example test:

```go
func Test_PGX(t *testing.T) {
	config, err := pgxpool.ParseConfig("postgres://postgres:postgres@localhost:5432/coke_development?sslmode=disable")
	if err != nil {
		t.Fatal(err)
	}

	config.MaxConns = 100
	config.MinConns = 10
	config.MaxConnLifetime = 30 * time.Minute
	config.MaxConnIdleTime = 5 * time.Minute

	for i := 0; i < 20; i++ {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		_, err = pgxpool.ConnectConfig(ctx, config)
		if err != nil {
			t.Log("Error received at: ", i+1)
			t.Fatal(err)
		}
	}
}
```

The test above passes in 4.13.0, but in 4.14.0 it fails after trying to open an 11th connection.

**Comment by jackc** [comment]
> The test above passes in 4.13.0, but in 4.14.0 it fails after trying to open an 11th connection.

The change that probably caused this is that min connections are immediately established instead of waiting for the background health check. Your test is trying to open 20 **pools** each with a minimum of 10 connections. You don't include what the error message is, but if I had to guess it is no more connection slots available on the server. Failing on the 11th iteration would match your server being configured to allow 100 connections.

**Comment by fasmat** [comment]
@jackc thanks for the quick response. The error was something like "too many clients". So it's just my misunderstanding of what a client and a pool is? 😅 

Guess I'll have to adapt my code then.

**Comment by jackc** [comment]
Right, a pool can handle many connections. And unless you have a very unusual application you should only have one pool.
