### ISSUE TITLE
UUID Type Information

### ISSUE THREAD

**Issue by bbernays** [jackc/pgx#1122]
In the following query the data type returned from pgx query has no type information that it is a UUID:

``` go
	data, err := e.conn.Query(ctx, 'select '95c7f238-c6b8-4d0b-ab90-d26fef023d6b'::uuid')
	if err != nil {
		return nil, fmt.Errorf("%s: %w", q.Name, err)
	}
	for data.Next() {
		values, err := data.Values()
		for i := range values {
			fmt.Printf("Underlying Type: %T, value: %+v\n", values[i], values)
		}
```
output: `Underlying Type: [16]uint8, value: [149 199 242 56 198 184 77 11 171 144 210 111 239 2 61 107]`

I can see that the`func (dst UUID) Get() interface{}` method for that type in the `pgtype` package explicitly only returns the underlying `[]byte`

https://github.com/jackc/pgtype/blob/75446032b914bb0be5e07da29c976034c0a666cf/uuid.go#L66

There are no tests that cover this section of code at the moment. Was it the intention to only return the Bytes attribute? Or is this a bug?

**Comment by bbernays** [comment]
For others seeing this same thing, we were able to override the default UUID data type by attaching a new data type via the pgx pool `AfterConnect` method.

```
poolCfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		UUIDType := pgtype.DataType{
			Value: &UUID{},
			Name:  "uuid",
			OID:   pgtype.UUIDOID,
		}

		conn.ConnInfo().RegisterDataType(UUIDType)
		return nil
	}
```

We then copied the UUID implementation from `pgtype` into our package and made the following single line adjustment:

```
func (dst UUID) Get() interface{} {
	switch dst.Status {
	// Return the entire object, not just the dst.Bytes
	case pgtype.Present:
		return dst
	case pgtype.Null:
		return nil
	default:
		return dst.Status
	}
}
```

**Comment by jackc** [comment]
> Was it the intention to only return the Bytes attribute?

Yes. The `Value` interface defines `Get` as returning the simplest possible representation of of the value.

e.g. `pgtype.Int4.Get()` will return an `int32` or `nil` rather than a `pgtype.Int4`.

https://github.com/jackc/pgtype/blob/75446032b914bb0be5e07da29c976034c0a666cf/pgtype.go#L131

The simplest possible representation of a UUID is `[16]byte`.

FYI, in this particular case there is also an [extension](https://github.com/jackc/pgtype/blob/75446032b914bb0be5e07da29c976034c0a666cf/ext/gofrs-uuid/uuid.go) for the [github.com/gofrs/uuid](https://github.com/gofrs/uuid) package that you may find useful.
