### ISSUE TITLE
How does it affect user response time if I use a single *pgxpool.Pool thread for all website activities?

### ISSUE THREAD

**Issue by curiosport** [jackc/pgx#1131]
The actions of the users towards the database are simple and in a normal situation should take maximum 1 second to be answered.

My doubt comes when for example if in the website there are **20 million users** and I have created a single thread `*pgxpool.Pool` (for everything) configured in `pool_max_conns=30000000`, as I understand pgx will automatically scale in such a way that it will use the 100 connections that PostgreSQL makes available, but how much will this affect the user response time? After all by using a single `*pgxpool.Pool` I am creating a long queue of queries.

If this is a bad idea and is a problem I have a plan B.

I would create a map of Pool connections like this:
```
mapPool := make(map[string]*pgxpool.Pool)

//util.GetPool returns a connection *pgxpool.Pool and sets the variable "pool_max_conns" to 10000
mapPool["register"] = util.GetPool(10000)
```

Each pool connection will have a name according to the tables they modify, some will be for read only, some for write only and some more like a mix of both, also each connection will have a different value for the `pool_max_conns` variable.

Should I stick with my plan B or can I rely on the original plan or are there other better ideas to handle this?

**Comment by jackc** [comment]
`pool_max_conns` should typically be at most the number of CPUs * 2.

pgxpool should behave in roughly the same manner as any other application level connection pool such as the Go `database/sql` pool or the Ruby on Rails ActiveRecord pool.

In almost all cases you should have only one `*pgxpool.Pool` per process. Only obvious exception is if you had read-only PostgreSQL replicas and had a different pool for them.

If you really need to scale to 20M concurrent users then you have many, many, many other things to worry about.

**Comment by curiosport** [comment]
> 

From the answer you gave me I was researching and came across this article:
[SCALE FROM ZERO TO MILLIONS OF USERS](https://systeminterview.com/scale-from-zero-to-millions-of-users.php)

And what I need is an architecture with a **"Load balancer"** and then I would only need one `*pgxpool.Pool` per server.

So to give me an idea, can you tell me how many users can pgx/PostgreSQL handle on a VPS with 8 cores and 16GB of RAM? Consider that server will be exclusively for the database.

**Comment by jackc** [comment]
> So to give me an idea, can you tell me how many users can pgx/PostgreSQL handle on a VPS with 8 cores and 16GB of RAM? Consider that server will be exclusively for the database.

That really depends on what you are doing with it. And you would probably be better off thinking in terms of requests per second instead of users. A content site may have users that only make a request every few seconds or minutes where some sort of highly interactive tool may have multiple requests per second per user.

It also depends on how many SQL queries each HTTP request makes and how expensive the queries are. A `select * from foo where id = $1` is going to be pretty cheap (assuming id has an index). A query with many joins will be slower. Writes are also slower than reads.

The short answer is that VPS should handle a lot of traffic (e.g. tens of thousands of simple read queries per second). But based on your questions I assume you don't have millions of users now... assuming that is the case start with the simplest thing that will work. As your traffic increases you can benchmark your site and see where the bottlenecks are. Avoid [premature optimization](http://wiki.c2.com/?PrematureOptimization).

**Comment by curiosport** [comment]
I prefer to optimize bottlenecks on a scalable system than on a non-scalable system, as that will take a long time to go from one design to another, at first I thought that 20 million users was not that big of a deal and that a decent VPS would handle it without problems, but you made a comment that made me doubt about my design. That's why I looked at other architectures. Nothing else.

The information you gave me was very helpful thank you very much.
