### ISSUE TITLE
panic: BUG: unexpected error from stmtCache 

### ISSUE THREAD

**Issue by niksajakovljevic** [jackc/pgx#1156]
During high load PGX randomly panics. Prior to panic I see a lot of context timeouts. In my setup I have context timeout set to 5 seconds when doing batch inserts in parallel. The following stack trace gets generated:

```
panic: BUG: unexpected error from stmtCache

goroutine 15280 [running]:
github.com/jackc/pgx/v4.(*Conn).SendBatch(0xc059743f00, 0x1792860, 0xc0c2c5d980, 0xc00b71c300, 0xc05c11ac30, 0xc05c130280)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.15.0/conn.go:801 +0x1734
github.com/jackc/pgx/v4/pgxpool.(*Conn).SendBatch(0xc03878bb50, 0x1792860, 0xc0c2c5d980, 0xc00b71c300, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.15.0/pgxpool/conn.go:66 +0x6f
github.com/jackc/pgx/v4/pgxpool.(*Pool).SendBatch(0xc00097e150, 0x1792860, 0xc0c2c5d980, 0xc00b71c300, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.15.0/pgxpool/pool.go:543 +0x8c
```

I've digged a bit through PGX code and found a potential suspect on this line: https://github.com/jackc/pgconn/blob/master/pgconn.go#L1620
I wonder why`pgConn` is not closed at this point but just `unlocked`?
My hunch is that potentially unclean connection is being returned to the pool and used by other go routine making it panic?

**Comment by jackc** [comment]
I think the problem is a context expiration after the statement is first prepared and before it is retrieved for use. Since it is already prepared I assumed it was impossible for it to fail. That's why it is an explicit panic. But that assumption is wrong in case of context cancellation. I changed to to handle it as a normal error.

I've made this change on master. Let me know if it fixes it.

**Comment by niksajakovljevic** [comment]
Thanks for the quick feedback! Right `stmtCache.Get(ctx, bi.query)` can return an error due to context timeout. I'll give it a try and let you know.
