### ISSUE TITLE
The prepared statement cache cannot be deactivated

### ISSUE THREAD

**Issue by galdor** [jackc/pgx#116]
`Conn.Query()` caches prepared statements in `c.preparedStatements`. While it is useful in most common cases, it becomes a real problem when using code-generated SQL queries.

For example, in an application, if we want a user to be able to load items based on various key/value filters and sort criteria, we need to generate a SQL query based on all the filters and criteria.

With the current code, `c.preparedStatements` will be filled with lots of generated queries which will never (or very rarely) be reused.

Would it be possible to manually disable the prepared statement cache ? Or to have a query function which does not cache the statement ?

I may try to write a patch, but you maybe have a better idea :)

**Comment by jackc** [comment]
Can you give me an example code demonstrating this behavior? This is not intentional (or known to me) behavior. Conn does not have any (intentional) automatic prepared statement caching.

If you call Query it checks the map of prepared statements to see if it is the name of a prepared statement. If not, it is considered to be a SQL string. It then prepares a statement with the special name of empty string. Note that it does not store it in c.preparedStatements. 

```go
	ps, ok := c.preparedStatements[sql]
	if !ok {
		var err error
		ps, err = c.Prepare("", sql)
		if err != nil {
			rows.abort(err)
			return rows, rows.err
		}
	}
```

Prepared statements named the empty string denote the "unnamed prepared statement" to the PostgreSQL backend. The unnamed prepared statement is automatically cleaned up by the server upon use. See http://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY for the details.

So there shouldn't be any accumulation of prepared statements in the Go client program or the server when calling Query with a string.

**Comment by galdor** [comment]
You are absolutely right, it seems I read the code too quickly and assumed incorrectly. Thank you for taking the time to explain it this clearly.

By the way, we are using pgx in our company, and it worked perfectly so far. Thank you for your work !

**Comment by whoiscarlo** [comment]
> Can you give me an example code demonstrating this behavior? This is not intentional (or known to me) behavior. Conn does not have any (intentional) automatic prepared statement caching.
> 
> If you call Query it checks the map of prepared statements to see if it is the name of a prepared statement. If not, it is considered to be a SQL string. It then prepares a statement with the special name of empty string. Note that it does not store it in c.preparedStatements.
> 
> ```go
>     ps, ok := c.preparedStatements[sql]
>     if !ok {
>         var err error
>         ps, err = c.Prepare("", sql)
>         if err != nil {
>             rows.abort(err)
>             return rows, rows.err
>         }
>     }
> ```
> 
> Prepared statements named the empty string denote the "unnamed prepared statement" to the PostgreSQL backend. The unnamed prepared statement is automatically cleaned up by the server upon use. See http://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY for the details.
> 
> So there shouldn't be any accumulation of prepared statements in the Go client program or the server when calling Query with a string.

Oddly enough I'm running into this exact issue when using Supabase. I've messaged their team, but can't seem to find the cause of it

**Comment by jackc** [comment]
@whoiscarlo This issue is from 7 years and several major versions ago. pgx now does have automatic prepared statement caching enabled by default. You can change this with [QueryExecMode](https://pkg.go.dev/github.com/jackc/pgx/v5#QueryExecMode).

I would suspect this is a configuration or Supabase issue, but if you do find an issue with pgx please create a new issue rather than resurrect this old one.
