### ISSUE TITLE
Scan wrong boolean value

### ISSUE THREAD

**Issue by OnlyC** [jackc/pgx#1163]
The `rows.Scan` return wrong value of my boolean value, always return `false`.

Notice that the raw value is correct, there are true and false values ( 102, 116).
![image](https://user-images.githubusercontent.com/1250580/156737861-25d8b937-5cbd-4f90-8b6e-0f354b9f6ab1.png)

![image](https://user-images.githubusercontent.com/1250580/156738096-28857d84-dc58-4675-83a3-4f0a8f51ada2.png)

I tried `lib/pq` package and it's working correctly but I want to use decimal scan from pgxtype.

**Comment by jackc** [comment]
There's something funny going on here. Your first result column `ts` is apparently a `timestamp[tz]` returned in the binary protocol. I would assume your second result column `buy` is supposed to be a boolean. But if so it should return binary `1` not `116` / `f`. I think the `Scan` is looking for `1` and not finding it. My guess is `buy` is not actually a boolean type.

**Comment by OnlyC** [comment]
It is boolean type, I double checked. But im using questdb with postgres
driver.

**Comment by jackc** [comment]
I'm not familiar with questdb but maybe it doesn't format boolean the same way in binary format.

You could try passing `pgx.QueryResultFormats{pgx.TextFormatCode}` or `pgx.QueryResultFormats{pgx.BinaryFormatCode}` as the first query argument to force the use of the text or binary formats respectively. My guess is that the db server is returning the `t` or `f` instead of `0` or `1` for the binary format of `boolean`.

**Comment by OnlyC** [comment]
`pgx.QueryResultFormats{pgx.TextFormatCode}` solved this. 
I'll open an issue on questdb in case someone getting this problem.

Thank you!
