### ISSUE TITLE
Connection pool MinConns question

### ISSUE THREAD

**Issue by jvmiert** [jackc/pgx#1164]
It takes ~2 seconds for dailing to complete to my db (is this normal?).

When the `MaxConnIdleTime` is reached, the connection is closed during the next `HealthCheckPeriod`. However, if I set the `MinConns` > 0, then a new connection is not opened right after closing the previous connections that idle timed out. Only during the next elapse of the `HealthCheckPeriod` are new connections added to the pool. This means that if a request is made during this period, the user has to wait for dailing to complete to receive the response.

So if I set the `HealthCheckPeriod` to 20 seconds, then there is potentially a 20 second window where the pool has no available connections standing by.

Am I understanding this correctly? Or am I doing something wrong?

Just an example to illustrate my issue:

**Config**
```
MaxConnIdleTime = 5 * time.Second
MaxConns = 10
MinConns = 2
HealthCheckPeriod = 20 * time.Second
```

**Log**
```
time="2022-03-06T20:10:03+07:00" level=info msg="Dialing PostgreSQL server" host=localhost
time="2022-03-06T20:10:03+07:00" level=info msg="Dialing PostgreSQL server" host=localhost
time="2022-03-06T20:10:23+07:00" level=info msg="closed connection" pid=1381
time="2022-03-06T20:10:23+07:00" level=info msg="closed connection" pid=1380
time="2022-03-06T20:10:43+07:00" level=info msg="Dialing PostgreSQL server" host=localhost
time="2022-03-06T20:10:43+07:00" level=info msg="Dialing PostgreSQL server" host=localhost
```

**Comment by jackc** [comment]
> It takes ~2 seconds for dailing to complete to my db (is this normal?).

No. Connecting to local server takes ~6ms on my development machine. And connecting to a remote server on Digital Ocean with TLS takes ~220ms. 

> When the MaxConnIdleTime is reached, the connection is closed during the next HealthCheckPeriod. However, if I set the MinConns > 0, then a new connection is not opened right after closing the previous connections that idle timed out. Only during the next elapse of the HealthCheckPeriod are new connections added to the pool. This means that if a request is made during this period, the user has to wait for dailing to complete to receive the response.

> So if I set the HealthCheckPeriod to 20 seconds, then there is potentially a 20 second window where the pool has no available connections standing by.

> Am I understanding this correctly? Or am I doing something wrong?

That is the way it works, though only due to circumstance.

* Destroying / closing a connection happens in a goroutine. This prevents destroying a connection from being a blocking operation.
* The connection is only removed from the pool after it is destroyed. This ensures that max connections is not violated by creating a new connection while the old connection still exists.
* The check for min connections runs immediately after the check for idle connections. If the idle connections haven't finished closing then they will still be counted as in the pool.

I don't see any simple way to change this behavior.

**Comment by jvmiert** [comment]
> > It takes ~2 seconds for dailing to complete to my db (is this normal?).
> 
> No. Connecting to local server takes ~6ms on my development machine. And connecting to a remote server on Digital Ocean with TLS takes ~220ms.

This seems way more reasonable and makes the downtime between health checks less of a problem. Long connection times was a result of [WSL weirdness](https://dba.stackexchange.com/a/229841) in case anyone cares.

Just wanted to give you a quick thanks for the hard work you put into the library. It's been great working with it!

**Comment by jackc** [comment]
> Just wanted to give you a quick thanks for the hard work you put into the library. It's been great working with it!

Glad to hear it!

> Edit: For my usecase I don't have a problem with this issue anymore. However, I was thinking, would staggering the connections on start-up maybe make it so that there's always a connection available? Just a thought.

Maybe... would depend on the relation between how much the staggering is applied vs the health check time vs the max idle time. But I think it would be difficult to get the balance right.

But I think / hope this is not likely to be a problem in production.

1. Connect is normally fairly quick as mentioned above.
2. It seems unlikely that there would be little enough traffic that connections would be closed from idleness, but at the same time enough traffic that it would hit the window where the connection is being recreated.

---

Hmmm... random other idea. Actually, the simple solution would be to not close a connection due to idleness if it would bring the pool to less than min connections. Kind of pointless to close a connection due to idleness only to immediately reconnect. We could still respect max connection lifetime as that is more to ensure that no resources are consumed too long on the client or server.

I don't plan on implementing this right now, but I'll leave this note for future reference as this is probably the right solution if this is an issue for anyone else.
