### ISSUE TITLE
can't scan into dest[0]: unable to assign to custom date type

### ISSUE THREAD

**Issue by not-rusty** [jackc/pgx#1168]
Hello there!

I've encountered a similar bug as one I reported before https://github.com/jackc/pgx/issues/1151

Versions used:
- github.com/jackc/pgconn v1.11.0
- github.com/jackc/pgx/v4 v4.15.0

To reproduce:

```sql
create table dates (
    date timestamp with time zone
)
```

And the following code errors:

```go
    (... init connection ...)

    type customDate time.Time

    var date customDate

    row := db.Pool.QueryRow(context.Background(), `
        select date from dates
        limit 1
    `)

    err = row.Scan(&date)

    fmt.Println(date)
    fmt.Println(err)

```

But the following one does not:

```go
    type customDate time.Time

    var date time.Time

    row := db.Pool.QueryRow(context.Background(), `
        select date from dates
        limit 1
    `)

    err = row.Scan(&date)

    fmt.Println(date)
    fmt.Println(err)
```

**Comment by jackc** [comment]
It is similar #1151, but the solution is not so simple. When the underlying type of a custom type is a builtin language level type like `int32` or `float64` the `Kind()` method in the `reflect` package can be used to find what it really is. But for a struct that is all `Kind()` knows -- that it is a struct.

There _may_ be some additional reflect magic that could test if one struct is equivalent or assignable to another that could _maybe_ handle this case but I'm not sure if it can be done or if it should be done even if possible. Because it would also need to interact with all the other magic like allocating new objects and assigning `nil` when using scanning into `**customDate`. The code that tries to figure out how to handle types that don't directly implement pgx or database/sql interfaces is probably the messiest / most complicated / hardest to reason about code in the entire pgx project.

**Comment by not-rusty** [comment]
Didn't know the issue was that messy. I wouldn't like to promote adding that much complexity to the project just to handle such an edge case like this one, so I'm gonna close this.

Thanks for this library @jackc!

**Comment by euphbriggs** [comment]
@not-rusty I'm not sure if this would help you in your use case, but I ended up doing something similar to this. `Scan()` operates with `time.Time` then I wrapped it in `customDate` before returning the value.

```Go
type customDate time.Time

var date time.Time
row := db.Pool.QueryRow(context.Background(), `
    select date from dates
    limit 1
`)

err = row.Scan(&date)

return customDate(date), err
```
