### ISSUE TITLE
query issue

### ISSUE THREAD

**Issue by goldfix** [jackc/pgx#118]
Hi

I have a small problem. When try to execute this simple function:

```
CREATE OR REPLACE FUNCTION test_pgx()
  RETURNS TABLE(o_test int) AS
$BODY$
begin
	RAISE EXCEPTION 'test error!';
	
	return query
	select 1 as col
	UNION ALL
	select 2 as col;

	
end;
$BODY$
  LANGUAGE plpgsql STABLE
  ;
```

but my code do not return any error (err==nil):
```

	fmt.Println("Start...")

	var err error
	var conf pgx.ConnConfig
	conf.Database = "blocketdb"
	conf.Host = "127.0.0.1"
	conf.Password = "Qwertyuiop01"
	conf.User = "postgres"
	conf.Port = 5432
	conf.LogLevel = pgx.LogLevelInfo

	conn, err := pgx.Connect(conf)
	if err != nil {
		fmt.Printf(err.Error())
	}

	defer conn.Close()

	rows, err := conn.Query("select * from test_pgx() as t(a);")

	if err != nil {
		fmt.Printf(err.Error())
	}
	defer rows.Close()

	for rows.Next() {
		var n *int32
		err = rows.Scan(&n)
		if err != nil {
			fmt.Printf(err.Error())
		} else {
			fmt.Printf("%d\n", *n)
		}
	}
```

**Comment by jackc** [comment]
Add this to the bottom and it will catch the error.

```go
if rows.Err() != nil {
	fmt.Println(rows.Err())
}
```
Here's what is happening. There is no error returned from `conn.Query` because that is only responsible for sending the query, and that happens successfully. When `rows.Next()` tries to read the first row, it sees the error, so it returns false because it can't read a row. So the entire body of the loop is skipped. You need to check rows.Err() at the end of a query to see if it completed successfully.

See https://godoc.org/github.com/jackc/pgx#hdr-Query_Interface for a complete example.

**Comment by goldfix** [comment]
Perfect!

thanks for your patience! :+1: 

ciao
p
