### ISSUE TITLE
PGX POOL seems to successfully commit the transaction despite it throws a context timeout error

### ISSUE THREAD

**Issue by anadoba** [jackc/pgx#1223]
Hello!

I am writing this knowing that it may not be easy to reproduce. Actually, the issue happens only during heavy load, when the connection pool does self-maintenance and closes/opens/rotates its connections.

What happens step by step:
1. Create a context with a timeout
2. Open a transaction
3. Do stuff, insert things to a table with a unique index
4. TX Commit
5. defer TX Rollback with its own, prolonged ctx timeout.

All steps above are also wrapped with a retry func. If any step between 1 and 4 returns an error, the whole procedure is repeated.
One thing to note, my transaction is not idempotent so it is heavily reliant on commit/rollback behaviour.

What can I see in the logs?
Step 4 (commit) throws `timeout: context deadline exceeded`
Occasionally, I can see step 5 (rollback) logging error `conn closed`
Retry kicks in, during the next attempt step 3 (inserting stuff) starts to throw unique index-related errors.

I have been observing this behaviour in different production environments since a year ago.
It _always_ happens during connection pool self-maintenance, when it goes from, for example, min conns (16) to 9 for a moment, and then goes up to 16 again. The max conns is 64, it is never reached due to huge Postgres nodes.

Any idea how to mitigate it? Or maybe the library has a bug somewhere inside the transaction commit + context timeout logic? Maybe it is affected by self-maintenance, which seems to make the pool go below the configured min conns for a moment?

**Comment by jackc** [comment]
It's hard to say, but here are a few factors to consider.

* Depending the circumstances a context cancellation may be impossible to recoverable from. And when it is recoverable it is still tricky. Because of this a context cancellation will usually kill the connection.
* Any error from the deferred tx rollback should usually be ignored. Either the transaction is already committed in which case it will return an ignorable error or a rollback failure should be fatal to the connection.
 
But If the root issue is commit returning an error but still being committed, that may be difficult to handle correctly. That would happen if the timeout occurred after the `commit` is sent to PostgreSQL but before the response was received. In that case I don't know any other solution than to query the database for something written in the original attempt before retrying.

**Comment by jackc** [comment]
So yeah, rereading your message I would posit that here is what is happening:

In your step 4 the `commit` is sent to PostgreSQL and the context is cancelled before the response is received. The context cancellation causes the connection to be closed.

In your step 5 you get the `conn closed` error.

You retry due to these errors, but the previous attempt actually had committed.

**Comment by anadoba** [comment]
Thank you for spending some time and providing an answer.
Sadly, you have confirmed my way of thinking. I'll try to either make the transaction idempotent or do an additional query inside it.

The only part, which remains not so clear to me is the connections count here.
Does lowering the connections count for a quick moment (pool self-maintenance/health-check) cause the timeouts?
Or it is the other way around, so errors during commit/rollback cause connection termination?

**Comment by jackc** [comment]
> Does lowering the connections count for a quick moment (pool self-maintenance/health-check) cause the timeouts?

Possible, but that wouldn't be my first guess. You could find out for sure by raising or disabling the health check limits.

> Or it is the other way around, so errors during commit/rollback cause connection termination?

A timeout will typically kill the connection.

**Comment by anadoba** [comment]
Thank you very much @jackc 
Not only for these answers but also for the whole lib in general.
As you could read, we have been using it in our different prod environments for 10+ months already.
