### ISSUE TITLE
How to generate mock pgxpool connection

### ISSUE THREAD

**Issue by sagar-work** [jackc/pgx#1225]
Hello everyone,

I have a function with parameter of type pgxpool.conn .I want to write unit test for that function but I don't know how to pass mock pgxpool connection.

Thanks!

**Comment by jackc** [comment]
Mocking the entire database action is technically possible. i.e. Everything needed can be an interface instead of a real type. But it is quite difficult. You would need to have your application and tests use an interface instead of a pgx type. e.g.

```go
type DBConn interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, optionsAndArgs ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, optionsAndArgs ...any) pgx.Row
}
```

But the real trick is then you would need to have your test connections `Query` and `QueryRow` methods return something that also implemented `pgx.Rows` and `pgx.Row` respectively. And implementing `Scan` on those would be quite the trick. I don't recommend it.

Personally, I think integrating over the database is almost always the right decision. When that's not feasible I would prefer to mock the data access layer above the actual database driver or worst case use something like https://github.com/jackc/pgmock to actually fake a real database connection.
