### ISSUE TITLE
Mocking pgx pool connection for unit testing 

### ISSUE THREAD

**Issue by super3programmer** [jackc/pgx#1231]
Hello,
	I am trying to write a unit test for a function in which I fetched pgxpool connection from another microservice. But I am not understanding how to write unit test for this function and how to get mock pgxpool.Conn
	
	E.g.
	Func (a *ADB) Create(ctx *gin.Context, userID uuid){
		pgxpoolConn, err := a.dbservice.GetConnection(ctx)
		//GetConnection is function of DBService(microservice) which returns the single connection of  pgxpool

		pgxpoolConn.QueryRow(ctx, query, arguments)
		//Using that pgxpool connection takes the actions on the DB
	}

Thanks!

**Comment by nikitacrit** [comment]
Hello!
1. Create your own interface, build mock with standard mock library (gomock, mockery). **- complex solution**
2. Use https://github.com/DATA-DOG/go-sqlmock. You also need to create your own interface because of capability between standard sql db and pgxpool signatures. Core problem - go-sqlmock support standart go sql db interface **- complex solution**
3. Just use https://github.com/pashagolub/pgxmock. All described above already done by community. **- ok solution**

**Comment by bfontaine** [comment]
ping @jackc you might have missed that one

**Comment by jackc** [comment]
There is no built-in mocking framework for pgx.

But here are three approaches for testing with pgx.

First, I typically integrate over the database when possible.

Second, when testing lower level functionality, the pgmock package allows mocking the database server. This is very low level and should probably **not** be used for application level testing, but it is possible.

Lastly, the application can define its own connection interface. e.g.

```go
type DB interface {
	Query(ctx context.Context, sql string, optionsAndArgs ...interface{}) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, optionsAndArgs ...interface{}) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}
```

In your case `a.dbservice.GetConnection(ctx)` would return that `DB` interface instead of an actual pgx type. In testing your service could return a mock interface.

**Comment by StevenACoffman** [comment]
This comes up a lot and this issue gets referenced a lot, so I just wanted to add a bit more nuance to what has been said.

The sharp distinction between "unit" and "integration" tests, with anything talking to a "real" database being by definition an integration test is rooted in the need that developers need a tight feedback loop. It used to be that starting up a local database or talking to an non-local database was very slow. The distinction has become less useful over time, but we haven't come up with better words to describe more modern classifications due to test "size" (which is itself kind of a bad description). See more here:

- https://www.matttproud.com/blog/posts/revisiting-test-sizes.html
- https://michael.stapelberg.ch/posts/2024-11-19-testing-with-go-and-postgresql-ephemeral-dbs/

**Comment by jackc** [comment]
For another way of making tests using a real database faster check out another project of mine: https://github.com/jackc/pgundolog. It is handy when you can't use transactions to efficiently rollback changes made by a test.

**Comment by StevenACoffman** [comment]
I circled back to this a bit and [made a pgx and pgxpool fork](https://github.com/StevenACoffman/pgxtest/ ) of  [Roxy Light’s postgrestest package](https://pkg.go.dev/zombiezen.com/go/postgrestest).

I would like it to eventually incorporate more of the techniques in https://michael.stapelberg.ch/posts/2024-11-19-testing-with-go-and-postgresql-ephemeral-dbs/ like a tiny helper command to share the instance as in: https://github.com/gokrazy/gus/commit/b97c652fd03754ba817bd3c13f18ea6e2e154ef4#diff-5f289a54bf40fa4d4d107f50311dcaf4e741644956f53f24ca2d460532c61f28
