### ISSUE TITLE
Protocol problem with error responses

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#125]
This may be two separate issues, but I'm not sure.

So I have some test code that does this in parallel transactions:

```go
rows, err := tx.Query(`SELECT * FROM test_docs WHERE id = 1 LIMIT 1 FOR UPDATE NOWAIT`)
```

On the Postgres side, this sometimes fails, for good reason:

    ERROR:  could not obtain lock on row in relation "test_docs"

But pgx seems to misparse the protocol response:

    &errors.errorString{s:"Received unknown message type: C"}

---

Here's where it gets weird for me. If I have an insert after the select:

```go
rows, err := tx.Query(`SELECT * FROM test_docs WHERE id = 1 LIMIT 1 FOR UPDATE NOWAIT`)
if err != nil {
    log.Fatal(err)
}
if _, err = tx.Exec(`INSERT INTO test_txns (doc_id) VALUES ($1)`, 1); err != nil {
    log.Fatal(err)
}
```

then no select fails, but the _insert_ fails instead with:

    &errors.errorString{s:"Prepared statement \"\" requires 0 parameters, but 1 were provided"}

Meanwhile, the Postgres server log shows that the `SELECT` actually failed before that.

---

These may be separate issues, I don't know. But the second problem only occurs when there is a locking error. It's almost as if they're accidentally sharing the same underlying state, like the TCP connection itself.

Here both test cases: [pgxissue.tar.gz](https://github.com/jackc/pgx/files/174546/pgxissue.tar.gz). Output:

```
# sudo -u postgres createuser -s test
# sudo -u postgres createdb -O test test
# sudo -u postgres psql -d test -f schema.sql
# go run pgxtest1/pgxtest1.go
2016/03/15 14:18:40 goroutine 1 failed to select: &errors.errorString{s:"Received unknown message type: C"}
# go run pgxtest2/pgxtest2.go 
2016/03/15 14:18:25 goroutine 1 failed to insert: &errors.errorString{s:"Prepared statement \"\" requires 0 parameters, but 1 were provided"}
```

PostgreSQL 9.5.1, pgx is latest HEAD (d88242b).

**Comment by jackc** [comment]
Thanks for providing great, reproducible test cases. The bug was a real edge case that would have been very difficult to track down without them.

The problem was when a `Rows.Close()` was called before the results of the query are read *and* there is an error on the wire waiting to be read. `Rows.Close()` is supposed to read until it gets the "Ready for Query" message from the server. But it would stop if it received an error message from the server. This would leave unread messages on the wire that would confuse the next operation.

With this fix in place your test cases should pass, though since the NOWAIT option does cause an error, it breaks the transaction, so you would either need to rollback or swallow the `pgx.ErrTxCommitRollback` error when calling Commit on a dead transaction.

**Comment by atombender** [comment]
Awesomely fast fix, thank you. I'll give it a go.
