### ISSUE TITLE
Timeout around creation of pool resources

### ISSUE THREAD

**Issue by jameshartig** [jackc/pgx#1275]
I saw in 7ce634d62b474a0a1e4683138d7ee1258bd4f34e you added a 2 minute timeout but I don't think that's necessary since pgconn already adds a timeout: https://github.com/jackc/pgconn/blob/master/pgconn.go#L141

If you wanted to do something it should be based on a configurable time or at the very least make sure it's not less than the ConnectTimeout.

**Comment by jackc** [comment]
`ConnectTimeout` is supported but not set by default. Without that set a background connect could hang forever.

I chose 2 minutes because I couldn't imagine a successful connection taking longer, but I suppose we could change it.

I suppose that another solution would be to set a default `ConnectTimeout`. If someone disabled it then the consequences are on them.

**Comment by jameshartig** [comment]
Rather than defaulting `ConnectTimeout` which might be a bigger change right now. Maybe we should just set the 2 minute timeout in this case only when there is no `ConnectTimeout`.

**Comment by jameshartig** [comment]
Maybe v5 could default a `ConnectTimeout`?

**Comment by jackc** [comment]
> Rather than defaulting ConnectTimeout which might be a bigger change right now. Maybe we should just set the 2 minute timeout in this case only when there is no ConnectTimeout.

Done on v4 (1d748d9b) and v5 (c842802d).

**Comment by jameshartig** [comment]
Thanks for the quick fix!
