### ISSUE TITLE
How to disable automatically perpared statements

### ISSUE THREAD

**Issue by JamesInform** [jackc/pgx#1297]
Hi,

is it possible to not prepare a statement when executing a query?

I want to execute the following sql statement:

```
do
$$
begin
    create temp table myt as 
     select a from b;
end
$$
;

select a from myt;

```

I need the result from the last set returning sql statement, in this scenario "select * from myt".

Setting 
`config.PreferSimpleProtocol = true`
doesn't do the trick.

I can be sure that the sql is not "nasty". So sql injection is no problem in my scenario at all.

Cheers,
James

**Comment by JamesInform** [comment]
Btw. preparing statements in PostgreSQL is not guaranteeing better performance. They may indeed lead to unexpected performance drops and other issues.

With the default configuration PostgreSQL will build a custom plan during the first 5 executions and then switch to a generic plan. So for the first 5 executions a prepared sql statement is no different to an unprepared statement.

If the first generic plan (the one that is chosen beginning at the sixth execution) e.g. is not considering an index on a specific column, all subsequent query executions will likewise not consider the index although it may be much faster to use it.

See:
[How PostgreSQL 12 handles prepared plans](https://www.cybertec-postgresql.com/en/tech-preview-how-postgresql-12-handles-prepared-plans/)

**Comment by jackc** [comment]
`config.PreferSimpleProtocol = true` should make it use the simple protocol. It's also possible to control per query. But my guess is it *is* running the simple protocol, but the problem is `Query` only expects one response. So it reads the first response (i.e. the `create table`) and ignores the rest.

Practically speaking, I would recommend executing your SQL in two steps. The `create table` as an `Exec` and the `select` as a `Query`.

If for some reason that is not possible you can drop down to the pgconn layer and use it's `Exec()` method. It allows reading multiple query responses from a single simple protocol request. However, pgconn is much lower level and you may find it's interface less convenient (e.g. it does not do any type conversion).

**Comment by JamesInform** [comment]
Sounds reasonable.
Can you post a simple example of how to use pgconn.exec and retrieve multiple query responses?!

**Comment by jackc** [comment]
See `TestConnExecMultipleQueries` - https://github.com/jackc/pgconn/blob/15f8e6323e113feb44678e5cb16cfbeba4630bf6/pgconn_test.go#L606

**Comment by JamesInform** [comment]
Thank you very much for hinting me to the "pgconn_test.go".

That's exactly what I needed. Works pretty well. (At least for strings).

Maybe you can help with type conversion. The last three assignments are the problem:
```
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgconn"
)

func main() {
	config, _ := pgconn.ParseConfig(os.Getenv("PGX_TEST_CONN_STRING"))
	conn, _ := pgconn.ConnectConfig(context.Background(), config)
	defer conn.Close(context.Background())

	query := "select 1::int8 as myint, now() as mytimestamp, jsonb_build_object('mykey','myvalue') as myjson"

	results, err := conn.Exec(context.Background(), query).ReadAll()
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}

	// QUESTION: HOW TO CONVERT AND UNMARSHAL
	myint := int64(results[0].Rows[0][0]) // doesn't work
	mytimestamp := timestamp(results[0].Rows[0][1]) // don't know how to
	myjson := {unmarschaljsonb}(results[0].Rows[0][2]) // don't know how to
}
```
How can I convert to the correct GO type and how to handle JSONB in this context? How is NULL handled?.

I would really appreciate your help.

James

**Comment by jackc** [comment]
```go
	// QUESTION: HOW TO CONVERT AND UNMARSHAL
	myint := int64(results[0].Rows[0][0]) // doesn't work
	mytimestamp := timestamp(results[0].Rows[0][1]) // don't know how to
	myjson := {unmarschaljsonb}(results[0].Rows[0][2]) // don't know how to
```

Use https://pkg.go.dev/strconv#ParseInt to parse an int.
Use https://pkg.go.dev/time#Parse to parse a time.
Use https://pkg.go.dev/encoding/json#Unmarshal to unmarshal JSON into an object. 

But better than those would be to use https://pkg.go.dev/github.com/jackc/pgx/v4#ScanRow. It is designed as a bridge between pgconn and pgtype. 

---

But let me re-offer my earlier advice to use multiple queries instead of dropping down to pgconn. This is doing it the hard way and there are very few circumstances where this approach make sense.

**Comment by JamesInform** [comment]
Hi Jack,

thanks for your quick response and also for your re-offer. I will surely use the high level functions where possible. But in certain situations I have the need to simply run a sql of which I don't know if it is a single or a multiple statement. I am not able to parse the sql and identify the type. The only thing I can be sure of is that the last sql statement is a set returning sql with result columns I know, so that I can alway read the last result.

In this scenario the low level pgconn approach is really handy and seems to be the only viable solution available, isn't it?

**Concerning your previous answer:**
The manual parsing using the GO core functionality works fine.

What I am not getting right is the usage of ScanRow function:

Example:
```
var myint int64
HOW TO DEFINE THE VARIBLES mytime and myjson

pgx.ScanRow(conn, results[0].FieldDescriptions, results1[0].Rows[0], &myint, &mytime, &myjson)
```

- how to invoke ScanRow?
- how to get conninfo (the first parameter)?

Could you give an example for my scenario?

Cheers
James

**Comment by jackc** [comment]
[TestScanRow](https://github.com/jackc/pgx/blob/d42b399be3ec4153ccd7e8b84ee50e60751a6936/query_test.go#L1440)
[(*Conn) ConnInfo()](https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.ConnInfo)

**Comment by JamesInform** [comment]
Sorry, I still doesn't get it to work.

I try:

```
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v4"
)

func main() {
	config, _ := pgconn.ParseConfig(os.Getenv("PGX_TEST_CONN_STRING"))
	conn, _ := pgconn.ConnectConfig(context.Background(), config)
	defer conn.Close(context.Background())

	query := "select 1::int8 as myint, now() as mytimestamp"

	result, err := conn.Exec(context.Background(), query).ReadAll()
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}

	var (
		myint  int64
		mytime time.Time
	)

	pgx.ScanRow(conn.ConnInfo(), result[0].Rows[0].FieldDescriptions(), result[0].Rows[0].Values(), &myint, &mytime)

	fmt.Printf("int: %v, time: %v, %v", myint, mytime, result)

}

```

The comiler says:
```
./pg5.go:32:19: conn.ConnInfo undefined (type *pgconn.PgConn has no field or method ConnInfo)
./pg5.go:32:49: result[0].Rows[0].FieldDescriptions undefined (type [][]byte has no field or method FieldDescriptions)
./pg5.go:32:88: result[0].Rows[0].Values undefined (type [][]byte has no field or method Values)

```

How must the ScanRow line be written correctly?

**Comment by jackc** [comment]
* ConnInfo comes from a pgx: *Conn. https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.ConnInfo
* FieldDescriptions comes from a pgconn ResultReader: https://pkg.go.dev/github.com/jackc/pgconn#ResultReader.FieldDescriptions
* You will need to iterate over the `MultiResultReader` that comes back from `Exec()` instead of using `ReadAll()` to get a `ResultReader`.

**Comment by JamesInform** [comment]
Fine that helped much.

Additional question:
Is there an easy way to now how many results are in a MultiResultReader without iterating and grabbing all of them? Something like MutliResultReader.Count()

**Comment by jackc** [comment]
> Is there an easy way to now how many results are in a MultiResultReader without iterating and grabbing all of them? 

No. By sending multiple queries as a blob of SQL pgx doesn't know what to expect and the PostgreSQL server doesn't tell us.

**Comment by JamesInform** [comment]
Hi Jack!

Thank you very much for guiding in the right direction.

Now everything works fine.
