### ISSUE TITLE
[Question] pgtype with pgx v5

### ISSUE THREAD

**Issue by MindMayhem** [jackc/pgx#1298]
Hi, i have a question, we have package https://github.com/jackc/pgtype which use pgx v4, but at the same time it continues to be updated, the author makes commits

But at the same time we have this - https://pkg.go.dev/github.com/jackc/pgx/v5@v5.0.0-alpha.3/pgtype
but it doesn't have several types of data, such as jsonb

What we should use with latest versions of pgx?

Thanks

**Comment by jackc** [comment]
pgx v4 will only work with `github.com/jackc/pgtype`.
pgx v5 will only work with `github.com/jackc/pgx/v5/pgtype`.

The v5 version of pgtype has less types because many are no longer needed in the new architecture. In v4 the type struct was directly tied to encoding and decoding the underlying PostgreSQL type. For example, `pgtype.JSON` and `pgtype.JSONB` both existed even though there is no difference to the application because the binary encoding is slightly different for `jsonb`.

`[]byte` and `string` can directly be used for json and jsonb. No need to a pgtype wrapper.
