### ISSUE TITLE
best practice to insert arbitrary structs in an ORM way

### ISSUE THREAD

**Issue by ntswamp** [jackc/pgx#1402]
for example

```
type Account struct {
	Id        uint64
	Email      string
	Name     string
	CreatedAt     time.Time
}

bob:= &Account{Id:1, Email:bob@mail.com, Name:Bob, CreatedAt: time.Now()}
```

How can I insert bob like what ORMs do?
Currently I'm implementing it through reflections, iterating over each field of bob, retrieving the values, building a SQL sentence, querying it. 

```
func (p *pgxpool.Pool)Insert(model interface{}) error {
//iterate over every field of model to get the values
...
//build SQL
...
sql:= `something`
//query
p.Query(ctx, sql)
}
```
but I found this method clumsy and slow. any suggestions?

**Comment by jackc** [comment]
ORM functionality is explicitly out of scope for pgx. So there is no "pgx way" to do this. Personally, I tend to hand write my SQL or write my own mini-ORMs. I think that most people who need an actual ORM end up using the database/sql interface instead of the native pgx interface so they can use gorm, sqlx, etc.
