### ISSUE TITLE
Scanning from JSONB ignores sql.Scanner

### ISSUE THREAD

**Issue by dacohen** [jackc/pgx#1418]
**Describe the bug**
When scanning a JSONB column into a type that implements `sql.Scanner`, the `Scan()` function is never called, and the column is always scanned with `json.Unmarshal`.

**To Reproduce**

If possible, please provide runnable example such as:

```sql
CREATE TABLE test (
  data JSONB NOT NULL
);
INSERT INTO test (data) VALUES ('{"hello": "world"}');

```

```go
package main

import (
	"context"
	"database/sql/driver"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

type CustomType map[string]interface{}

func (c CustomType) Value() (driver.Value, error) {
	log.Println("Value called")
	return "", nil
}

func (c *CustomType) Scan(in interface{}) error {
	log.Println("Scan called")
	return nil
}

func main() {
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	var myData CustomType
	err = conn.QueryRow(ctx, "SELECT * FROM test LIMIT 1").Scan(&myData)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Expected behavior**
I would expect to see `Scan called` in the output, indicating that the custom Scan function was called.

**Actual behavior**
The output is empty. `myData` is populated with `json.Unmarshal` instead of the custom scanner.

**Version**
 - Go: `$ go version` -> go version go1.19.3 darwin/arm64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` ->  PostgreSQL 14.6 (Homebrew) on aarch64-apple-darwin22.1.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` ->  v5.2.0

**Additional context**
If a `TEXT` column is used rather than `JSONB`, this example behaves as expected.

In general, it appears that calling a custom scanner is only done as a last resort. Is this for speed reasons? It seems go used to be much slower to evaluate type assertions, but that's been rectified in the last few years.

**Comment by jackc** [comment]
That's a little tricky.

pgx will try *many* different approaches to find a way scan a value. e.g. The type could directly support a pgx interface, or the type could be unwrapped to something that can be handled (e.g. `type foo string`), or the type could be wrappable in a compatibility type, etc.

The first approach that is found will be used. This can cause ambiguity when a value could be scanned multiple ways. In the JSON case, one of the earlier things it tries is `json.Unmarshal()`. So it never gets to the `sql.Scanner` interface. It is the last or nearly last thing that is tried because otherwise a type could not support `database/sql` and `pgx` as the pgx interfaces would never be called. In addition, in general `sql.Scanner` works with the text format which is slower (doubly so if it was received in binary and pgx has to transcode it to text before passing it to `Scan`.

Ordinarily, `sql.Scanner` being last isn't a problem, but for the JSON type handler `json.Unmarshal` is always called first.

---

I've special-cased pgtype.JSONCodec to look for `sql.Scanner` before trying `json.Unmarshal` instead relying on the default `sql.Scanner` handling code. It's a little awkward, but I think it should work.
