### ISSUE TITLE
Prepare should bind param types

### ISSUE THREAD

**Issue by willtrking** [jackc/pgx#144]
PGX should bind the param types when preparing statements, not just executing them. There are edge cases where if this doesn't happen, postgres won't be able to figure out the proper types. Consider the following query

```UPDATE my_table AS t SET expiration=c.c_3 FROM(VALUES ($1,$2),($3,$4),($5,$6),($7,$8),($9,$10))  AS c(c_3,c_4) WHERE t.id=c.c_4 RETURNING *```

Attempting to prepare this statement returns ```ERROR: operator does not exist: bigint = text (SQLSTATE 42883)``` This is because Postgres can't figure out the types of the bound parameters, and assumes their all strings. When using the raw libpq C library included with postgres, this works as it properly binds the OIDs (in the 9.5.3 library this happens in ```PQsendPrepare```)

In the above, expiration is a ```timestamp without timezone``` and id is a ```biginteger```. The types of the values being bound are properly set in Go, but because the ```Prepare``` function isn't sending the params like it does in ```sendPreparedQuery```, it fails.

This would be incredibly useful for me, so I'm definitely willing to put the effort in to get it done if you'd like it included.

**Comment by jackc** [comment]
It really surprises me that this would work with libpq. I took a quick look at the source for `PQsendPrepare` and I didn't see anything that would auto-identify types. It only uses parameter OID's if provided by the client (https://github.com/postgres/postgres/blob/master/src/interfaces/libpq)/fe-exec.c#L1251).

I'm interested in this, but I'm curious how it could work.

**Comment by willtrking** [comment]
Ah you're right, and yes that is what I was doing. Well I think a good in between would be a "PrepareWithTypes" that would allow the client to provide the types if they are known.

**Comment by jackc** [comment]
Do you find it easier to pass in OIDs to prepare rather than just supply the appropriate cast in the SQL (e.g. `UPDATE my_table AS t SET expiration=c.c_3 FROM(VALUES ($1::timestamp,$2::bigint),($3::timestamp,$4::bigint),($5::timestamp,$6::bigint),($7::timestamp,$8::bigint),($9::timestamp,$10::bigint)) AS c(c_3,c_4) WHERE t.id=c.c_4 RETURNING *`

Assuming so, I'm open to a advanced variant of `Prepare`. I'd probably want to have the advanced options (initially just the OID list) be a struct so if necessary we could add additional options (such as choosing between binary or text protocol) later without changing the method signature.

**Comment by willtrking** [comment]
In terms of ease of use I think they end up both being around equal, and if your using something like sqIx  I think passing OIDs could be significantly simpler. Also, direct passing of OIDs could have performance benefits over casting in certain use cases I would imagine. 

The idea of passing in a struct makes sense. I can put some time into a simple ```PrepareAdvanced``` if that helps.

What are your thoughts on corresponding ```QueryAdvanced``` ```QueryRowAdvanced``` and ```ExecAdvanced```?

**Comment by jackc** [comment]
Based on my understanding of the wire protocol, I'm pretty sure that passing OIDs vs including casts in the SQL should have no performance difference. However, if it makes certain use cases easier, I think it is reasonable to add.

pgx already has a pretty big public interface, so I try to keep interface additions to a minimum. In the long term I'd be open to the `Advanced` variants of the `Query` and `Exec` methods, but I think I'd want to see how the `Prepare` variant panned out be adding them.

As far as the name `Advanced`, I thought the stdlib used `Ex` to denote extended versions of functions. But when I looked around I couldn't find any examples. So I guess I'd like to use a name that matches stdlib conventions assuming there is one.

**Comment by willtrking** [comment]
Sqlx takes the approach of appending ```x``` to the end of its functions, which makes sense to me. Haven't seen the ```Ex``` at the end, although that also makes sense IMO. Definitely agree ```Advanced``` isn't a good one to go with. Personally I would go with ```x``` as it also seems to fit in with the name of your library.

**Comment by jackc** [comment]
I merged in #146 and I added a few tweaks on top of it.

* It might be bike-shedding, but I prefer Ex to x as the suffix, so I renamed Preparex to PrepareEx.
* I refactored the duplicated code out of Prepare and PrepareEx.
* PrepareExOptions is now passed by pointer instead of value. This helped with DRYing Prepare and PrepareEx. It also avoids additional overhead if the PrepareExOptions gains additional fields.
* Added a test to the PrepareEx path
