### ISSUE TITLE
PGX statements can't handle float64

### ISSUE THREAD

**Issue by robert-zaremba** [jackc/pgx#150]
Version: PostgreSQL 9.4.6 on x86_64-suse-linux-gnu, compiled by gcc (SUSE Linux) 4.8.5, 64-bit
pgx version: master (8db0a774d7)

This is regression issue. When I updated pgx version from edfdaf15c67 to master, I can't insert float64 values any more. I have the following error:

> cannot encode float64 into oid 700

`github.com/lib/pq` driver works as well.

Code:
```go
package main

import (
	"database/sql"
	"github.com/jackc/pgx"
	_ "github.com/jackc/pgx/stdlib"
	_ "github.com/lib/pq"
	"log"
)

func main() {
	db, err := initPGX()
	// db, err := initPG()
	if err != nil {
		log.Fatalln(err)
	}
	if _, err = db.Exec("create table if not exists xx (id integer, val real)"); err != nil {
		log.Fatalln(err)
	}

	res, err := db.Exec("insert into xx (id,val) values ($1,$2)", 1, float64(1.1))
	log.Println(res, err)
}

func initPGX() (*pgx.Conn, error) {
	// sql.Open("pgx", "postgres://localhost:5432/agflow?sslmode=disable")
	return pgx.Connect(pgx.ConnConfig{Host: "localhost", Database: "agflow"})
}

func initPG() (*sql.DB, error) {
	return sql.Open("postgres", "dbname=agflow sslmode=disable")
}
```

**Comment by jackc** [comment]
The above code is trying to write a 64-bit float into a 32-bit float. That potentially will lose data. I'm pretty sure 73bd33b21562f483c420c5f8389bba8a46dacb1f is the culprit -- it restricts enforces matching float sizes on the Go and PostgreSQL sides.

However, given that PostgreSQL will silently round/convert data on insert/update to float or numeric fields, perhaps it would be better to conform to precedent rather than be stricter than everything else...

**Comment by robert-zaremba** [comment]
I see, so this is the project decision.
Fair enough.

**Comment by robert-zaremba** [comment]
Would be good to put this somewhere in README or docs.
