### ISSUE TITLE
pgxpool.New did not return connection error

### ISSUE THREAD

**Issue by cdestiawan** [jackc/pgx#1508]
Why pgx.New doesn't throw a connection error?
Here is the example
```go
db, err := pgxpool.New(context.Background(), os.Getenv("DATABASE_URL") // I don't provide DATABASE_URL in environment variable
if err != nil { // should have an error since we don't provide DATABASE_URL 
    fmt.Println("Hey, it's an error!") // not printed at all
    log.Fatal(err) // not exited
}
```

Expected result: Throw a connection error
Actual result: It doesn't throw anything

Version:
- Go 1.20
- PostgreSQL 15
- pgx 5.3.0

**Comment by jackc** [comment]
It did not not return an error because it successfully created a pool. However, it is an empty pool. It doesn't actually create a connection until it needs to. The reason for this logic is a server shouldn't crash / abort if the database server is temporarily unreachable. You can call `Ping` to see if the database can actually be reached.

With regard to not passing a connection string (or rather passing `""`). That is entirely acceptable as well. In fact, that is what I usually do myself. pgx supports the standard `PG*` environment variables such as `PGHOST`. With those a connection string is optional.

**Comment by cdestiawan** [comment]
I see. Thanks for the answer.
