### ISSUE TITLE
JSONB type changed from []byte to string

### ISSUE THREAD

**Issue by zanmato** [jackc/pgx#1522]
**Describe the bug**
The type received in Scan() (sql.Scanner) was `[]byte` for JSONB columns in 5.2.0, now it seems to be `string`.
I've bisected the issue to 279c3c0a20e0dbee3c4b644f58e5e3b3de8e051f

**To Reproduce**
```go
package main

import (
	"context"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"log"
	"os"

	pgx "github.com/jackc/pgx/v5"
)

type References map[string]string

func (m References) Value() (driver.Value, error) {
	return json.Marshal(m)
}

func (m *References) Scan(v interface{}) error {
	b, ok := v.([]byte)
	if !ok {
		return errors.New("type assertion to []byte failed")
	}

	return json.Unmarshal(b, &m)
}

func main() {
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, os.Args[1])
	if err != nil {
		log.Fatal(err)
	}

	if _, err := conn.Exec(
		ctx,
		"CREATE TABLE IF NOT EXISTS test_jsonb(id INT GENERATED BY DEFAULT AS IDENTITY, b jsonb)",
	); err != nil {
		log.Fatal(err)
	}

	var id int
	if err := conn.QueryRow(
		ctx,
		`INSERT INTO test_jsonb(b) VALUES('{"a": "b"}') RETURNING id`,
	).Scan(&id); err != nil {
		log.Fatal(err)
	}

	var b struct {
		ID int
		B  References
	}

	if err := conn.QueryRow(
		ctx,
		"SELECT id, b FROM test_jsonb WHERE id = $1",
		id,
	).Scan(&b.ID, &b.B); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%#v", b)
}
```

**Expected behavior**
The type should be `[]byte`

**Actual behavior**
The type is `string`, resulting in an error `can't scan into dest[1]: type assertion to []byte failed`

**Version**
 - Go: go version go1.20 linux/amd64
 - PostgreSQL: PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
 - pgx: v5.3.0

**Comment by jackc** [comment]
`[]byte` vs `string` is not actually this issue. Try throwing a panic in your `Scan` method. Prior to https://github.com/jackc/pgx/commit/279c3c0a20e0dbee3c4b644f58e5e3b3de8e051f the code still seems to work -- because the `Scan` method is never being called.

pgx will use `json.Unmarshal` automatically when scanning a json column. However, it was doing that even if `sql.Scanner` was implemented. https://github.com/jackc/pgx/commit/279c3c0a20e0dbee3c4b644f58e5e3b3de8e051f fixed this so a `sql.Scanner` is handled before falling back to the generic `json.Unmarshal`.

**Comment by zanmato** [comment]
Ah, I see. I never actually tested whether it was called or not prior to the change. Thanks!
