### ISSUE TITLE
NetipAddrScanner, NetipAddrValuer

### ISSUE THREAD

**Issue by gnuletik** [jackc/pgx#1526]
I'm migrating `pgx/v4` to `pgx/v5` (using `sqlc`).

In order to serialize IP addresses as JSON, I had the following type:
```go
import (
    "github.com/jackc/pgtype"
)

// Inet is a wrapper around pgtype.Inet that
// serialize to the string IP in JSON.
type Inet struct {
	pgtype.Inet
}

func (i Inet) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i Inet) String() string {
	return i.IPNet.IP.String()
}
```

However, `pgtype.Inet` has been removed in `pgx/v5` in favor of direct usage of `netip.Addr`.

I tried to migrate to
```go
type Inet struct {
	netip.Addr
}
```

However, queries fails with the following error
```
can't scan into dest[4]: cannot scan inet (OID 869) in binary format into *dbtype.Inet
```

**Describe the solution you'd like**

I'm kind of discovering the new Codec concept so I'm not sure what the best solution should be but it seems that `pgx/v5/pgtype` introduced [NetipPrefixScanner](https://pkg.go.dev/github.com/jackc/pgx/v5/pgtype#NetipPrefixScanner) and [NetipPrefixValuer](https://pkg.go.dev/github.com/jackc/pgx/v5/pgtype#NetipPrefixValuer) interfaces which seems to allow implementing custom Scanner/Valuer for custom types.

However, there is not equivalent for `netip.Addr`, so I guess they could be added.

**Describe alternatives you've considered**

It seems to be possible to implement a new type like https://github.com/vgarvardt/pgx-google-uuid/blob/master/uuid.go but it feels a bit heavy to wrap an existing type.

**Comment by jackc** [comment]
`netip.Prefix` contains a `netip.Addr`. That's why only [NetipPrefixScanner](https://pkg.go.dev/github.com/jackc/pgx/v5/pgtype#NetipPrefixScanner) and [NetipPrefixValuer](https://pkg.go.dev/github.com/jackc/pgx/v5/pgtype#NetipPrefixValuer) exist. It can handle both PostgreSQL `inet` and `cidr` and Go `netip.Prefix` and `netip.Addr`.  I think your best option is to implement them. It's what pgx does internally for its `netip.Addr` support.

See below: https://github.com/jackc/pgx/blob/6105ca50734a6588a6d159a4f0c6f1398a793e5c/pgtype/builtin_wrappers.go#L583-L607

It should be relatively straightforward to adapt the code for `netipAddrWrapper` to work with your struct.
