### ISSUE TITLE
`RowToStructByName` with nested structs

### ISSUE THREAD

**Issue by davidspiess** [jackc/pgx#1585]
I would like to scan a joined query in a nested struct with `RowToStructByName` 
Example:

```golang
type User struct {
	ID   int    `db:"id"`
	Address Address `db:"address"`
}

type Address struct {
	ID  int    `db:"id"`
	City string `db:"city"`
}
```
My query looks like the following:

```sql
SELECT
u.id,
a.id AS "address.id",
a.city AS "address.city"
FROM users AS u 
INNER JOIN addresses AS a ON u.address_id = a.id
```

Is it somehow possible to scan the address in the user struct?
I tried aliasing the address fields in the query with "dot" syntax but i does not seem to work. `RowToStructByName` gives me `cannot find field address in returned row`.

I found a sqlx example which already provides this exact behaviour, maybe it would be a nice addition for this library too.
https://gist.github.com/ara-ta3/36149583788cdbdae1f3c31a4561ce9f

**Comment by jackc** [comment]
pgx does not support using column names to map to nested structs in that particular way. What pgx does support is mapping row / composite types to nested structs. So you could instead use a query like:

```sql
SELECT
u.id,
row(a.id, a.city) AS address
FROM users AS u 
INNER JOIN addresses AS a ON u.address_id = a.id
```

This is slightly different in that the nested values are mapped by position instead of by name but that is usually not a problem in my experience.

In addition, `RowToStructByName` is simply a `RowToFunc`. It is possible for you to implement whatever scanning logic you want without changing the pgx library.

**Comment by davidspiess** [comment]
Thank you for your proposed solution and insights, i will try it out 😊
In the mean time i found https://github.com/georgysavva/scany, which is also mentioned in your readme. 
It solves this exact problem and has a pgx compatible interface.
