### ISSUE TITLE
Connection over SSH hung with DialFunc in pgx v5 (v4 works)

### ISSUE THREAD

**Issue by d-bytebase** [jackc/pgx#1600]
**Describe the bug**
I'm writing postgres connection over SSH with pgx v5, see code below.

1) The first "SELECT 1" returns, but "SELECT 2" hangs.
2) When I use conn from  db.Conn() instead of db to make the queries, everything works as expected.
3) If I switch to v4, everything works as expected.

**To Reproduce**
Sample code: https://go.dev/play/p/vdy7W739QAl

**Expected behavior**
See above

**Actual behavior**
See above

**Version**
 - Go: `$ go version` -> [go version go1.20.4 darwin/arm64]
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> [PostgreSQL 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit]
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> [v5.3.1]

**Additional context**

**Comment by d-bytebase** [comment]
We have switched to pgx/v4 to work around the problem at Bytebase. However, we are hoping v5 to work in the future.

**Comment by jackc** [comment]
Unfortunately, this is a rather messy issue. pgx v5 relies on non-blocking I/O. Go only exposes non-blocking I/O via syscalls. This is implemented on for unix and windows platforms, but a fallback mode that uses `SetWriteDeadline` is also provided. 

Obviously, we can't use OS level syscalls on the conn created by the SSH library so the fallback mode is enabled. But the SSH conn also doesn't actually implement the deadline functions so the fallback mode doesn't work either.

Presumably, the hang is occurring because it's reaching a part of the code that actually needs the deadline to work -- and the stubbed version in your example can't actually abort the read or write.

I'm not really sure what a solution would be here.

**Comment by d-bytebase** [comment]
Thanks! Is there a way to disable the non-blocking IO in v5?

**Comment by jackc** [comment]
Unfortunately, not in this case. Disabling non-blocking I/O was intended to be done with the `SetWriteDeadline` fallback. But that fallback doesn't work here either.

**Comment by brandur** [comment]
@jackc Hi Jack, I ended up running into a very similar problem as Bytebase here, and although _I think_ I've been able to resolve it using a modified version of the `net.Conn` deadline shunt here [1], it feels pretty gnarly to have had to use this sort of hammer. And if more issues do crop up, we'll probably have to resolve them by just downgrading to V4 again because we're not well set up to be diagnosing and troubleshooting this kind of low-level code.

Do you have any thoughts on what a "good" solution for this problem would look like? Like, is the basic issue that Go's SSH package should support deadlines? (I tried to find an existing issue for that, but couldn't, for whatever that's worth.) If that's unlikely to ever happen, should pgx have a variant mode more similar to v4 that doesn't rely on non-blocking I/O or deadlines?

Thanks.

[1] https://github.com/jackc/pgx/issues/525#issuecomment-1448265724

**Comment by jackc** [comment]
@d-bytebase @brandur Please try PR #1629. I think it should resolve the issue.

**Comment by d-bytebase** [comment]
Hi @jackc, I'm still hitting hanging issue on the latest v5.4.3.

**Comment by jackc** [comment]
@d-bytebase I don't know... The only place I am using actually using an SSH tunnel with pgx v5.4.3 is with [tern](https://github.com/jackc/tern) -- and it's working on there (on master anyway, not sure about the latest tagged release).

**Comment by d-bytebase** [comment]
I've tested pgx v5.5.0 works like a charm. Thanks @jackc for helping out. 

Upgrade towards Bytebase: https://github.com/bytebase/bytebase/pull/9731

**Comment by fgm** [comment]
FWIW, I just had the issue on 5.3.0, but it was fixed by the upgrade to 5.5.1.
