### ISSUE TITLE
DOCS. Misleading in QueryExecMode description type.

### ISSUE THREAD

**Issue by teror4uks** [jackc/pgx#1635]
https://pkg.go.dev/github.com/jackc/pgx/v5#QueryExecMode

Hello, I've found that the description for `QueryExecModeDescribeExec` is not entirely correct in my understanding, for example, it claims that `It does not use prepared statements`, but it does at least [to create PS with an unknown(empty) name](https://github.com/jackc/pgx/blob/master/conn.go#L834), which might raise an issue like a `prepared statement with unknown name does not exist` in PgBouncer if it works in `transaction` mode

Can we maybe re-phrase this somehow? For example:

`It creates prepared statements with empty name and does not store them in the local cache (allowing usage with most connection poolers, except PgBouncer in transaction mode)`

Or some other suggestions?

**Comment by jackc** [comment]
`QueryExecModeDescribeExec` uses the extended protocol. There is no way to use the extended protocol without issuing a `Parse` message to the server. (https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY)

The unnamed prepared statement is a special case on the server. In most cases, using the extended protocol without _named_ prepared statements would be considered as not using prepared statements. This is the case even with PgBouncer. PgBouncer can work perfectly well with the extended protocol and the unnamed prepared statement. The problem is specific to how `QueryExecModeDescribeExec` uses it. PgBouncer understands the PostgreSQL protocol enough to only switch the underlying connection when it sees a `Sync` message. However, in `QueryExecModeDescribeExec`, pgx needs to send a `Sync` to get the statement description back, then it sends the `Bind` (execute the query) message and another `Sync`. PgBouncer may switch the underlying connection in that instant between the two round trips to the server.

I've updated the docs to reflect that this mode may be incompatible with connection poolers. https://github.com/jackc/pgx/commit/490f70fc5f6544a8d19ee09d2abec311fca93478.
