### ISSUE TITLE
How can I get a accurate execution time

### ISSUE THREAD

**Issue by sasakiyori** [jackc/pgx#1696]
Postgres can get an execution time from `explain analyze`, for example:
```sql
postgres=# \timing
Timing is on.
postgres=# explain analyze select * from pg_sleep(5);
                                                 QUERY PLAN
-------------------------------------------------------------------------------------------------------------
 Function Scan on pg_sleep  (cost=0.00..0.01 rows=1 width=4) (actual time=5004.211..5004.212 rows=1 loops=1)
 Planning Time: 0.039 ms
 Execution Time: 5004.826 ms
(3 rows)

Time: 5012.983 ms (00:05.013)
```

I want to get an execution time which is close to the result above when executing a sql. 
And I do it like:
```go
// ...
start := time.Now()
rows, err := conn.Query(ctx, "select * from pg_sleep(5);")
execTime := time.Since(start).Milliseconds()
// scan the rows...
```

Is it accurate? I found the results are nearly same in many cases, but sometimes there have a big gap between them(The query plan is the same).

**Comment by jackc** [comment]
The server does not expose the actual server side execution time of a query to the client. `\timing` in `psql` is a client side measurement. You can see this by running a `select 1` on a local PostgreSQL server and on a remote server.

Using `time.Now()` is equivalent to what `\timing` is doing. However, you should take the finish time after the `rows` are closed. Otherwise, the timing may differ on large responses.

Also, if your intention is for logging or tracing you may want to look at the `pgx.QueryTracer` interface and the `tracelog` package.

**Comment by jackc** [comment]
Unfortunately, as far as I know what you want is impossible. The PostgreSQL protocol does not expose the server side execution time. And as you discovered `RowDescription` is not an indicator of execution time. It can be sent before the query is completed, but it could instead be delayed until the query was finished to minimize the number of network writes. And as also mentioned, network latency would also be a significant problem.

https://www.postgresql.org/docs/current/auto-explain.html may be helpful if you have access to the logs, though beware of the server overhead.

**Comment by sasakiyori** [comment]
Thanks for your detailed answer and advice!!
