### ISSUE TITLE
type pgx.ConnPoolConfig has no field or method AcquireTimeout

### ISSUE THREAD

**Issue by tommiv** [jackc/pgx#170]
Is this field deprecated?

I see it's mentioned in [docs](https://godoc.org/github.com/jackc/pgx#ConnPoolConfig) but go refuses to compile this:

```go
    var pgcfg pgx.ConnPoolConfig
    pgcfg.Host           = cfg.Connection.Host
    pgcfg.Port           = uint16(cfg.Connection.Port)
    pgcfg.Database       = cfg.Connection.Database
    pgcfg.User           = cfg.Connection.User
    pgcfg.Password       = cfg.Connection.Password
    pgcfg.MaxConnections = cfg.Pool.Max
    pgcfg.AcquireTimeout = time.Duration(cfg.Pool.Timeout) * time.Second

    pg, err := pgx.NewConnPool(pgcfg)
```

Version fixed by glide is 

```yaml
- package: github.com/jackc/pgx
  version: ^2.8.1
```

I can't find any entry of `AcquireTimeout` in pgx subfolder of vendor folder of my project, but I see this [test](https://github.com/jackc/pgx/blob/558d5550cf5c08e7192eb2eb8635f21f4b700ff5/conn_pool_test.go#L241) in a non-master branch.

**Comment by konstantin-dzreev** [comment]
It's been there for a while: https://github.com/jackc/pgx/blob/master/conn_pool.go#L13
Are you sure you are running an up-to-date version of pgx?

**Comment by tommiv** [comment]
Hmmm. I delegated versions management to the Glide. Actually, I used `github.com/jackc/pgx` instead of recommended `gopkg.in/jackc/pgx.v2`. But now I migrated project to the later option and I've got the same error. Glide fixed version as ^2.8.1. which means, I believe, "anything what is compatible with 2.8.1 regarding to semantic versioning". Which should resolve to 2.8.x or higher. Additionally, glide.lock contains entry

```yaml
- name: gopkg.in/jackc/pgx.v2
  version: 9edd770c70e274b7ef67fa9f4039c824be0f8bda
```

So I'm pretty sure it major version 2, but I don't know what exact version was fetched.

It doesn't make any sense for me, but I'm admit that it can be glide issue, not pgx. Is there any way to determine pgx version from its fetched source?

**Comment by tommiv** [comment]
UPD: Found changelog in source folder and now I'm pretty sure it's really 2.8.1 version:

```
# 2.8.1 (March 24, 2016)

## Features

* Scan accepts nil argument to ignore a column
```

**Comment by jackc** [comment]
I think this confusion is probably my fault. This feature was on the master branch but had not been merged into the v2 branch. Instead of merging new features into the stable ```v2``` branch immediately as I formerly did, I've been leaving them on master until I release a new stable version. This gives me the chance to back out of any ill-conceived changes without breaking semver. However, I had not issues a release in about 5 months so v2 did not have the feature you are trying to use. In addition, I hadn't updated the readme to reflect the change in versioning policy.

I've corrected the readme, and released pgx ```v2.9.0```. So update to pgx ```v2.9.0``` or head of ```v2``` branch and the problem should be resolved.

**Comment by jackc** [comment]
Oops. Sorry I forgot to `git push --tags`. It's there now.

**Comment by tommiv** [comment]
Thank you, it works now.
