### ISSUE TITLE
Return multiple result sets

### ISSUE THREAD

**Issue by denis-n** [jackc/pgx#171]
Hi,

[This article](https://blog.dsl-platform.com/multiple-result-sets-alternatives-in-postgres-3/) shows how to return multiple sets for one request.

How to make it work with pgx?

For example, for a select sql query with 2 columns `array_agg()` returns something like this:

> {"(var1,abc)","(var2,xyz)"}

var1, var2 is for 1st column,
abc, xyz is for 2nd column

**Comment by jackc** [comment]
It looks like the final example in the article you reference is returning arrays of records. That might be difficult.

There are several ways to approach this problem. 

First would be implementing the `Scanner` interface for each specific type of array of records. You could either parse the text format directly or try and deal with the binary format. pgx has support for decoding the binary array header and it has limited support for parsing a row record into a `[]interface{}`. See source for `decodeRecord` and `decode1dArrayHeader` for details. Note both those methods are private so you might need to copy and paste them into your own code. If you found a technique that worked we could work on making a public interface in pgx.

Second, you could use PostgreSQL to serialize the entire result set into JSON, then decode the JSON into your data structures in Go. pgx supports automatic deserialization into `struct` so the Go side could be as simple as scanning directly into your data structure. See https://hashrocket.com/blog/posts/faster-json-generation-with-postgresql and https://www.pgcasts.com/episodes/1/generating-json-from-sql/) for info on how to generate SQL in PostgreSQL.

Third, you could return a result set of `row` instead of array of records. Using `row` lets you return arbitrary shaped data from PG.

For example:

```sql
select 'user' as rectype, row(42, 'John', 'Smith')
union all
select 'order' as rectype, row(65, 'widgets', 43.23, '2016-10-01');
```

pgx will parse `row` into `[]interface{}` so you could switch on rectype and then extract the values from the `[]interface{}` into your data structures.

I think the second or third ideas are probably the easiest to implement.

But ultimately, I would suggest doing some benchmarks to be sure you really need to do this level of optimization. Presumably, all you are saving a round trip to PostgreSQL -- in many cases the query time would dwarf the round-trip time.

**Comment by denis-n** [comment]
Thank you for links)

I'm new to golang and PostgreSql. What is the best way to return the value from row() method?
Use Scan() with a string variable?

**Comment by jackc** [comment]
I'll reiterate my suggestion to start by doing it the simplest way to avoid [premature optimization](http://c2.com/cgi/wiki?PrematureOptimization).

But to answer your question, the following code should scan a row into a slice of empty interface `[]interface{}`.

```go
var row []interface{}
err := conn.QueryRow("select row(1, 'cat', '2015-01-01 08:12:42'::timestamptz)").Scan(&row)
if err != nil {
  return err
}

// row now contains 3 elements
```
