### ISSUE TITLE
does pgx support Dynamic SQL like mybatis?

### ISSUE THREAD

**Issue by necsk** [jackc/pgx#1713]
hay all
I searched a lot and have no clue.
i used NamedArg but have no idea how to control my sql more more flexible.

if not supported, will that be a feature in the future? or any reason that pgx will not support it?
also, except writing go code for specific scenario, any other idea/thirdpart libs would be appreciated.

thank you

**Comment by jackc** [comment]
pgx doesn't do anything like that and it is extremely unlikely it ever will. The reason is that pgx is a database driver, not an ORM or SQL builder. It makes sense for that functionality to exist in other projects.

I'm unfamiliar with mybatis, but after a quick investigation I think that [sqlc](https://sqlc.dev/) might be what you are looking for.

**Comment by necsk** [comment]
thank you Jackc!

**Comment by necsk** [comment]
sorry but add some supplement and here is my final solution:

mybatis has the following utils and it generates sql while in run-time.
https://mybatis.org/mybatis-3/dynamic-sql.html#:~:text=The%20most%20common%20thing%20to%20do%20in%20dynamic,null%22%3E%20AND%20title%20like%20%23%20%7Btitle%7D%20%3C%2Fif%3E%20%3C%2Fselect%3E


for example,
  <if test="title != null">
    AND title like #{title}
  </if>

then, i found a lib in go,

https://pkg.go.dev/text/template 
and i tried to impl my own ones.

for example,
{{if pipeline}} T1 {{else}} T0 {{end}}
	If the value of the pipeline is empty, T0 is executed;
	otherwise, T1 is executed. Dot is unaffected.

thank you Jackc again.
