### ISSUE TITLE
Turn off prepared statements for use with PGBouncer

### ISSUE THREAD

**Issue by dinosaurcop** [jackc/pgx#172]
I may be missing something, but I am running into the problem addressed here:

https://github.com/lib/pq/issues/389

Would be great to get advice on how to disable prepared statements if it is doable.

**Comment by jackc** [comment]
I'm not very familiar with pgbouncer or the internals of `lib/pq` so I'm probably missing something, but it looks like the `sendBinaryModeQuery` method in `lib/pq` prepares the unnamed statement and executes it. That is what Query/QueryRow/Exec do when provided with SQL text instead of a prepared statement name. So I would think that calling Query with SQL text would do what you want. Assuming you've tried that and it fails, can you give more details about the problem?

**Comment by dinosaurcop** [comment]
It does fail, and I'm not sure why exactly the `sendBinaryModeQuery` works for `lib/pq`. I think it has to do with the fact that it is skipping the `PrepareEx` step of retrieving descriptions.

@johto any chance you could shed some light on how the `sendBinaryModeQuery` short-circuits PgBouncer's restriction on `PREPARE` statements?

**Comment by johto** [comment]
The trick is not to Sync before you're completely done with the unnamed statement.  `pq` uses the "binary mode" option to change the semantics a bit in order to provide a mode where a query only does a single round trip, i.e. it doesn't need to know the types inferred for the parameters before sending the parameters over.  I *think* it would be possible to do this even with two round trips using a Flush instead of a Sync in case you need to know the inferred types, but I haven't tried it.

Sorry I can't give a more specific answer than that -- I don't know anything about `pgx` and I don't have the time to get into this right now.

**Comment by dinosaurcop** [comment]
Ok, that's very helpful and definitely doable in `pgx`. Thanks for the help!

I'll test the Flush idea as it would good to know if that works, but fortunately there is no need in our application to fetch the types before sending the parameters.

**Comment by jackc** [comment]
That could be interesting even outside of the pgbouncer use case. It could let regular non-prepared queries run with 1 round trip instead of 2. Might be worth adding a QueryEx like there is a PrepareEx that takes the extra parameters.

**Comment by dinosaurcop** [comment]
Seems to be working perfectly :)  This is not an area I am very familiar with, and I haven't found good documentation on the client->server protocol (any good resource links?) so my efforts are very guess and check. What I've done is add `PrepareEx` returns in the `rowDescription` and `noData` cases:

`// flush (replaces sync)
	wbuf.startMsg('H')
	wbuf.closeMsg()

	_, err = c.conn.Write(wbuf.buf)
	if err != nil {
		c.die(err)
		return nil, err
	}

	ps = &PreparedStatement{Name: name, SQL: sql}

	var softErr error

	for {
		var t byte
		var r *msgReader
		t, r, err := c.rxMsg()
		if err != nil {
			return nil, err
		}

		switch t {
		case parseComplete:
		case parameterDescription:
			ps.ParameterOids = c.rxParameterDescription(r)

			if len(ps.ParameterOids) > 65535 && softErr == nil {
				softErr = fmt.Errorf("PostgreSQL supports maximum of 65535 parameters, received %d", len(ps.ParameterOids))
			}
		case rowDescription:
			ps.FieldDescriptions = c.rxRowDescription(r)
			for i := range ps.FieldDescriptions {
				t, _ := c.PgTypes[ps.FieldDescriptions[i].DataType]
				ps.FieldDescriptions[i].DataTypeName = t.Name
				ps.FieldDescriptions[i].FormatCode = t.DefaultFormat
			}
			return ps, nil
		case noData:
			return ps, nil
		case readyForQuery:
			c.rxReadyForQuery(r)

			if softErr == nil {
				c.preparedStatements[name] = ps
			}

			return ps, softErr
		case closeComplete:
			return ps, nil
		default:
			if e := c.processContextFreeMsg(t, r); e != nil && softErr == nil {
				softErr = e
			}
		}
	}`

**Comment by ezotrank** [comment]
So, any news about pgx and pgbouncer?

**Comment by jackc** [comment]
In the development `v3` branch there is a `SimpleProtocol` flag that you can pass to `QueryEx` and `ExecEx`. This flag disables automatic prepared statements. I don't have a pgbouncer instance handy to test it with, but if all that is needed is to avoid prepared statements then it should be possible.

**Comment by jackc** [comment]
`v3` has now been released including the `SimpleProtocol` flag to avoid prepared statements.
