### ISSUE TITLE
keep alive a connection waiting for a notifications

### ISSUE THREAD

**Issue by parihaaraka** [jackc/pgx#1831]
As far as I can see the `WaitForNotification()` method locks the connection and makes it unavailable to perform queries (the protocol does not impose such restrictions). How is loss of connection (without FIN packet) supposed to be detected?

**Comment by jackc** [comment]
`pgx.Conn` buffers notifications received while performing queries. You can use a connection to make queries then call `WaitForNotification()` with a context with a short timeout to process any notifications that were received.

As far as detecting a lost connection, `WaitForNotification()` blocks on a network read. If the problem can be detected by a read it will return an error. Otherwise, if the connection loss can only be detected by a network write then to loop around ``WaitForNotification()` with a short timeout and `Ping()`.

**Comment by jackc** [comment]
Potentially, you could also use a custom dialer on connect to set some TCP level keepalive settings.

**Comment by parihaaraka** [comment]
thanks for the tips 🤝🏼

**Comment by technillogue** [comment]
it would be great if there was a way to listen indefinitely on a connection while also doing Ping() in a loop. the short timeout could be less effective. for example, here's this asyncpg [example](https://github.com/MagicStack/asyncpg/issues/519#issuecomment-571828667), or the way asyncpg_listen does it: https://github.com/anna-money/asyncpg-listen/blob/master/asyncpg_listen/listener.py#L134-L144.

I guess users could implement this themselves by using pgConn.receiveMessage directly, or you could add WaitForNotificationWithoutLocking
