### ISSUE TITLE
[]Tags and implementation of Scaner\Encoder

### ISSUE THREAD

**Issue by gebv** [jackc/pgx#187]
How to implement a Scanner\Encoder for custom type?

```
type Tag string

type Tags []Tag

func (t *Tags) Scan(vr *pgx.ValueReader) error {
	log.Println(vr.ReadString(vr.Len())) // expected '{a,b,c}'
	return nil
}

func (t Tags) Encode(w *pgx.WriteBuf, oid pgx.Oid) error {
	w.WriteInt32(int32(len("{a, b}")))
	w.WriteBytes([]byte("{a, b}"))

	return nil
}

func (l Tags) FormatCode() int16 { return pgx.BinaryFormatCode }
```

```
var tags = Tags{}
err := db.QueryRow("select '{a,b,c}'").Scan(&tags)
assert.NoError(t, err)
```

Get the error `can't scan into dest[0]: Scan cannot decode into *Tags`
Not correctly implemented the interface Scaner\Encoder?

**Comment by gebv** [comment]
The problems begin with
```
type Tag string

type Tags []Tag

func (t *Tags) Scan(value interface{}) error {
	log.Println(value)

	return nil
}

func (t Tags) Value() (driver.Value, error) {

	return "{a, b}", nil
}

```

`ERROR: number of array dimensions (2069965856) exceeds the maximum allowed (6) (SQLSTATE 54000)`

what was my mistake?

**Comment by jackc** [comment]
`text[]` and `varchar[]` are already handled natively by pgx. So the default configuration is for `text[]` and `varchar[]` to be transported in the binary format. So when your `Encode` function sends a string, PostgreSQL is trying to read it as the binary array header. That's what I think that array dimensions error means.

There are a few possible solutions.

1. Use []string instead of Tags
2. Disable binary encoding in `DefaultTypeFormats` or an a per prepared statement level so your text encoding can work.
3. Implement your encoder and decoder functions in terms of pgx.Encode and pgx.Decode. Those can handle `[]string`. You would need to convert `Tags` to a `[]string` in your encode and the reverse in your decode. Unfortunately, you can't just to cast to Tags to []string in Go. You would have to loop through and copy to a new array on the way in or out (or do something clever with the `unsafe` package).

**Comment by gebv** [comment]
I get it, thanks jackc
The quickest and the easiest way to end - used `[]string`

**Comment by bodokaiser** [comment]
@jackc I want to implement the third approach you listed, however, I believe it might not be valid anymore as code has changed a lot in 3 years.

```go
// Tags represents a collection of tags.
type Tags []string

// Scan implements sql/driver Scanner interface.
func (t *Tags) Scan(src interface{}) (err error) {
	var ta pgtype.TextArray

	fmt.Printf("scan: %v\n", src)

	err = ta.Scan(src)
	if err != nil {
		return
	}
	err = ta.AssignTo(t)

	return
}

// Value implements sql/driver Scanner interface.
func (t Tags) Value() (driver.Value, error) {
	var ta pgtype.TextArray

	err := ta.Set(t)
	if err != nil {
		return nil, err
	}

	return ta.Value()
}
```

```go
sql := "UNNEST(tags) AS tag, COUNT(*) FROM feed_sources GROUP BY tag"

rows, err := conn.Query(sql)
if err != nil {
    log.Fatalf("failed to execute query: %v\n", err)
}
defer rows.Close()

for rows.Next() {
    var t Tags
    var c int

    err = rows.Scan(t, &c)
    if err != nil {
        log.Fatalff("failed to scan row in tags: %s\n", err)
    }

    tags = append(tags, t...)
}
err = rows.Err()
if err != nil {
    log.Fatalf("failed to iterate rows in tags: %s\n", err)
}
```

This will fail with
> can't scan into dest[0]: invalid array, expected '{': <nil>"}
which I believe is defined [here](https://github.com/jackc/pgx/blob/master/pgtype/text_array.go#L89).

Nevertheless, scanning into structs with property of type `Tags` seems to work.

**Comment by jackc** [comment]
I noticed that you have a Printf in your Scan function. Is that getting called?

Another thing to check is whether you are using database/sql or pgx native. Your Tags struct is designed for database/sql. But it isn't clear in your user code which is being used.

Ultimately though, the error message makes me think that the binary format is being used, but it is trying to decode it as text. Not clear why though.

**Comment by bodokaiser** [comment]
Thank you Jack! You are correct when just implementing the `database/sql` interface everything works as expected.

In case anyone checks this issue in the feature I created this minimal example:
https://gist.github.com/bodokaiser/1287d9183c8c6a5ac0f0134a0eaf88c2
