### ISSUE TITLE
support request: review initial PostGIS/GEOS integration

### ISSUE THREAD

**Issue by twpayne** [jackc/pgx#1892]
The goal of this issue is provide high-quality PostGIS <-> GEOS bindings to jackc/pgx via go-geos. I've written some code that seems to work well, but I would like to verify that it conforms to how jackc/pgx code should be written.

Firstly, thank you for this amazing library! jackc/pgx is so much better than database/sql. I've been using jackc/gpx with PostGIS for a while with a few private hacks, but I'd like to contribute better support for everybody.

## Background terminology

[PostGIS](https://postgis.net/) adds native support for geometry (and geographical) types for mapping applications to PostgreSQL. It's awesome.

[GEOS](https://libgeos.org/) is the standard library (written in C/C++) for geometry operations (think math like computing the intersection of two polygons) and underpins PostGIS.

[WKB](https://libgeos.org/specifications/wkb/) is the binary format used to transfer geometries between PostGIS and Go.

GEOS has functions for converting to/from `[]byte` and geometries.

[go-geos](https://github.com/twpayne/go-geos) is the [official set of Go/GEOS bindings](https://libgeos.org/usage/bindings/). I'm the author of go-geos. go-geos uses cgo but this should not be an issue.

## Action requested

[pgx-geos](https://github.com/twpayne/pgx-geos) contains an [implementation of `github.com/jackc/pgx/v5/pgtype.Codec`](https://github.com/twpayne/pgx-geos/blob/fd837cd411013a744f16398d99e649fa7512772e/pgxgeos.go) and is currently ~130 lines of code.

Would you be able to scan this code and indicate if anything is obviously very wrong?

Note that [using `conn.LoadType` causes errors](https://github.com/twpayne/pgx-geos/blob/fd837cd411013a744f16398d99e649fa7512772e/pgxgeos.go#L107-L108).

## Next steps for me

If the code is roughly correct, then I plan to make the following improvements:
* Add support for PostgreSQL's text protocol (currently the code is binary protocol only).
* Improve error values, replacing `errors.ErrUnsupported` with a richer error message.
* Add [dockerized tests](https://github.com/twpayne/go-geos/tree/master/examples/postgis) to remove the dependency on the PostGIS extension being available.

Many thanks!

**Comment by jackc** [comment]
I took a quick look and don't see any issues.

The only thing I noticed was the comment about why `conn.LoadType` can't be used. It's not really because of array support or lack thereof. It's because it is only intended for derived types such as arrays or composites. The pgx documentation wasn't clear about this. I have updated it in fd4411453fbd592586601b71f05eb06ea1c74906.

**Comment by twpayne** [comment]
Brilliant, thank you very much for the review and your time!

**Comment by ImDoubD-datazip** [comment]
Hi @twpayne @jackc 

I’ve been using the pgx driver with Go for quite some time now, primarily relying on rows.ColumnTypes() and DatabaseTypeName() to inspect schema metadata. Recently, I encountered an issue while working with a Postgres table that includes a geometry column, enabled via the PostGIS extension.

When calling ColumnTypes() on this table, the geometry column returns a database type OID like 1325320, rather than a descriptive type name like geometry or POINT. Additionally, when querying this table with a SELECT *, the geometry column returns a hex-encoded value instead of a human-readable format (e.g., POINT(x y)), which is what Postgres shows when queried directly.

I am using sqlx with: 
`err := p.client.Select(&columnSchemaOutput, getTableSchemaTmpl, schemaName, streamName)` to get schema details
and in the same geometry column is reported as type `USER-DEFINED`, which doesn't help with inferring the actual data type or formatting the value.

Basically I want the data as it is showing in postgres.

How can I solve this?

<img width="597" height="377" alt="Image" src="https://github.com/user-attachments/assets/e45d8ace-e663-4edf-97bb-e556a4b3fbd5" />


```
func MapScan(rows *sql.Rows, dest map[string]any, converter func(value interface{}, columnType string) (interface{}, error)) error {
	columns, err := rows.Columns()
	if err != nil {
		return err
	}

	types, err := rows.ColumnTypes()
	if err != nil {
		return err
	}

	scanValues := make([]any, len(columns))
	for i := range scanValues {
		scanValues[i] = new(any) // Allocate pointers for scanning
	}

	if err := rows.Scan(scanValues...); err != nil {
		return err
	}

	for i, col := range columns {
		rawData := *(scanValues[i].(*any)) // Dereference pointer before storing
		if converter != nil {
			datatype := types[i].DatabaseTypeName()
			precision, scale, hasPrecisionScale := types[i].DecimalSize()
			if datatype == "NUMBER" && hasPrecisionScale && scale == 0 {
				datatype = utils.Ternary(precision > 9, "int64", "int32").(string)
			}
			conv, err := converter(rawData, datatype)
			if err != nil && err != typeutils.ErrNullValue {
				return err
			}
			dest[col] = conv
		} else {
			dest[col] = rawData
		}
	}

	return nil
}
```


<img width="1406" height="626" alt="Image" src="https://github.com/user-attachments/assets/a46d2610-ef92-4706-9b81-58216b27c555" />


```
func (p *Postgres) ProduceSchema(ctx context.Context, streamName string) (*types.Stream, error) {
	populateStream := func(streamName string) (*types.Stream, error) {
		streamParts := strings.Split(streamName, ".")
		schemaName, streamName := streamParts[0], streamParts[1]
		stream := types.NewStream(streamName, schemaName)
		var columnSchemaOutput []ColumnDetails
		err := p.client.Select(&columnSchemaOutput, getTableSchemaTmpl, schemaName, streamName)
		if err != nil {
			return stream, fmt.Errorf("failed to retrieve column details for table %s: %s", streamName, err)
		}

		if len(columnSchemaOutput) == 0 {
			logger.Warnf("no columns found in table [%s.%s]", schemaName, streamName)
			return stream, nil
		}

		var primaryKeyOutput []ColumnDetails
		err = p.client.Select(&primaryKeyOutput, getTablePrimaryKey, schemaName, streamName)
		if err != nil {
			return stream, fmt.Errorf("failed to retrieve primary key columns for table %s: %s", streamName, err)
		}

		for _, column := range columnSchemaOutput {
			if strings.EqualFold("no", *column.IsNullable) {
				stream.WithCursorField(column.Name)
			}
			datatype := types.Unknown
			if val, found := pgTypeToDataTypes[*column.DataType]; found {
				datatype = val
			} else {
				logger.Debugf("failed to get respective type in datatypes for column: %s[%s]", column.Name, *column.DataType)
				datatype = types.String
			}

			stream.UpsertField(typeutils.Reformat(column.Name), datatype, strings.EqualFold("yes", *column.IsNullable))
		}

		// add primary keys for stream
		for _, column := range primaryKeyOutput {
			stream.WithPrimaryKey(column.Name)
		}

		return stream, nil
	}

	stream, err := populateStream(streamName)
	if err != nil && ctx.Err() == nil {
		return nil, err
	}
	return stream, nil
}
```

**Comment by twpayne** [comment]
See github.com/twpayne/pgx-geom and github.com/twpayne/pgx-geos.

**Comment by ImDoubD-datazip** [comment]
> See github.com/twpayne/pgx-geom and github.com/twpayne/pgx-geos.

I know I can use this library for geometry-based datatype, but what I need is to identify whether the user-defined datatype which I am getting in OID format is basically geometry. Then only I can use this library. I am not able to figure out how can I get to know that this OID belongs to geometry based datatype or any other user defined datatype.

**Comment by twpayne** [comment]
The libraries already do this for you, for example:

https://github.com/twpayne/pgx-geos/blob/18fcfe761cfe7301daeaf4aae2f0336203d0e1e9/geom.go#L181-L210
