### ISSUE TITLE
Convert interval to time.Duration (with stdlib API)

### ISSUE THREAD

**Issue by Tachi107** [jackc/pgx#1916]
**Is your feature request related to a problem? Please describe.**

This issue is really similar to <https://github.com/jackc/pgx/issues/748>, with the only difference that I'd like to be able to do the opposite: retrieving an `interval` from my PostgreSQL database and storing it into a `time.Duration` type, all while using the `stdlib` api.

**Describe the solution you'd like**

In a manner similar to <https://github.com/jackc/pgx/pull/1041>, I'd like the conversion to just work. The SQL standard (but not Postgres) requires durations to be either negative or positive, which maps well to Go's `time.Duration` type, which is simply a signed integer - refusing to convert mixed interval types seems like an acceptable restriction in the `stdlib` API to me.

It is possible to convert an `interval` to its number of microseconds with something like the following:

```sql
SELECT (EXTRACT(epoch FROM '1 minute 5 seconds 2 milliseconds 3 microseconds'::interval) * 1000000)::bigint;
```

which returns `65002003` microseconds. This number can then be passed over to Go, multiplied by `1000` (to convert it to nanoseconds), and assigned to a `time.Duration`.

**Describe alternatives you've considered**

Using `pgtype.Interval`, but I'd prefer using the `stdlib` API only.

Thanks!

**Comment by jackc** [comment]
Unfortunately, as far as I know, this is not possible to implement in pgx.

The problem is it never gets to pgx. `database/sql` doesn't know what a `time.Duration` is so it uses reflection to determine the underlying type is `int64`. It then tries to parse the raw value returned by PostgreSQL / pgx as an integer. Obviously, that fails. See `convertAssignRows()` in `database/sql/convert.go`.

I don't think this is possible unless `time.Duration` implemented `sql.Scanner` or `database/sql` added `time.Duration` to it's list of natively supported types. Or if `database/sql` added hooks for a driver or application to handle arbitrary types that do not implement `database/sql.Scanner`.

Alternately, you might be able to use `pgtype.Map.SQLScanner` in your `Scan` call. However, that will not work if you are using a library like gorm or sqlx where you may not directly control the `Scan` call.

**Comment by Tachi107** [comment]
Hi Jack, thanks for the reply! I'll ask the Go team if it's possible to extend `sql.Scanner` to also support `interval`, thanks for the explanation. I'll come here if there are some news :)
