### ISSUE TITLE
PGX 5.5.4 incompatible with pglogrepl

### ISSUE THREAD

**Issue by jacobmikesell** [jackc/pgx#1930]
**Describe the bug**
The recent changes to pgproto3 break the function signature expected in pglogrepl

**Comment by jackc** [comment]
The backwards compatibility break in the function signature was unfortunate, but the alternative was a panic (or not fixing a security issue), and I figured it was better force downstream users to update rather than introduce a panic. I updated pglogrepl in [828fbfe908e97cfeb409a17e4ec339dede1f1a17](https://github.com/jackc/pglogrepl/commit/828fbfe908e97cfeb409a17e4ec339dede1f1a17).
