### ISSUE TITLE
Add Support for protobuf timestamp.Timestamp 

### ISSUE THREAD

**Issue by kbsec** [jackc/pgx#1933]
**Is your feature request related to a problem? Please describe.**
Most protobuf types work out of the box with   pgx.CollectOneRow for scanning to a struct. Timestamp (https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto) does not. Seems  like  the fix is adding another case   here https://github.com/jackc/pgx/blob/master/pgtype/timestamptz.go#L60  with the relevant code being
```go

...
import (
...
"github.com/golang/protobuf/ptypes/timestamp"
)

case timestamp.Timestamp:
    *tstz = Timestamptz{Time: src.AsTime(), Valid:true}
```

**Describe the solution you'd like**
I would love for timestamp.Timestamp to be a valid type for RowToStruct

**Comment by jackc** [comment]
Unfortunately, this would add a dependency to pgx and I try to avoid that if at all possible.

However, pgx has an extensible type system, so that type can be supported without changing pgx itself. See https://github.com/vgarvardt/pgx-google-uuid for an example of how a third party UUID library was supported.

**Comment by kbsec** [comment]
Perfect, thank you!
