### ISSUE TITLE
unsupported jsonb version number

### ISSUE THREAD

**Issue by elvizlai** [jackc/pgx#200]
My previous code works. But it not now.
```
ERROR: unsupported jsonb version number 123 (SQLSTATE XX000)
```

```
extra,_ := json.Marshal(p)
db.PGX.Exec(`INSERT INTO pushes(publisher_id,  extra) VALUES ($1, $2);`, req.PublisherId,  extra)
```

And I now also tried `INSERT INTO pushes(publisher_id, extra) VALUES ($1, $2::JSONB);` but still not work.

Update 12:26
using `INSERT INTO pushes(publisher_id, extra) VALUES ($1, $2::JSON);` works. But it is not as my code expected. Am I miss something?

Update 12:44
using latest release the previous code works.

**Comment by elvizlai** [comment]
@jackc  The previous code does not work now. Maybe a change log need be declared for this update.

**Comment by ronaldslc** [comment]
Hi, we're running into a similar, maybe related, but different problem, where we're trying to read a JSONB field into a []byte before doing unmarshal ourselves.

We're getting errors along the lines of "invalid character '\x01' looking for beginning of value" in the json decoder and noticed that the byte array contains an extra \x01 byte at the start.

Pardon my lack of understanding, is this a specific problem to pgx or is it that PostgreSQL has always has this type of formatting for jsonb?

My other developers running slightly older versions of pgx, PostgreSQL server and go are not seeing this error (their code runs fine on their machine) so we're trying to establish where and when this change occurred.

Thanks.

**Comment by jackc** [comment]
It's the particular combination of PostgreSQL, pgx, and []byte. PostgreSQL has two formats for transferring data, binary and text. pgx has to tell the server what format to send values back in when the query is sent. pgx uses the binary format by default for jsonb. In text format, jsonb is simply the JSON text. In binary format, the first byte is a version number. At the moment, the is only jsonb version is `1`, so that is the '0x01' you are seeing.  

This is fine when using pgx decodes the JSON automatically. However, when scanning into a `[]byte` pgx bypasses any decoding and reads the raw bytes from the server. 

You can override the default format and use the text format with the following code:

`pgx.DefaultTypeFormats["jsonb"] = pgx.TextFormatCode`

However, certain features such as `CopyTo` will only work with the binary format. Another less convenient option is to use prepared statements and manually adjust the format for the jsonb column there.

Other alternatives would be to cast the jsonb to text in your query or to let pgx parse the jsonb value.

**Comment by justinclift** [comment]
@ronaldslc Seems to be reported (in a separate issue) here: #269

**Comment by ashb** [comment]
(sorry to resurrect an old issue) This seems to be a breaking change against the stated policy of using Semver -- code that worked from 2.9.0 doesn't work in 2.10.0

I'm not asking for history to be changed, but a clearr notice of this fact in the changelog would be nice.

**Comment by jackc** [comment]
Sorry about that. I'm not sure exactly what I was thinking at the time regarding whether it should be considered a breaking change or not. But it is noted in the release notes for 2.10.0: https://github.com/jackc/pgx/blob/master/CHANGELOG.md#compatibility
