### ISSUE TITLE
Cannot use arguments with some statements?

### ISSUE THREAD

**Issue by m3-mwilliamson** [jackc/pgx#202]
Noticed I am not able to pass arguments to some types of sql statements such as:

`_, err = conn.Exec("create database $1", "testdb")`
`_, err = conn.Exec("drop database $1", "testdb")`

These produce ERROR: syntax error at or near "$1" (SQLSTATE 42601)

However something like this works as expected:

`_, err = conn.Exec("create database testdb")`
`_, err = conn.Exec("drop database testdb")`

Am I doing something wrong?  Or is this expected behaviour?

Thanks!

**Comment by jackc** [comment]
That is expected behaviour. That substitution syntax is only usable for queries that will be executed as prepared statements. So basically just `select`, `insert`, `update`, `delete`, or `values`. In addition, substitution is only usable for values not identifiers.

If you need to create databases with user supplied identifiers you can escape them with this function:

```go
func quoteIdentifier(s string) string {
	return `"` + strings.Replace(s, `"`, `""`, -1) + `"`
}
```

**Comment by m3-mwilliamson** [comment]
Thanks for the clarification, much appreciated :)
