### ISSUE TITLE
Context support ?

### ISSUE THREAD

**Issue by howesteve** [jackc/pgx#218]
Hello,

Are there any plans to support [go 1.7+ contexts](https://golang.org/pkg/context/)? I understand that would be a API breaking change, but language has gone that way and everybody is following as well. Even the standard library's [sql package](https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit) will be adopting it in go 1.8. 
It's specially interesting when you have a context coming a web request and want to follow it in the database request as well.

Thanks,
Howe

**Comment by jackc** [comment]
At the very least I plan to support it for the `database/sql` driver.

It's on my wish list for the native pgx interface, but it vastly expands the API and/or is a breaking change. I haven't looked closely enough at it yet to know what will be involved.

If it ends up being a breaking change, then I'd like to take the opportunity to fix/tweak some other interfaces that have proved sub-optimal in hindsight (I've been experimenting a bit on those on the `v3-experimental` branch).

So I guess the short answer is, yes, it's in my plans, but I haven't done any coding on it yet.

**Comment by howesteve** [comment]
Thanks, I guess splitting it on v3 branch is the ideal thing to do.

Eagerly wating for this :)

**Comment by j7b** [comment]
I'd suggest (as I have elsewhere) database/sql's use of context (which is itself a bad design that conflates the notions of cancellation and deadlines and complicates error handling) is a bad design for a bad idea. A friendly method or two that sets statement_timeout on a connection would satisfy every reasonable use case, but notion of a client performing asynchronous statement cancellation is dangerous and naive in many more ways than it's useful.

**Comment by jackc** [comment]
@j7b Mind expounding on that a little more (or linking to your previous discussion)? Context may be a little complex to use at times (and implementing correctly in the driver was very tricky) but it does provide a few features that might be difficult to represent in another way.

A few examples I have in mind:

* Arbitrary cancellation control with ConnPool in a single call instead of needing to checkout out a Conn, set deadline, then query.
*  Potential to pass a request ID with the context where pgx would include that in log statements.
* Arbitrary async cancellation is needed for a feature like Ctrl+C in `psql`.

I've basically got the entire core of pgx async cancel safe in `v3` (and it was quite an undertaking), but I haven't settled on an API yet -- aside from supporting whatever database/sql does.

**Comment by howesteve** [comment]
I agree with @jackc. A context is a more standardized way to deal with cancellations and timeouts across API boundaries. That's the deal with contexts; I don't see why they are a bad design. Anyway, contexts are stdlib now, and all major APIs are supporting it.

**Comment by j7b** [comment]
https://github.com/golang/go/issues/18168 is some rage against the machine in which a deficient design is acceptable for inclusion in a "standard" library if it's documented. 

The context package conflates the notions of deadlines and cancellation into one type, which is terrible, and assumes nasty, brutish and short termination is always possible or at least reasonable. It ain't. 

In general, arbitrary cancellation and deadlines aren't applicable to implementations of application-layer protocols without violating the contract of the context package, the error type, or the protocol. Implementations that hide that fact would need to be extremely abstract or deficient or both.

To quote a bit from volume 5 of the PostgreSQL (9.0) Official Documentation, "Issuing a cancel simply improves the odds that the current query will finish soon, and improves the odds that it will fail with an error message instead of succeeding."

The context package doesn't support notions of cancellation failure or ambiguity, therefore database/sql doesn't. The mindset behind the design pretends resources were released even if they weren't, and I suspect database/sql isn't the only place in the standard library where cancel() doesn't (or hasn't).

I'd also point out the only thing asynchronous about control-c in psql is the signal handler, it's otherwise an extremely synchronous new conn and pqcancel as anybody who's said "control c didn't work and it's not doing anything, help!" would agree with.

In general statement_timeout is an effective way to manage deadlines in the scope of concern of a database transaction, the mechanism is in-band in terms of the session and the scope of errors are appropriate to the protocol and implementation and it should give a pretty clear indication to whomever's responsible for database administration somebody thinks something takes too long. Statement cancellation's much easier to use incorrectly (even pathologically) than correctly and should usually be approached as a desperate last resort to the point I'd avoid implementing it.

**Comment by jackc** [comment]
Interesting. I think there's a few issues involved.

First, is database/sql allowing use of context functions even when the underlying driver doesn't support it. That definitely can lead to confusion. Fortunately, any context enabled functions that pgx exposes would have the support baked in all the way through the driver.

As far as using `statement_timeout`, in many cases I agree that server side `statement_timeout` is better. But it doesn't cover all use cases. One reason for client-side timeouts is to handle network interruptions. If the client sends a query but never receives a response it shouldn't just hang forever.

The fundamental ambiguity of whether a query or a cancellation succeeded or not is unsolvable (https://en.wikipedia.org/wiki/Two_Generals%27_Problem) in a generic sense. Anytime a client-side cancellation or deadline occurs it is possible that the server succeeded but the response was lost or not received in time. I think this needs to be well documented on any context functions.

> I'd also point out the only thing asynchronous about control-c in psql is the signal handler, it's otherwise an extremely synchronous new conn and pqcancel as anybody who's said "control c didn't work and it's not doing anything, help!" would agree with.

I don't think that's the case at least on a recent psql. I canceled some queries in one session and looked at `pg_stat_activity` in another and the psql with the canceled queries always used the same connection.

> Statement cancellation's much easier to use incorrectly (even pathologically) than correctly and should usually be approached as a desperate last resort to the point I'd avoid implementing it.

The core functionality is already implemented in the `v3` branch. I want to support everything I can for database/sql. For the native pgx interface there is more flexibility, but I'm very reluctant not to support the standard/blessed solution deadlines and cancellations even if it does have deficiencies.

**Comment by j7b** [comment]
The Context interface actually doesn't bother me much, other than Value() that's another intentional deficiency+documentation.  I'd suggest copying the interface, never returning ctx.Err() if a backend connection was successfully opened (if whoever gave it to you cares what Err() is they still have it), honoring Deadline() ok==true by futzing with statement_timeout, issuing the cancel on Done() closed but not guaranteeing it will do anything, and so documenting pgx's version of the Context interface.

If that's an acceptable approach I'd even be inclined to pr same against master. 

I'd also suggest a context parameter only belongs on Begin() signatures for pools - if you're using a context you're certainly doing something transactional in the general sense.  That incorporates the behavior described above most succinctly and forestalls the bizarre possibilities the context fetishism that ended up in database/sql allows.

**Comment by tejasmanohar** [comment]
+1 for contexts. Cancelation is a pretty crucial feature, e.g. right now, I'm not sure how to "timeout" a query.

**Comment by j7b** [comment]
@tejasmanohar statement_timeout is how you do it:

```
tx, _ := db.Begin()
tx.Exec(`set local statement_timeout=1000`) // 1 second
// ...
```

I have a POC for a Begin() that can set local I use on my fork but I'm not inclined to pr it, it's not elegant.

**Comment by tejasmanohar** [comment]
Yeah, that's what I'm doing for now, though not sure how to asynchronously cancel queries (don't need to right now but I can see a use case for it).

**Comment by enjoylife** [comment]
This [article](https://hackernoon.com/education-of-a-programmer-aaecf2d35312) by a microsoft veteran is in general, a quick, good read. One section in particular is related to this issue and the comments on context between @j7b and @jackc.

A portion of the relevant section: 
 
> ... recognize that failure is expected. The only guaranteed way to detect failure in a distributed system is to simply decide you have waited “too long”. This naturally means that cancellation is first-class. Some layer of the system (perhaps plumbed through to the user) will need to decide it has waited too long and cancel the interaction. Cancelling is only about reestablishing local state and reclaiming local resources — there is no way to reliably propagate that cancellation through the system. It can sometimes be useful to have a low-cost, unreliable way to attempt to propagate cancellation as a performance optimization.

**Comment by j7b** [comment]
@enjoylife what about "You recognize that cancellation is not rollback since it is just reclaiming local resources and state. If rollback is necessary, it needs to be an end-to-end feature." Also, stock PostgreSQL installations (including clusters) aren't distributed systems from the perspective of clients, basically for that reason.

**Comment by jackc** [comment]
Regardless of the virtues or vices of the standard context system, it is the _blessed_ approach by the standard library. As of `v3`, both the pgx native interface and `stdlib` support have full context cancellation support.

**Comment by jackc** [comment]
`v3` has just been released with full context support.
