### ISSUE TITLE
introduce simple scan interface

### ISSUE THREAD

**Issue by emicklei** [jackc/pgx#221]
I am proposing to add the following interface to this package.
We have been using this as a pattern for many table accesses in multiple apps.

```
// Scannable exists for functions that can take both a pgx.Row and pgx.Rows.
type Scannable interface {
	Scan(dest ...interface{}) (err error)
}
```

It allow us to write resuable code related to reading the data into a model struct. For example, we have ```scanStoredMessage(storeId string, rows dao.Scannable) (*model.StoredMessage, error) ``` that can be used in functions such as ```GetStoredMessageById``` and ```GetStoredMessagesList```

**Comment by jackc** [comment]
Can you explain a bit more? I'm not exactly sure what you're asking for?

**Comment by emicklei** [comment]
I added this interface to our apps because (in our cases) the result of conn.Query and conn QueryRow had the same structure to be scanned. So in order to refactor that common part (scanning values into record fields), I defined the Scannable interface.

As I am copying this interface definition into each projects, I thought about adding it to the pgx package. 

I also checked with the Go database/sql package to see they already had such a definition (considering the fact that both Row and Rows have a Scan function). But it doesn't (should it?)

**Comment by jackc** [comment]
I'm sorry, I'm still not understanding exactly what this interface does? Can you post an example implementation and an example usage?

**Comment by jackc** [comment]
Okay, I just reread this thread again and I think I understand what you are asking. I've done something similar in some of my own application code.

A reason for not including it in core pgx (and I'm guessing in database/sql) is that the core package doesn't need it. Query and QueryRow would still return concrete types and no library code needs to accept a Scannable interface. It would simply be an unused definition. Since Go has implicit interfaces an interface defined in the application code can do everything an interface defined in the library can do.

**Comment by emicklei** [comment]
Yes, it would become an unused definition. And indeed because of the implicit interfaces, we can have such a pattern which I am using in many other places as well.

I suggest we close this.
