### ISSUE TITLE
OID constant for hstore?

### ISSUE THREAD

**Issue by ARolek** [jackc/pgx#227]
I'm working on an implementation that switches on Fielddescription.Oid and I need to support the hstore datatype. I can hard code `229530` but it would be better to have the Constant defined for hstore.

```sql
SELECT oid FROM pg_type WHERE typname = 'hstore';

-- result: 229530
```

**Comment by jackc** [comment]
The hstore OID is not stable across multiple PostgreSQL installations due to it being an extension.

```
jack@edi:~/dev/go/src/github.com$ psql
Expanded display is used automatically.
Timing is on.
Null display is "∅".
psql (9.6.1)
Type "help" for help.

jack=# SELECT oid FROM pg_type WHERE typname = 'hstore';
 oid 
-----
(0 rows)

Time: 6.289 ms
jack=# create extension hstore;
CREATE EXTENSION
Time: 72.397 ms
jack=# SELECT oid FROM pg_type WHERE typname = 'hstore';
  oid   
--------
 147427
(1 row)

Time: 0.400 ms
```

What's the solution? First, if possible use pgx's builtin hstore support. You shouldn't have to worry about what the OID is at all. If for some reason you really do need to switch based on OID then you can run that query at connection time to get the OID (or search through the Conn.PgTypes map).

**Comment by ARolek** [comment]
Thanks for the quick response, as well as saving me from introducing a sneaking bug. I'm using rows.FieldDescriptions() for my switch and have been keying off of the OIDs for the primitives. 

Looking at this some more, is there any reason why FieldDescription.Name == "hstore" would not be reliable?

**Comment by ARolek** [comment]
I meant to say FieldDescription.DataTypeName not FieldDescription.Name

**Comment by jackc** [comment]
That should work as well.

**Comment by ARolek** [comment]
Great. Thanks.
