### ISSUE TITLE
Corruption when reading an timestamptz

### ISSUE THREAD

**Issue by FrozenPrincess** [jackc/pgx#228]
Reading a timestamptz into a string results in corruption, and no error. e.g. 

  ` �8b�`

I would expect that it either turns it into a usable string (e.g. `::text` in postgres) or fails with a hard error

**Comment by jackc** [comment]
That behaviour is less than ideal for sure. The problem is scan into string does not check the type of underlying the PostgreSQL data. For data types encoded in binary like `timestamptz` it's definitely wrong. But some types beyond `varchar` and `text` are correct to decode into string.

The problem is complicated by the differences between text and binary encoding. In theory, we should just be able to allow anything encoded in text protocol and reject anything encoded in binary. But in practice there are some complications. Copy and row/record support both require that all values be encoded/decoded in the same format. So to make that support possible/easier, every data type that pgx can handle in binary is encoded in binary even when text and binary are equal such as `text`.

Since that approach is seemingly blocked, the next approach would be whitelist PG types that could be decoded into a string. But that's messy too, because we don't necessarily want to block types pgx doesn't know about from being scanned into a string

I did hack around a bit trying to get it to reject the definite bad cases and still allow the good ones and I wasn't successful.

This might need to wait for v3 of pgx. I'm not sure if it can be changed in a backwards compatible manner.

**Comment by jackc** [comment]
`v3` was just released and it will not allow scanning of binary values into strings.
