### ISSUE TITLE
Returning no error if jesus dies on a tree

### ISSUE THREAD

**Issue by FrozenPrincess** [jackc/pgx#229]
Starting with a schema:

```
CREATE TYPE crucifix AS ENUM('STAKE', 'CROSS');

CREATE TABLE jesus_deaths(
   place crucifix
);
```

Trying the test code:
```
_, err := pgx.Query("INSERT INTO jesus_deaths VALUES('tree')")
fmt.Println(err)
```

Returns a rather sensible: 

```
ERROR: invalid input value for enum crucifix: "TREE" (SQLSTATE 22P02)
```

Which is certainly correct, there's no honestly biblical interpretation of Jesus dying on a tree. However:

```
_, err := pgx.Query("INSERT INTO jesus_deaths VALUES($1)", "tree")
fmt.Println(err)
```

Makes it seem like he was lynched:
```
<nil>
```

but the error is just swallowed somewhere

**Comment by jackc** [comment]
The simplest solution is to use `Exec` instead of `Query`. `Exec` is designed to for statements that do not return a result set. `Query` is designed for statements that do return a result set.

That said, sometimes you do want to use `Query` or `QueryRow` for an insert because you want to use a `returning` clause. In the last example you gave, the error was not swallowed - it was just never read.

Try this instead:

```
rows, err := pool.Query("INSERT INTO jesus_deaths VALUES($1) returning place", "tree")
for rows.Next() {
	fmt.Println("never will get here")
}

fmt.Println("result of insert :", rows.Err())
```

Results in: `result of insert : ERROR: invalid input value for enum crucifix: "tree" (SQLSTATE 22P02)`

The reason for the slightly different behavior is as follows. When `Query` executes it first prepares a statement, then executes the statement. Your first example with a literal value can be determined to be an error when the statement is prepared. So it returns an error immediately. But the second example with the bound parameter can be prepared successfully. So `Query` succeeds because the statement was prepared and an execution request was sent to the PostgreSQL server. The error only shows up when you try to read the results.

**Comment by FrozenPrincess** [comment]
Thanks for looking into it. I didn't realize you need to check  `rows.Err()` after iterating. This ends up being rather unfortunately verbose, even for go standards, as you have to check for errors in three places: before iterating, during iteration and after iteration. 

Is there anyway to cut down on this, and have something like pgx peeks into the first entry to know if there's a scan error to return immediately?

**Comment by jackc** [comment]
The only easy way to cut down on error checks is to skip the check on `Scan`. If `Scan` fails then `rows.Err()` will be set. So if nothing is done with scanned data until after all rows are read then it is safe to ignore the `Scan` error and only look at `rows.Err()`.

As far as what pgx could do, the current API is equivalent to `database/sql`. The only solution would be a higher level API than `Query` and `Scan` that reads all results up front. The current API streams results. So it is entirely possible for it to fail at any of those three points. The plus side is only one row is required to be in memory at a time and processing can begin as soon as the first row arrives instead of waiting for the entire result set.

**Comment by FrozenPrincess** [comment]
Seems reasonable. Although I would've have thought that errors like above are always found at the start of the postgres response, so you'd not have to read through the entire result set to find it.

Thanks for your library -- by the way.
