### ISSUE TITLE
Unable to scan into pgx.NullString

### ISSUE THREAD

**Issue by reviewgen** [jackc/pgx#238]
I am seeing a strange issue when trying to Scan into a pgx.NullString. Not sure if this is by design or if I'm doing something wrong. 

Scenario:

```
type Item struct {
  Name pgx.NullString
}

type Collection {
  Name pgx.NullString
  Items []Item
```

What I am trying to do is write a query that will return the collection and and list of items. 

```
data := Collection{}

err := conn.QueryRow(`
  SELECT
    c.name,
    json_agg( json_build_object( 'name', i.name )) as items
  FROM
    collections
  INNER JOIN items ON ...
```

Running this code I can populate the Collection struct with the name and other fields that are of type pgx.NullStruct.

I can't however populate the Items array - I get the error `can't scan into dest[2]: json: cannot unmarshal string into Go value of type pgx.NullString`

The strange thing is though, if Instead of setting the Item.Name struct to `pgx.NullString` I set it to `null.String` from this package: http://gopkg.in/guregu/null.v3 - I get the the struct properly filled out without errors.

Any ideas on what is happening?

**Comment by jackc** [comment]
The order pgx attepts to decode values in is roughly the following: raw bytes, pgx.Scanner, sql.Scanner, JSON, and lastly native types. When pgx handles a JSON column value it will try to json.Unmarshal it into the provided value. It looks like for some reason JSON is taking priority over the pgx.Scanner interface, but not the sql.Scanner interface. Haven't had a chance to look in depth yet.

**Comment by jackc** [comment]
I looked a little closer. My above explanation was incorrect.

The `items` column is a `json` value so it is correct for it to be decoded as `json`. The reason it fails is `pgx.NullString` does not implement `UnmarshalJSON`. So when it is unable to decode the `json`.  `null.String` does implement `UnmarshalJSON`, which is why it is able to decode successfully.

It might be worth adding `UnmarshalJSON` to some of the core Null* types. But for the moment, pgx is compatible with `database/sql` types like those provided by http://gopkg.in/guregu/null.v3.

**Comment by reviewgen** [comment]
Hi Jack, 

That makes perfect sense. Thanks for such a quick reply. I'll stick to using guregu/null for now - but when I get a free day I may submit a PR for UnmarshalJSON for the pgx.Null Types. 

I really appreciate all the effort you've put into this lib.
