### ISSUE TITLE
Make all pgx error types public so they can be destructured.

### ISSUE THREAD

**Issue by hsyed** [jackc/pgx#241]
`scanArgError` is internal and thus cannot be destructured in a type switch. Additionally it would be nice if would contain the column name (don't know if that is possible efficiently). 

I could submit a pr for just making the error types public. Would such a pr go straight into master ? 

Alternatively (probably better) the other types should be collapsed into `PgError` ?

**Comment by jackc** [comment]
I definitely want to make errors easier to handle than string munging. I've been thinking about some of the stuff Dave Cheney has said about error handling.

* https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully
* https://dave.cheney.net/2016/06/12/stack-traces-and-the-errors-package
* https://www.youtube.com/watch?v=lsBF58Q-DnY

I think using https://github.com/pkg/errors and the practices given above might be the best approach. but I haven't attempted to integrate it into pgx so I don't know if there are any problems that may arise.

But regardless I do prefer some strategy that minimizes the coupling caused by exported error values and error types.

With regard to the `PgError` type, it specifically is for representing errors that were returned from the PostgreSQL server. I don't think it would be appropriate merge any other functionality into it.

**Comment by mbesancon** [comment]
@jackc you should look at https://github.com/juju/errors which helps a lot for informative error handling

**Comment by jackc** [comment]
The approach I've taken for `v4` is to keep error types internal when there is no obvious action the calling code could use to handle the error. But in addition it supports Go 1.13 style `Unwrap` to extract the underlying error if someone really wants to.

**Comment by matbesancon** [comment]
thanks for the work on this
