### ISSUE TITLE
Extending pointer types?

### ISSUE THREAD

**Issue by matthewmueller** [jackc/pgx#257]
I noticed that a lot of `Null*` types have pointer counterparts (e.g. `NullString` & `*string`). 

Is it possible to add custom pointer `Scan` methods? The type I'd like to extend is `*uuid.UUID`

**Comment by jackc** [comment]
> I noticed that a lot of Null* types have pointer counterparts (e.g. NullString & *string).

It's not so much that these are counterparts. It's just that pgx internally supports pointers to native Go types. Support for native (pointer) types have to be implemented directly driver.

> Is it possible to add custom pointer Scan methods? The type I'd like to extend is *uuid.UUID

What can be done is implement the Scanner and Encoder interfaces on the types you want . This is the mechanism for adding custom type support in v2 of pgx.

v3 is currently under development and has a more flexible type system. It also already supports UUID directly. You can try that if you are feeling adventurous.

**Comment by matthewmueller** [comment]
@jackc thanks for your response, i'll definitely give that a go. for my understanding, is it actually possible to extend a pointer type in v2? from the examples and source code, i'm only seeing `Null*` being extended.

**Comment by jackc** [comment]
There's nothing special about the `Null*` types. They just implement `Scanner` and `Encoder`. Any type with the appropriate methods can be scanned into.

For example, something like:

```go
type uuid [16]byte

func (u *uuid) Scan(r *ValueReader) error {
// ...
}
```

The reason some types are handled internally in pgx instead of through the Scanner and Encoder interfaces is it is impossible to add methods to native Go types such as `int64` or `string`.

It is also impossible to add methods to types defined in a different package. This makes integrating with 3rd party types such as https://github.com/shopspring/decimal problematic. Either they need to depend on pgx or pgx needs to depend on them for seamless usage. Neither is ideal.

The other alternative is to define a type based on the 3rd party type. For example:

```
type pgxDecimal decimal.Decimal

func (d *pgxDecimal) Scan(r *ValueReader) error {
// ...
}
```
This solves the dependency issue at the expense of needing to type convert to and from this scannable/encodable type and the original type.

A future release of pgx will resolve almost all these type system limitations, however it is a breaking change so it has to wait for a major release.

**Comment by matthewmueller** [comment]
Ah okay, thanks a lot for taking the time to explain this better to me.

I opened a PR to scanning into pointers #261 for this issue. I'm not sure this is the best way to address this issue, but it does resolve the scanning problems I've been having.

I just tried adding a new type like `pgxDecimal`, so it could be extended outside the codebase, but i wasn't able to get it working in v2.
