### ISSUE TITLE
unique constraint error is swallowed

### ISSUE THREAD

**Issue by volkmarbuehringer** [jackc/pgx#259]
I switched from pg to pgx and now an unique constraint error during insert isn't reported any more (usage as stdlib )

other errors are reported correctly

Also I found the preparation of queries more intuitive in the standard library, now I would have to prepare for every new connection again ?

**Comment by jackc** [comment]
Do you have a small sample that reproduces this? It sounds like it might be a bug.

For prepared statements, I assume you are referring to pgx's native interface as with the stdlib you would use database/sql in the normal fashion. One reason they are handled differently is due to pgx exposing connections directly and database/sql abstracting individual connections behind a pool. That said, if you are using pgx's ConnPool, you can prepare statements on the pool and it will handle ensuring they are prepared on all the connections it manages.

**Comment by volkmarbuehringer** [comment]
I switched completely to pgx
syntax errors are reported, data errors are not, in updates and inserts
I use Query together with returning clause:

`insert into ` + DBschema + `.%s(%s)values(%s) returning %s`,
`update ` + DBschema + `.%s set %s where %s returning %s`,


I use:

	rows, err := db.DBx.Query(stmt.Name, db.ROWQueryFunMap[tab](ga)...)
		if err != nil {
			senderErr(w, err)
			return
		}

**Comment by volkmarbuehringer** [comment]
Exec in the same place works.
So it is a problem of  Query and returning

**Comment by volkmarbuehringer** [comment]
It works now.
I had to use QueryRow and everything is ok
so never use Query with returning clause

**Comment by jackc** [comment]
In this case, `QueryRow` is what you want. But to be precise, `Query` can be used. The difference is you may need to try to read the rows before an error will manifest. i.e. `for rows.Next() {...}` Then `rows.Err()` would have the error.

The short rule of thumb for which method to use is:

`Exec` - no rows should be returned
`QueryRow` - exactly one row should be returned (and a single row insert or update with a returning clause counts)
`Query` - any number of rows should be returned
