### ISSUE TITLE
nil slice encoded as empty array instead of NULL

### ISSUE THREAD

**Issue by kelseyfrancis** [jackc/pgx#271]
The `encodeXSlice` functions in `values.go` encode a `nil` slice argument as an empty array. I assume this was an an intentional choice because it's common to treat a `nil` slice the same as an empty slice since its `len` is 0?

Would it make sense to include, e.g., `NullFloat64Slice` and/or make a note in the doc section "Array Mappings" about `nil` slices? It's simple enough to pass an explicit `nil` interface value as the argument to the query instead of a `nil` slice, but the current behavior surprised me at first.

**Comment by jackc** [comment]
It wasn't intentional. I would consider it a bug. I got bit by nil interface vs typed nil.

```go
func Encode(wbuf *WriteBuf, oid Oid, arg interface{}) error {
	if arg == nil {
		wbuf.WriteInt32(-1)
		return nil
	}
```

Was never expecting nil values to reach `encodeXSlice` functions.

The development `v3` branch has a totally revamped the type-mapping system and correctly handles typed nils. That's definitely what I prefer for the future.

The question is what to do in the current branch. We could fix it, at the cost of a small behavior change, or just document the known bug.

**Comment by jackc** [comment]
Just released `v3` today. That fixes the original issue. I think I'd prefer to leave `v2` as is to preserve compatibility.
