### ISSUE TITLE
suggention :  isNullable filed 

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#276]
Could you add below field?

from "messages.go"

type FieldDescription struct {
	Name            string
	Table           Oid
	AttributeNumber int16
	DataType        Oid
	DataTypeSize    int16
	DataTypeName    string
	Modifier        int32
	FormatCode      int16
.............
       Nullable     bool   <==============
.............
}

**Comment by jackc** [comment]
I was just going through the pgx backlog and saw I had never responded to your issue. Sorry about that. `FieldDescription` is now defined in the extracted library https://github.com/jackc/pgproto3. It is simply a struct of what PostgreSQL sends over the wire. Since PG doesn't include a nullable flag I don't think it would make sense to add it.

**Comment by coreybutler** [comment]
@jackc sorry to revive an old closed thread - if nullable isn't available on the wire, do you know how the std lib is handling it (https://golang.org/pkg/database/sql/#ColumnType.Nullable)? Any alternative ideas for identifying nullable fields?

**Comment by jackc** [comment]
My guess is it just isn't supported. From the docs:

> Nullable reports whether the column may be null. If a driver does not support this property ok will be false. 

> Any alternative ideas for identifying nullable fields?

The only way I know of would be to inspect either `information_schema` or the `pg_*` tables.
