### ISSUE TITLE
Possible race condition when used with context

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#280]
I'm trying to set up a reproducible test case, but it's tricky, so here's some information in case anyone can shed light on the problem.

Basically, we have an endpoint which starts a transaction, declares a cursor, yields data, and then closes the transaction. We're using `database/sql` + `stdlib`, in other words a connection pool. Here's the relevant part:

```
tx, err := db.BeginTx(ctx, nil)
if err != nil {
  return err
}
defer func() {
  if e := tx.Rollback(); e != nil {
    fmt.Fprintf(info, "Warning: Error on rollback, ignoring: %s\n", e)
  }
}()

_, err = tx.Exec(`
  DECLARE c NO SCROLL CURSOR FOR
  SELECT ...
`)
if err != nil {
  return err
}

for {
  rows, err := tx.Query(`FETCH 100 FROM c`)
  if err != nil {
    return err
  }
  defer rows.Close()

  end := true
  for rows.Next() {
    end = false
    // ...
  }
  if err := rows.Err(); err != nil {
    return err
  }
  rows.Close()

  if end {
    break
  }

  // Abort if canceled
  select {
  case <-ctx.Done():
    return ctx.Err()
  default:
  }
}
```

What we're seeing is that if a client HTTP connection is aborted, the context aborts the whole thing, and the rollback fails with `sql: Transaction has already been committed or rolled back`. That's fine. 

But on the _next_ request, we get `ERROR: cursor "c" already exists (SQLSTATE 42P03)` from PostgreSQL. In other words, something seems to be reusing a transaction. This is the only possibility that I know about, since cursor names are local to the transaction by default.

I've never encountered pgx's pool accidentally reusing transactions. Is it possible that the rollback call in the pool release code isn't foolproof? Also worth noting that the pool doesn't automatically close cursors, due to #279, although cursors _are_ closed when a transaction ends.

**Comment by atombender** [comment]
Here's some more information. If I add some debug output to `ConnPool`'s `Release`, I see that `conn.Exec("rollback")` returns the error `conn is busy`.

[Here](https://gist.github.com/atombender/e6591945a5d22d336bc106dbf321acb9) is a self-contained test case that consistently reproduced the problem. Output:

```shell
$ go build -o ./txntest . && PGDATABASE=template1 ./txntest
2017/06/07 20:48:48 first txn
2017/06/07 20:48:48 fetch fail: sql: Transaction has already been committed or rolled back
Error on rollback, ignoring: sql: Transaction has already been committed or rolled back
2017/06/07 20:48:48 second txn
2017/06/07 20:48:48 could not declare cursor: ERROR: cursor "c" already exists (SQLSTATE 42P03)
```

I'm using `BeginTx()` with a context, which automatically causes a rollback on cancel. If I use `Begin()`, and do a select on `ctx.Done()` to check for a cnacel, then I don't have any issues. Am I using `BeginTx()` wrong?

**Comment by jackc** [comment]
There's a few different complicating factors here.

First, pgx `v2` doesn't directly have any support for context (v3 has full context support and is currently in beta -- you might want to try with the `v3` branch). database/sql tries to still provide some context support even when the driver doesn't support it to varying degrees of success. In this case, it appears that it closes the connection.

That led me to discover a faulty assumption in pgx stdlib when created through `OpenFromConnPool`. Since in this mode pgx maintains an underlying connection pool it did not actually close connections when database/sql requested, it merely released them to the pgx ConnPool. This was okay when database/sql was closing a good connection (such as when shrinking the pool do to inactivity), but when database/sql was closing the conn because it considered the conn broken it caused this failure it caused a failure.

I've pushed a fix that causes the underlying stdlib ConnPool to not recycle connections that database/sql has requested to be closed. You're test case appears to work for me now.

**Comment by atombender** [comment]
Can confirm that the fix works. Thank you!
