### ISSUE TITLE
Is v3 stdlib Postgres date parsing behavior changed from previous version?

### ISSUE THREAD

**Issue by achiku** [jackc/pgx#286]
Hi, thank you so much for working on v3! I'm pretty fascinated about this branch with context support. I'm testing stdlib in v3 branch with my project, and saw a bit of difference in stdlib from previous major version, so I would like to know if this behavior is intended, or not.

Using the previous version of stdlib in master branch, Postgres `date` type (not `timestamp with time zone`) is parsed into `time.Time` with my local machine's timezone which is JST. However, when I use stdlib in v3 branch, `date` type is parsed into `time.Time` with UTC when I retrieved it from database.

My question is that is change in behavior parsing `date` into `time.Time` with UTC intended, or not.

**Comment by jackc** [comment]
It is _slightly_ intentional. With UTC the same `date` value will always yield the same `time.Time` value, which is not the case if we interpret it in the local time zone, which seems slightly desirable.

I didn't anticipate that this change would be noticed given the only valid fields of the time are year, month, and day. However, it looks like I was incorrect.

There's a bit of a mismatch between the PostgreSQL `date` type and Go's `time.Time`. It's not obvious to me whether local time or UTC is better for a `date`. I don't feel strongly either way -- I'm open to reverting to local time.

**Comment by achiku** [comment]
We found this out because we were not handling Postgres `date` with Go `time.Time` properly :( 
I think current v3 behavior is appropriate enough, and there is no need to switch to local time zone in Go when dealing with `date`. I just wanted make sure this is intended.

By the way, I tried [lib/pq](https://github.com/lib/pq) in [this test file](https://github.com/achiku/sample-pgx-stdlib/blob/master/pq/sample_test.go), found out they are doing pretty much the same, but without timezone info in Go (not event UTC).

```
 go test -v
=== RUN   TestPqPing
--- PASS: TestPqPing (0.08s)
=== RUN   TestTimeWithTz
--- PASS: TestTimeWithTz (0.03s)
        sample_test.go:60: 2017-08-18 00:00:00 +0900 JST
        sample_test.go:75: tm=2017-08-17 15:00:00 +0000 UTC, tz=UTC
        sample_test.go:76: dt=2017-08-18 00:00:00 +0000 +0000, tz=
        sample_test.go:79: a=2017-08-18 00:00:00 +0000 UTC, tz=UTC
        sample_test.go:82: b=2017-08-18 00:00:00 +0000 UTC, tz=
        sample_test.go:85: c=2017-08-18 00:00:00 +0900 JST, tz=Local
```
