### ISSUE TITLE
v3 internal directory

### ISSUE THREAD

**Issue by twils0** [jackc/pgx#293]
v3 is importing a directory labelled "internal" - which, as I understand it, is causing this error: "imports github.com/jackc/pgx/internal/sanitize: use of internal package not allowed"

I could be wrong. What I can tell you for sure is - I ran "go get gopkg.in/jackc/pgx.v3", and I got the above error.

**Comment by jackc** [comment]
I don't importing sub-packages works with gopkg.in. Try getting pgx normally and see if it works.

**Comment by twils0** [comment]
Sorry - I don't know what you mean by getting pgx normally. Is this main pgx repository (github.com/jackc/pgx) updated to v3?

**Comment by jackc** [comment]
v3 has reached stable release so `master` is now tracking `v3`.

**Comment by apratheek** [comment]
Hi, is there a fix for this? I ran into this problem today while updating my vendor dependencies using Glide. Any help would be appreciated. Thanks.

**Comment by twils0** [comment]
You've got to use the master branch of github. It's now v3 from my understanding.

Jackc - I'd recommend updating the readme to indicate you're now tracking v3 on the master branch. It wasn't clear to me at least, which pushed me to gopkg.in. Right now, it seems like you're saying the master branch may be unstable and that you recommend use of v3 (through gopkg.in - the only place it's available).

**Comment by jackc** [comment]
The version policy note is perhaps too strong a push for the `v3` branch instead of `master`.  Basically all it means is that new features on `master` may change a bit before they are frozen on the `v3` branch. But this rarely happens.

Maybe I'm over complicating it. In general, I'd expect people to use the master branch and vendor pgx. 

Since gopkg.in doesn't work with sub-packages if someone really needs to lock to `v2` or `v3` a git submodule would probably be good.
