### ISSUE TITLE
Named prepared statements.

### ISSUE THREAD

**Issue by aravindc26** [jackc/pgx#294]
How do I run named prepared statement using stdlib api's. I notice that stdlib only takes query as the argument whereas the native lib takes name and query as argument. This is useful when you need to run prepared statements across connections, which is not possible using [stdlib's api](http://godoc.org/github.com/jackc/pgx/stdlib#Conn.Prepare).

I also noticed that following code block *does not work*, while using stdlib.

```
db.Execute("prepare prep_query as select id from employees where name=$1;")
db.QueryRow("prep_query", "jackc")
```

**Comment by jackc** [comment]
That's a bit tricky since database/sql and pgx native have a different architecture for managing connections. pgx is fundamentally built on and exposes the concept of individual connections. A connection pool is built on top of that concept, but underlying connections are still exposed. database/sql has a higher level of abstraction and only exposes a connection pool concept. This leads to its prepared statement abstraction being different -- it needs to keep track of what underlying connections it actually has been prepared on.

Directly executing a prepare SQL statement definitely won't work through database/sql. You have no way of knowing what underlying connection the prepare happened on. Also, even in native pgx you would need to use the `Prepare` function instead of direct SQL to ensure pgx was aware of the prepared statement.

I _think_ you could prepare your statements in a AfterConnect hook on the ConnPool to ensure all connections had all prepared statements, and then use the named prepared statements from stdlib / database/sql.

**Comment by jackc** [comment]
> I think you could prepare your statements in a AfterConnect hook on the ConnPool to ensure all connections had all prepared statements, and then use the named prepared statements from stdlib / database/sql.

If this is still an issue the above approach should work. But with `v4` it should almost certainly unnecessary is it supports automatic preparing and caching of statements -- so there shouldn't be any need to manually manage them at all.
