### ISSUE TITLE
AfterClose alternative

### ISSUE THREAD

**Issue by ronaldslc** [jackc/pgx#298]
Hello, I noticed AfterClose is removed from V3, could I know why it was removed and what are the suggested alternatives? We used AfterClose to perform certain functions depending on whether the transaction was committed successfully, and doing tasks such as keeping track of whether a SQL mapped structure has a row lock within long chains of complex transactions (and resetting the lock boolean after close).

**Comment by jackc** [comment]
I presume you are referring to the hook on `Rows`? Or `Tx`? Originally, I added that as part of an attempt to make the connection pool pluggable. That didn't pan out so I figured it could be left out of v3. Didn't occur to me it could be used for anything else.

I don't mind adding it back. Since v3 is major release we do have the option of changing APIs. So was `AfterClose` fine as is, or do you think it might make sense to make any changes?

**Comment by ronaldslc** [comment]
As our use case is for it to perform maintenance / clean up function(s) should a transaction fail, we've simply restored the AfterClose function as it was, but only to Tx, it was fine for our purpose. Cheers
