### ISSUE TITLE
How are the types in pgtype/ext meant to be used?

### ISSUE THREAD

**Issue by dnaq** [jackc/pgx#316]
For example, if I want to store a satori/go.uuid UUID in the database (in a UUID column). As I understand the code the Set()-method of pgtype.UUID will be called which doesn't support go.uuid UUIDs. Is there any way to get pgx to use the Set()-method from pgtype/ext instead?

**Comment by jackc** [comment]
You typically shouldn't _need_ to use the pgtype/ext types directly, though you _may_ get better performance if you do. This is because pgx also supports database/sql compatible types. So satori/go.uuid and shopspring/decimal should work out of the box because they implement database/sql interfaces. However, this requires using the text format for encoding values. So the extension types may be a bit faster.

To use them you need to call `RegisterDataType` on the `ConnInfo` of your connection. If using a pool do this in the `AfterConnect` hook. Also, if you choose this style be sure to pull down the latest version of `master`. I found and fixed a bug with this functionality while refreshing my memory of how this works.

```go
package main

import (
	"fmt"
	"os"

	"github.com/jackc/pgx"
	"github.com/jackc/pgx/pgtype"
	satori "github.com/jackc/pgx/pgtype/ext/satori-uuid"
	"github.com/satori/go.uuid"
)

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Unable to parse environment:", err)
		os.Exit(1)
	}

	conn, err := pgx.Connect(config)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connection to database: %v\n", err)
		os.Exit(1)
	}

	conn.ConnInfo.RegisterDataType(pgtype.DataType{
		Value: &satori.UUID{},
		Name:  "uuid",
		OID:   2950,
	})

	u, err := uuid.FromString("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to parse UUID: %v\n", err)
		os.Exit(1)
	}

	var u2 uuid.UUID
	err = conn.QueryRow("select $1::uuid", u).Scan(&u2)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to transcode UUID: %v\n", err)
		os.Exit(1)
	}

	fmt.Println(u, u2)
}

```

**Comment by dnaq** [comment]
Thanks for your quick and helpful reply, that solves my problem.
