### ISSUE TITLE
Unable to change port

### ISSUE THREAD

**Issue by riaan53** [jackc/pgx#325]
Hi,

I get the following error when changing to another port. I tried with the parse con string helper as well. Please let me know if im doing something stupid.

```go
connPoolConfig := pgx.ConnPoolConfig{
	ConnConfig: pgx.ConnConfig{
		Host:     "127.0.0.1",
                Port:     uint16(26258),
		User:     "test",
		Password: "test",
		Database: "test",
	},
	MaxConnections: 5,
}
pool, err := pgx.NewConnPool(connPoolConfig)
if err != nil {
	log.Println("Unable to create connection pool", "error", err)
	os.Exit(1)
}
```

Error:
2017/09/18 22:08:28 Unable to create connection pool error ERROR: syntax error at or near "inet"
select '127.0.0.1'::inet, '1::'::inet
                    ^
 (SQLSTATE XX000)
exit status 1

Used latest master and cockroachdb. It works perfectly on v3.0.1.

**Comment by jackc** [comment]
Your code looks fine. Changing the port should work fine.

Hmm. The binary format of the PostgreSQL `inet` type can (theoretically) vary between servers. So as part of the connection process it requests known values to determine the server format.

Maybe cockroachdb doesn't have that type? Though I don't know what would have changed since v3.0.1.

**Comment by jackc** [comment]
Not sure if this issue still is relevant, but pgx no longer issues the `inet` format interrogation query so this should be resolved either way.
