### ISSUE TITLE
ConnPool.Release(conn) vs Conn.Close() vs Rows.Close()

### ISSUE THREAD

**Issue by MaerF0x0** [jackc/pgx#326]
Which of these do we need to use and which duplicate the others' functionality?

example code:
```golang
	c, err := p.Acquire()
	if err != nil {
		return nil, err
	}
	defer p.Release(c)  // Needed?
        defer c.Close() // Needed?

	rows, err := c.Query(`SELECT * FROM sur_la_table`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()  // Needed?
	for rows.Next() {
		var data []byte
		err := rows.Scan(&data)
		if err != nil {
			continue // #yolo
		}
		
	}
```

**Comment by jackc** [comment]
Any connection manually  gotten via `Acquire()` must be cleaned up with `Release()`. The connection should not be closed, otherwise the pool cannot reuse it.

It is only necessary to manually call `rows.Close` if you purposely do not read the whole result set. If you call `rows.Next()` until it returns false, or if `rows.Scan(...)` returns an error the rows object is closed automatically.
