### ISSUE TITLE
Binding pgtype.JSON doesn't work as I'd expect

### ISSUE THREAD

**Issue by wttw** [jackc/pgx#350]
If I create an pgtype.JSON variable, containing `{}` and insert it into the database the result I get is as though I'd inserted it as a struct:

    steve=# select * from foo;
                 bar
    -----------------------------
     {"Bytes":"e30=","Status":2}
    (1 row)

pgtype.JSONB is the same, unsurprisingly.

I think EncodeText and EncodeBinary should probably operate on `(src JSON)` instead of `(src *JSON)` but I'm not familiar enough with the code to go straight to a pull request.

**Comment by kelseyfrancis** [comment]
This ought to work if you pass `&v` as the arg instead of `v`:

    _, err = conn.Exec("insert into foo (bar) values ($1)", &v)

**Comment by jackc** [comment]
Yeah, that's surprising behavior. I'm not sure if there is a good solution though.

While defining the Encode* functions on the value instead of the pointer might be preferable in some cases, it's not for all. I thought it would be very unintuitive if some pgtypes were used by pointer and some by value so that suggested using pointer methods for everything.

In addition, the Go documentation recommends using all pointer methods if any method should be a pointer (https://golang.org/doc/faq#methods_on_values_or_pointers) and the Decode* methods must be pointer methods. Though it is interested that database/sql doesn't follow that rule for it's own Null* types...

It's only with encoding into a json/jsonb type that that becomes a problem because pgx automatically marshals the values into JSON. For other column types it would be an error when the type did not implement an encoder interface.

**Comment by wttw** [comment]
As another comparison MarshalJSON() tends to be a value method, while UnmarshalJSON() has to be a pointer method (e.g. json.RawMessage, or the CustomMarshalJSON example in the json docs.

I think that it'd be preferable from a library users perspective to have the automatically marshaling types use a value method rather than to require the user to pass those types in to a SQL query differently to other types in order for them to work correctly.

Consistent behaviour beats consistent implementation - especially when the inconsistent behaviour leads to silent data corruption rather than an error.

**Comment by jackc** [comment]
In hindsight, perhaps I should have defined all the Encode* methods on the values. However, we can't change that now without breaking backwards compatibility.

What we can do is detect this and return an error instead of silently storing the wrong data. I think that's the best we can do without a breaking change.

One more thing, it should be rare you need to use `pgtype.JSON` directly. You might find it more convenient to use a `[]byte` directly. It should be handled correctly and with less boilerplate.

**Comment by wttw** [comment]
> One more thing, it should be rare you need to use pgtype.JSON directly. You might find it more convenient to use a []byte directly. 

Yup, the issue came up with a kind-of-ORM I'm developing, trying to round-trip pgtype.* values, rather than in hand-written code.
