### ISSUE TITLE
Named arguments

### ISSUE THREAD

**Issue by jeromer** [jackc/pgx#387]
It would be useful to support named arguments in queries instead of only `$x` placeholders.

SQL queries would look like this:

    SELECT [...] FROM table WHERE foo=:arg;

    INSERT INTO table [...] VALUES(:name, :foo, :bar);

And then we could do something like:
```
conn.QueryRow(
        somSQL,
        map[string]interface{}{
            "name": "jack",
            "foo": "hello",
            "bar": "baz",
        }
    )
```

Supporting this feature would be more friendly with Go implementations of [yesql](https://github.com/krisajenkins/yesql) such as https://github.com/nleof/goyesql. Furthermore it would make it possible to use https://github.com/dimitri/regresql which is currently (as far as I know) not possible without named parameters.

Using `QueryRow` may not be possible because of the impact on the actual code (did not check). But using a new function like `QueryRowWithMap` (or any more meaningful name) would work.

I can write a patch if you find the feature useful for `pgx`.

:)

**Comment by jackc** [comment]
I'm open to this idea, but it may be more involved than it appears at first glance. PostgreSQL doesn't support named parameters. This would require query parsing (simple string substitution would not be sufficient) and rewriting. You can look at https://github.com/jackc/pgx/blob/master/internal/sanitize/sanitize.go to get an idea of the level of parsing required -- and/or maybe reuse most of it.

As far as the interface goes, I think the simplest would be a new function that maps a SQL string and map of arguments to a rewritten string and slice of arguments. e.g. `("select :id from users", map[string]interface{}{"id": 1})` maps to `("select $1 from users", []interface{1})`.

Beyond that, I'm not super keen on adding `QueryRowWithMap`. When you consider the variants and types that delegate query methods, this probably would involve adding a dozen or more new public functions.

There are two ways that I can think of to insert this functionality into `Query*`.

One is to define a new type `type NamedParamsMap map[string]interface{}` and have a single argument of that type trigger the new behavior. That would definitely require any libraries requiring named args to specifically support pgx though.

The other is to trigger this behavior on a single argument of `map[string]interface{}` **and** a SQL string that has named arguments. Just the map is insufficient because that could already be a single argument to a JSON or hstore field.

Another question is how this does or doesn't interact with normal prepared statements.

**Comment by GeertJohan** [comment]
Perhaps pgx could adopt how sqlx solved this, by adding such things as  `PrepareNamed` ?

**Comment by jackc** [comment]
Maybe. I think it would still require a simple parser and it looks like sqlx still ends up with "named" variants of a bunch of functions.

**Comment by fmmajd** [comment]
I think postgres now supports named arguments. I'm able to use them in the sql console.

**Comment by jackc** [comment]
The `psql` client supports named variables of a sort. But it is handled entirely client side. The PostgreSQL wire protocol only supports positional parameters.

**Comment by vspl-girish** [comment]
It's been a long time since any comments on this issue. But a simple wrapper method could address the issue. We can create positional parameters, implementing jackc's suggestion:

```
func queryNamed(ctx context.Context, sql string, namedArgs map[string]interface{}, conn *pgx.Conn) (pgx.Rows, error) {
	var i int = 1
	var args []interface{}
	// Loop the named args and replace with placeholders
	for pname, pval := range namedArgs {
		sql = strings.ReplaceAll(sql, ":"+pname, fmt.Sprint(`$`, i))
		args = append(args, pval)
		i++
	}
	// Execute the query and return
	return conn.Query(ctx, sql, args...)
}

// Call the method as follows
params := map[string]interface{}{
		"pcust_id":   1004744,
		"pcust_name": "D%",
}
sql := "Select customer_id, customer from customer Where customer_id = :pcust_id Or customer ilike :pcust_name Or control_account_id = :pcust_id Limit 5"
rows, err := queryNamed(context.Background(), sql, params, conn)
```

I am new to go and may have missed something....

**Comment by criscola** [comment]
I think it would be great do support `sql.Named`, in my case I had write what's basically a hack to avoid positional arguments.

Example of what I'd like to have:

```
func getNamedParameters(values map[string]interface{}) []interface{} {
	var inputParams []interface{}
	for k, v := range values {
		inputParams = append(inputParams, sql.Named(k, v))
	}
	return inputParams
}
```

then e.g. with `Query`, simply:

```
[..]
inputParams := getQueryInputs(operation.Inputs)
rows, err := c.c.Query(operation.Name, inputParams...)
[..]
```

this is the same code I've used for `go-mssqldb` (sqlserver driver).

**Comment by goldsky** [comment]
@vspl-girish [solution](https://github.com/jackc/pgx/issues/387#issuecomment-798348824) is close, but not quite correct for same prefix variables.
It fails for `@word` & `@word2` (and `@word...`) parameters.
You can try this instead:
```golang
var i int = 1
for pname, pval := range namedArgs[0] {
	m := regexp.MustCompile(`@\b` + pname + `\b`)
	// don't replace @ with $ in here, to avoid clash with regex's capture symbol
	// replace @ with other signature, to avoid clash with
	// postgres' array operators @> (contains) and <@ (is contained by)
	r := `@@@` + strconv.Itoa(i)
	sql = m.ReplaceAllString(sql, r)
	// replace @@@ with $ in here
	sql = strings.ReplaceAll(sql, "@@@", "$")
	args = append(args, pval)
	i++
}
```

**Comment by jackc** [comment]
I'm taking a look at this again for pgx v5. See #1186.

**Comment by jackc** [comment]
Just added this to the v5 dev branch. Example usage:

```go
conn.Query(ctx, "select * from widgets where foo = @foo and bar = @bar", pgx.NamedArgs{"foo": 1, "bar": 2}))
```

**Comment by kataras** [comment]
Good ond @jackc !

**Comment by edbmanniwood** [comment]
This is really cool that you have found a way to preserve what I've started thinking of as The Big Three methods: `Query()`, `QueryRow()`, and `Exec()`, as opposed to adding new methods. I hope I'm appreciating the hard work you put into designing a good API; this seems to continue the tradition.

**Comment by jackc** [comment]
Thanks! Indeed, you can build almost everything on top of those three methods. I kind of regret adding `QueryFunc()` as a method. Instead it should have been a function that takes anything implementing `Query()`. For that matter, `QueryRow` and `Exec` can actually be implemented in terms of `Query`. If I wasn't trying to maintain similarity with `database/sql` I would probably implement them as functions instead of methods as well.

>  I hope I'm appreciating the hard work you put into designing a good API; this seems to continue the tradition.

For more fun, take a look at `Collect` in pgxutil (https://github.com/jackc/pgxutil/blob/master/collect.go and https://github.com/jackc/pgxutil/blob/master/collect_test.go). I've been using this in my own projects and it really cleans up standard "select a list" type of queries. I'm considering whether it belongs in core pgx or not. It is really useful, but it doesn't actually need to be in the core project.

**Comment by paudley** [comment]
Ooo.. that's quite useful.  I'd love to see that included as it's a common pattern in my code.

**Comment by edbmanniwood** [comment]
@jackc , not sure if you go back and read old tickets, but I see you did ultimately decide to put pgxutil's `Collect`* and `RowTo*` functions into pgx5. Doing so really put them on my radar (as opposed to keeping them in a separate project). I've finally gotten around to playing with them. Thanks for that. I'm going to introduce these to my team at work tomorrow.

**Comment by jackc** [comment]
Thanks! Glad you're finding it valuable.
