### ISSUE TITLE
add method String to all pgtype

### ISSUE THREAD

**Issue by ruslanBik4** [jackc/pgx#390]
Hi!

 I thought that it would be nice to add method "String" or the ability to create a some method to all pgtype for JSON fast marshaling.
 At a minimum, there is a need for this for date types (DateRange etc.), so that you do not manually parse each time time.Format("2006-01-02").
 I can describe several such methods myself, if you give me such an opportunity

**Comment by jackc** [comment]
If it's specifically for JSON we would want to implement `MarshalJSON` and `UnmarshalJSON`.

However, one thing that has deterred me previously is it is not clear what the proper JSON representation should be for types like ranges. I'm open to the idea, but great care is needed because once we settle on a format changing it would be a breaking change.

As far as just getting some sort of string serialization, `EncodeText` and `DecodeText` will encode to and from the PostgreSQL text format.
