### ISSUE TITLE
pgtype.CharOID is not correctly formated or inserted

### ISSUE THREAD

**Issue by gadelkareem** [jackc/pgx#395]
Given the following
```
CREATE TABLE "public"."tb" ( 
	"id" Character( 40 ) NOT NULL,
	"d" JSONB NOT NULL,
	PRIMARY KEY ( "id" ) );
 ;
```
```
c.batch.Queue("INSERT INTO tb(id, d) VALUES ($1,$2) ON CONFLICT (id) DO NOTHING",
		[]interface{}{hash, somejson},
		[]pgtype.OID{pgtype.CharOID, pgtype.JSONBOID},
		nil,
)
```
hash is a SHA1
Only the first character of the hash is inserted, however switching to `pgtype.VarcharOID` solved the problem.

**Comment by jackc** [comment]
That is because internal and external names for a few PostgreSQL types are confusing. pgtype.CharOID is a single character.

https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.h#L294

pgtype.BPChar is what you want for a fix length multiple character field.

https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.h#L502

You might consider changing your table to `varchar(n)`. In general, `varchar(n)` is preferred over `char(n)` in PostgreSQL. The only significant difference is `char(n)` does blank padding.

Actually, it looks like you are storing the hex encoding of a hash. You could store it in half the space if you were to skip the hex encoding and decoding and store the hash as a `bytea` instead.

**Comment by gadelkareem** [comment]
Well the id is a sha1 hash which is exactly 40 characters so CHAR(40) is exactly what I need.
