### ISSUE TITLE
Setting a UUID field as NULL using a single statement

### ISSUE THREAD

**Issue by cheapRoc** [jackc/pgx#402]
I have a table with a key that is a UUID of the primary key of another table. Some of my writes might involve updating other fields of a row so I would like to use a single UPDATE statement using either a UUID or a NULL value. pgx allows me to UPDATE the field with a string typed UUID but I cannot use an empty string as NULL, despite the column allowing null values. I receive the following error when I attempt to update with a null string.

`ERROR: error in argument for $4: could not parse string "" as uuid (SQLSTATE XX000)`

To solve for this I'm using the following code when storing either an empty string or string UUID.

```go
keyID := new(pgtype.UUID)
if a.KeyID == "" {
    keyID.Status = pgtype.Null
} else {
    keyID.Status = pgtype.Present
    keyID.Set(a.KeyID)
}
```

For the moment, to solve for the simplest case, I only want to deal with UUIDs as strings in my app.

What is the proper way to UPDATE a UUID field to NULL or empty? Is this code proper use of `pgtype` (which BTW has worked out well in many other cases)?

**Comment by cheapRoc** [comment]
Actually, that snippet isn't working properly either. I'll end up just conditionally setting a second query. Still curious how to set UUIDs to NULL though.

**Comment by jackc** [comment]
Given this table:

```
create temporary table t (
	id int primary key,
	someuuid uuid
)
```

You can `nil` for the null value instead of having to use a `pgtype.UUID`.

`conn.Exec(`insert into t(id, someuuid) values($1, $2)`, 1, nil)`

You can also use a nil pointer to string. 

```
var s *string
_, err = conn.Exec(`insert into t(id, someuuid) values($1, $2)`, 1, s)
```

It also might be worth looking into `github.com/satori/go.uuid`. pgx has an extension package to integrate with it: `github.com/jackc/pgx/pgtype/ext/satori-uuid`.

If none of the above are acceptable then it would be possible to get the exact semantics of `""` assigns to `null` `uuid` by copying the `pgtype.UUID` and making a small change to the `Set` method. Then use your new type instead of `pgtype.UUID`. 

It even would be possible to configure pgx to use your new type by default by using `ConnInfo.RegisterDataType`.

**Comment by cheapRoc** [comment]
I thought the first thing I tried was a `nil` pointer to string but that doesn't seem like the case now. Thanks!
