### ISSUE TITLE
*Conn Used for Large Objects Cannot be Used for Other Queries

### ISSUE THREAD

**Issue by jonyoder** [jackc/pgx#403]
The test below breaks with `pgx`. This test is almost identical to the existing `TestLargeObjects` test, but it changes the following:

1. After creating the large object, the transaction is committed
1. A regular (not large object) SQL query is executed using the connect
1. A new transaction is created and used for the remainder of the large object tests

If I comment out the extra query, then this test passes, but with the extra query between transactions, I get a panic similar to this:

```txt
... Panic: runtime error: index out of range (PC=0x46351A)

/usr/local/go/src/runtime/panic.go:491
  in gopanic
/usr/local/go/src/runtime/panic.go:28
  in panicindex
/usr/local/go/src/encoding/binary/binary.go:111
  in LargeObjects.Open
/rstudio-pm/src/rspm/vendor/github.com/jackc/pgx/fastpath.go:111
  in LargeObjects.Open
/rstudio-pm/src/rspm/vendor/github.com/jackc/pgx/large_objects.go:72
  in LargeObjects.Open
```

## The Test that Fails

```go
func TestLargeObjectsMultipleTransactions(t *testing.T) {
	t.Parallel()

	conn, err := pgx.Connect(*defaultConnConfig)
	if err != nil {
		t.Fatal(err)
	}

	tx, err := conn.Begin()
	if err != nil {
		t.Fatal(err)
	}

	lo, err := tx.LargeObjects()
	if err != nil {
		t.Fatal(err)
	}

	id, err := lo.Create(0)
	if err != nil {
		t.Fatal(err)
	}

	obj, err := lo.Open(id, pgx.LargeObjectModeWrite)
	if err != nil {
		t.Fatal(err)
	}

	n, err := obj.Write([]byte("testing"))
	if err != nil {
		t.Fatal(err)
	}
	if n != 7 {
		t.Errorf("Expected n to be 7, got %d", n)
	}

	// Commit the first transaction
	err = tx.Commit()
	if err != nil {
		t.Fatal(err)
	}

	// IMPORTANT: Use the same connection for another query
	query := `select loid from pg_largeobject`
	rows, err := conn.Query(query)
	if err != nil {
		t.Fatal(err)
	}
	rows.Close()

	// Start a new transaction
	tx2, err := conn.Begin()
	if err != nil {
		t.Fatal(err)
	}

	lo2, err := tx2.LargeObjects()
	if err != nil {
		t.Fatal(err)
	}

	// Reopen the large object in the new transaction
	obj2, err := lo2.Open(id, pgx.LargeObjectModeRead|pgx.LargeObjectModeWrite)
	if err != nil {
		t.Fatal(err)
	}

	pos, err := obj2.Seek(1, 0)
	if err != nil {
		t.Fatal(err)
	}
	if pos != 1 {
		t.Errorf("Expected pos to be 1, got %d", pos)
	}

	res := make([]byte, 6)
	n, err = obj2.Read(res)
	if err != nil {
		t.Fatal(err)
	}
	if string(res) != "esting" {
		t.Errorf(`Expected res to be "esting", got %q`, res)
	}
	if n != 6 {
		t.Errorf("Expected n to be 6, got %d", n)
	}

	n, err = obj2.Read(res)
	if err != io.EOF {
		t.Error("Expected io.EOF, go nil")
	}
	if n != 0 {
		t.Errorf("Expected n to be 0, got %d", n)
	}

	pos, err = obj2.Tell()
	if err != nil {
		t.Fatal(err)
	}
	if pos != 7 {
		t.Errorf("Expected pos to be 7, got %d", pos)
	}

	err = obj2.Truncate(1)
	if err != nil {
		t.Fatal(err)
	}

	pos, err = obj2.Seek(-1, 2)
	if err != nil {
		t.Fatal(err)
	}
	if pos != 0 {
		t.Errorf("Expected pos to be 0, got %d", pos)
	}

	res = make([]byte, 2)
	n, err = obj2.Read(res)
	if err != io.EOF {
		t.Errorf("Expected err to be io.EOF, got %v", err)
	}
	if n != 1 {
		t.Errorf("Expected n to be 1, got %d", n)
	}
	if res[0] != 't' {
		t.Errorf("Expected res[0] to be 't', got %v", res[0])
	}

	err = obj2.Close()
	if err != nil {
		t.Fatal(err)
	}

	err = lo2.Unlink(id)
	if err != nil {
		t.Fatal(err)
	}

	_, err = lo2.Open(id, pgx.LargeObjectModeRead)
	if e, ok := err.(pgx.PgError); !ok || e.Code != "42704" {
		t.Errorf("Expected undefined_object error (42704), got %#v", err)
	}
}
```

Is this intended?

**Comment by jackc** [comment]
Well, a panic is definitely not intended. But I can't say I've ever used PostgreSQL large objects, so I'm somewhat unfamiliar with how it all should work. But since you were good enough to provide a test case, I'll take a quick look.

...

On my machine this query `select loid from pg_largeobject` fails due to `ERROR: permission denied for relation pg_largeobject (SQLSTATE 42501)`. But I'm guessing that isn't really the problem. I changed the query to `select n from generate_series(1,10) n` and was able to get the "index out of range" panic.

...

Ah. This is interesting. There seems to be an issue with ready for query tracking.

...

fastpath.Call was not incrementing pendingReadyForQueryCount when it sent a function call. But it was being decremented when the function call was finished and the server sent the ready for query message. This caused pendingReadyForQueryCount to go negative. This meant that any subsequent activity that depended on ensureConnectionReadyForQuery would not operate correctly because the connection would be considered ready before it had read all previous data off the wire.

Should be fixed now.

**Comment by jonyoder** [comment]
Great! Thanks for the fix! On a partially unrelated note, it would be helpful if you provided a brief dev README that explains how to set up a dev environment for pgx. I'd be happy to contribute a PR when I run into issues, but I struggled to get a dev environment set up to build and test pgx.

**Comment by jackc** [comment]
Do you recall at what point you ran into a problem? I have docs here: https://github.com/jackc/pgx#testing but obviously they may have fallen out of date.

**Comment by jonyoder** [comment]
Oh, thanks. I totally missed that section. I'll take a look. I expect that a good bit of my problem is that I don't have a lot of experience with bootstrapping a new Go project. I've been working almost exclusively in large projects that are quite mature and managed using Makefiles, docker, `go dep`, etc.
