### ISSUE TITLE
Feature request: connection testing on checkout

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [jackc/pgx#427]
Hi,

I was looking at ways to make sure that connections handed from the pool are not dead.

I'm aiming to support situations where the DB server might have been restarted, or the connection has been lost for whatever reason.

I have read the discussion in #74.  I see that transaction `Begin()` does retry the connection - and so far, wrapping all server-side DB interaction into a transaction works for us as an interim workaround.

Other DB pools I have worked with (in the Java world) support setting up a test query to be run each time a connection is checked out from the pool (or alternatively returned to the pool).  The test query might be just `SELECT 1;`, or it might be specific to the database driver.

For Apache Commons DBCP, the options configuring this behavior are called `validationQuery`  / `testOnBorrow` / `testOnReturn`: 
https://commons.apache.org/proper/commons-dbcp/configuration.html

For the C3P0 project, these are called `preferredTestQuery` / `testConnectionOnCheckout` / `testConnectionOnCheckin`:
https://www.mchange.com/projects/c3p0/#testConnectionOnCheckout

Would adding similar options to pgx sound as a suitable addition?

Cheers,
Vlad

**Comment by jackc** [comment]
I am a little hesitant, but I'm open to being convinced.

Running an extra query on every connection pool checkout could be quite expensive when doing many short queries.

In addition, it doesn't guarantee that the connection is good when you want it -- it's possible the test query succeeds and then the connection is dropped. So it is still necessary to handle failures later. Though I suppose that practically it might minimize the case sufficiently to allow for a failure instead of needing additional retry logic.

If we want to go down this path I think it would be better to have a generic validateOnCheckout callback rather than a test query to run. Then the test logic could be customized as needed. For example, it might only run the test query if the connection had been inactive for a least 30 seconds.

**Comment by vladimir-mencl-eresearch** [comment]
Hi,

Thanks for getting back to me.

I agree the connection validation would be an extra cost - and I'm proposing it as an optional setting.  Default behavior would not change, it would be just an option to turn it on.

I like the idea of a callback instead of a test query - it would better suit Go, and gives more flexibility.

Not sure how the callback would be able to drive decisions based on how long the connection has been idle for - does pgx track the idle time in the pool?

If we agree on the idea here, how would you like to get it realized?  Would you prefer this comes from within the project, or would you welcome a pull request?

For the latter, I'd envision adding the following to `ConnPoolConfig`:
```
    BeforeAcquire   func(*Conn) error // function to call on every connection checkout to validate the connection
```

Thanks again for getting back to me - and I look forward to hearing from you further.

Cheers,
Vlad

**Comment by sean-** [comment]
A connection validation callback ensures the wrong problem is being solved by a code base.  A connection being dropped mid-transaction or idle in a connection pool has the same consequence as a retriable serializable exception due to concurrent modifications of a record: the entire transaction needs to be retried.  If you have retry handling for an entire transaction, it doesn't matter if the transaction failed because of a stale connection in the connection pool or because there was a serializable exception in the transaction.  In all cases, these errors are retriable and should be handled by a library above `pgx`, not by `pgx` directly (unless `pgx` grows a notion of a retriable error, in which case, I would love to just push a `func` into `pgx` so it can execute the function for me - I'm happy to provide suggestions here).

It would be good if there were a pattern that people could pull from, however.  I tend to use [`backoff`](https://github.com/cenkalti/backoff), but that's a personal preference.  Regardless, there are a number of retry libraries and use of a retry mechanism is the right way to handle this type of problem.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Sean,

Thanks for the reply.

I agree that in the general case, connection validation on checkout would not be enough.

But I am looking at a concrete use case: a server serving a small set of API calls, mostly sitting idle.

If the DB connection is lost in the middle of a (short-lived) transaction - then yes, our server would catch that error, and report it back to the client.  And the client would handle the error - either propagating it further up, or retrying.

But I am looking for a simple solution for the most likely source of lost connections: connection having been lost while sitting idle in the pool.

We kinda get this functionality by wrapping the DB accessing code behind each API call into a transaction - pgx already gives the retry behavior for transaction BEGIN.

This however means that we are unnecessarily wrapping simple read-only API calls into DB-level transactions.

Having easy means to test connections on checkout would mean we solve the most frequent/likely cause of lost connections, hiding them from the client.  And leave standard error handling and reporting for other errors, to be reported to clients.

Would this sound to you as an acceptable justification of the feature?

Cheers,
Vlad

**Comment by sean-** [comment]
> But I am looking at a concrete use case: a server serving a small set of API calls, mostly sitting idle.

IMO, if connections are idle for long periods of time, then the pool isn't being tuned well in `pgx.ConnPoolConfig`.  Ideally there is only one idle connection at any given instant (or actually, zero idle connections because they're all in use and there is no backlog of work waiting for a connection).

> If the DB connection is lost in the middle of a (short-lived) transaction - then yes, our server would catch that error, and report it back to the client. And the client would handle the error - either propagating it further up, or retrying.

Sure.

> But I am looking for a simple solution for the most likely source of lost connections: connection having been lost while sitting idle in the pool.

It sounds like that's a solution, but not necessarily the solution I'm advocating for.  By that I mean, it sounds like idle pool settings need to be made more aggressive in terms of reaping idle connections and recycling connections that are in use.  The goal of the connection pool settings should be to make sure that the connection pool is nearly 100% utilized.  If there are 5x connections to PostgreSQL from the pool, and 4x of them are active at any one point in time, then I'd be happy with an 80% utilization.  If there are 100x open connections and only 1x of them is active, then I'd be unhappy with that utilization.  Similarly, 100x open and 99x in use would be great (though I'd also suggest at this last example, the database may be saturated :grinning: ).

> This however means that we are unnecessarily wrapping simple read-only API calls into DB-level transactions.

I'd argue that it is necessary because of the next point:

> Having easy means to test connections on checkout would mean we solve the most frequent/likely cause of lost connections, hiding them from the client. And leave standard error handling and reporting for other errors, to be reported to clients.

Reporting errors back to the client when the application could retry them is propagating implementation details back to the user.  Until the response timeout/SLA is breached, who cares how many round-trips it took to the database?  Retry until the failure count or timeout is hit.

If the volume of these retryable errors is low enough, then it seems like pushing new functionality into the connection checkout handler is a solution to the wrong problem.  Why not set the pool size to 0 if something has a low rate?  If something has a high-rate, all you need to do is tune the pool size and settings to ensure that there is at most one idle connection at all times and aggressive prune any idle connection.  This has the virtue of meaning the connection pool is close to 100% utilized.

> Would this sound to you as an acceptable justification of the feature?

I'm not the one you need to convince, to be clear, but it sounds like this is a well-meaning suggestion, but not a preferred solution in my book.  I jumped on this issue because I've seen this request in the past elsewhere with JDBC and ended up having to unwind that code in favor of properly tuning the connection pool.

My suggestion would be to:

1. monitor the connection pool utilization ratio.  My suspicion is this ratio is far from 100%
2. see if you can monitor the age of all connections in the idle state.  If there is an idle TCP reaper or something similar that is killing connections without explicitly closing the socket, then I'd adjust the max age to be under this TCP reaper interval.
3. tune the connection pool such that the rate of connects/disconnects and acquire/release operations boosts the connection pool utilization to as close to 100% as possible.
4. If, and only if, there are errors when the connection pool is near 100% utilization, then I would consider adding a retry mechanism for transactions, which would include stale connections from the connection pool

My suspicion is that the connection pool that you're working with has many long-lived TCP connections to PostgreSQL and those connections are becoming stale.  Unlike where there is a network partition blocking 100% of established connections, only old connections are entering this invalid/zombie state.  The average age of an idle connection too long for the DB or a firewall/LB, which begs the question: why bother keeping the connection open?  Reducing connections to PostgreSQL reduces the number of locks that PostgreSQL needs to acquire/contend with.  If you have pgbouncer, for instance, then I'd use something pretty aggressive like 15s for the max idle age of connections.

I hope that perspective helps.  If you have new information regarding your environment that I didn't incorporate into my speculative solution to the problem driving the feature request, lmk.  Like I said, I've been down this road a few times and have found the above to be a better path. YMMV, but those are my $0.02.

**Comment by jackc** [comment]
It feels like there are a few slightly different problems here and significant different situations proposed for solving them.

I'm not sure at this point what the right way to go is.

I think it is clear the native connection pool needs some additional abilities to shrink when connections are unused. The pool hasn't changed much since its initial implementation ~5 years ago. At the moment it never closes unused connections. This is a clear deficiency.

As far as retries, that is really tricky to handle correctly, which is why we currently only do it on begin. Perhaps somewhere a flag could be added to query options that indicates the query is idempotent... I'm not sure.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Jack,

I see the pitfalls with retries and I agree `BEGIN` is the (almost) only one where it's safe to retry.

That's why I was asking for connection validation (be it via a query or a callback).  It could be a generic callback (not tied to connection validation), same as there is one for connection creation.  Returning an error would indicate that the connection is to be closed and the checkout should be retried with a new one.

Other pool implementations have a similar feature (as per my initial post here).

But I'm not pushing for it - your call and I'll accept the outcome.

Cheers,
Vlad

**Comment by fastest963** [comment]
We're getting errors from "use of closed network connection" from prepareEx which is internally called when doing a query unless you enabled simple. Can't prepareEx be safely retired?

Additionally, our workload is 2-3x higher during the day than at night so we can't have a static pool configuration that leaves no idle connections at night but also can support the traffic during the day without churning.

Additionally maybe some sort of idle timeout would help here? If a connection has been unused in the pool for more than X then discard it?

**Comment by fastest963** [comment]
If someone wants to glance at the sanity of https://github.com/fastest963/pgx/commit/b8d9f382672f9663ecab0f465c68821780c35092. I'm not a fan of changing the options within the function but otherwise I'd have to change the return and break the function signature, or muck up the error by wrapping it. I was thinking that maybe you could set Retryable if you knew the query could be retried (SELECT or otherwise) in addition to it being set automatically. I also added a few more logs than ideal just so I can observe it.

Essentially we should be able to retry the `prepareEx` network errors and also retry if `waitForPreviousCancelQuery` errors. Specifically `waitForPreviousCancelQuery` seems to be the first thing to error if the connection was already closed but if it's not closed but in a broken state then `prepareEx` will error with `i/o timeout`.

By making both of those retry that solves a lot of our issues.

**Comment by jackc** [comment]
@fastest963 

As far as I can tell this is only designed to work with the database/sql interface. If that's the case another approach may be to make the stdlib adapter separately run `Prepare*` and `Exec*`. Then the error from the Prepare could be as `driver.ErrBadConn`.

Not sure about `waitForPreviousCancelQuery`.

**Comment by fastest963** [comment]
I have been using it now for a week or so without the `database/sql` interface. I have something like:

```
for i := 0; i < 3; i++ {
	opts := &pgx.QueryExOptions{}
	_, err = conn.ExecEx(ctx, query, opts, args...)
	if err != nil && opts.retryable {
		continue
	}
	break
}
```

**Comment by jackc** [comment]
Oh, I see. Hmm...

On line 3, is that actually a `ConnPool` instead of a `Conn`? Otherwise, I don't see how it would work.

As far as all connections being lost at the same time, are you aware of `ConnPool.Reset()`? Once you detect one fatal error you can reset the whole pool at once.

I'm not really sure what I think overall about the `Retryable` idea. It's not terribly elegant, but it seems to work and I don't have any better ideas that are as simple to implement. What I'd really like to do is de-couple the connection pool such that alternative pools with different behavior can be used. This strikes me as the place retry logic belongs.

**Comment by fastest963** [comment]
I could make new methods with new signatures that pools could call. Then I wouldn't need to break or change the existing methods and it would be cleaner. Let me make a PR

**Comment by fastest963** [comment]
What do you think about: https://github.com/fastest963/pgx/commit/8b9ecc5694d35c5f8b2e2b9d8f11a08890f83b00 ? I was going to make a PR but thought I'd run it by you here first before I write tests and everything else.

Essentially a pool would just wrap the Conn in `RetryableConn` and then the methods on that Conn would have a different signature that would then tell the pool it could be retried.

> On line 3, is that actually a ConnPool instead of a Conn? Otherwise, I don't see how it would work.

In my example I omitted the Get/Put that we do with our own pool that makes it work like you'd imagine.

> As far as all connections being lost at the same time, are you aware of ConnPool.Reset()? Once you detect one fatal error you can reset the whole pool at once.

Reset is a little bit more extreme than I'd like since a single fatal error doesn't imply that every single connection is reset. We have 3-7 servers in each region and so just because one server was restarted/down doesn't mean that we need to reset all 300+ connections that might be still be fine.

**Comment by fastest963** [comment]
@jackc sure, I'll keep thinking of better ways to solve it. I was debating making the return be a struct instead of just a bool so it could contain `Retryable` and potentially other things in the future. I'm not sure what I'd name the method or the `*Conn` though. Making it a struct just seems more flexible in the future.
