### ISSUE TITLE
unknown oid when 'hstore' is created on the same session

### ISSUE THREAD

**Issue by sly010** [jackc/pgx#460]
I am not an expert on the protocol, but it seems we request a list of types once at connection time and we assume that list will not change for the rest of the session. If the hstore extension doesn't exist when we connect, we will receive an "unknown oid" error even if we created the extension in the meantime:

    conn.QueryRow(`
        CREATE EXTENSION IF NOT EXISTS "hstore";
        SELECT 'a->1'::hstore;
    `)

My use case:
I am running integration tests on new database instances and my tests fail.

My current workaround is to reconnect after "create extension", but i am wondering if there is a better solution. At the very least we should improve the error message.

**Comment by jackc** [comment]
Yes, types are read at connection time so new types will not be recognized.

It's unclear to me what be a better solution.  Automatically handling it would require detecting an unknown oid and re-scanning the types -- but since we are already in the midst of processing a result set we couldn't do that on the same connection. Would be quite tricky.

You can manually add types to the type map (see pgtype.ConnInfo), but I don't know if that is really any better than just reconnecting.

I'm kind of surprised that it didn't treat the unknown type as a generic text field, but even that wouldn't necessarily be an improvement.

**Comment by heedson** [comment]
Just want to follow this up to suggest this being documented/added as an FAQ. I can manage doing that but I just ran into an issue with this when setting up my database connection then running migrations which add types.

**Comment by jackc** [comment]
This should no longer be an issue in the new `v4` release as it does not require a type registry in the same way `v3` did. It still should be registered to use the binary protocol but it should run without error regardless.
