### ISSUE TITLE
PreferSimpleProtocol from default config is ignored

### ISSUE THREAD

**Issue by phobosxy** [jackc/pgx#495]
If I set _{PreferSimpleProtocol: true}_ in deafult config it's not work.

**Comment by phobosxy** [comment]
It's bug was introduced by following commit: https://github.com/jackc/pgx/commit/d9f21d02a5bcf904c2cd59d81c8645645f18b92a
because we make merge from parsed to default config in this line:
https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L155
and parsed config always have PreferSimpleProtocol set by default with false
and parse connection string:
https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L155
not support set PreferSimpleProtocol

**Comment by ikitiki** [comment]
I guess it's out of doubt that `Merge` should mind `PreferSimpleProtocol` parameter no matter one is setting or unsetting it.

Perhaps it would be a good idea to introduce a map in which `PreferSimpleProtocol` will be moved to, thus it will give an option to ignore the mentioned parameter while merging the configs.

or

maybe have DriverConfig priority over config taken from ConnectionString in Stdlib's `Open` method:
```
connConfig = parsedConfig.Merge(connConfig)
```

**Comment by phobosxy** [comment]
For me, use map is a good solution and can support the following possible extensions with Boolean options. Another solution to have some kind of priority is quite not obvious and more complex.

**Comment by phobosxy** [comment]
Should I prepare patch?

**Comment by jackc** [comment]
I'd prefer not to introduce a map for this option as I don't think there is any way to do this without it being a breaking change. For the next major release, I'm planning on restructuring connection configs such that merging configs is no longer necessary (or possible).

For now, I think it would be fair to for merge to handle PreferSimpleProtocol with an OR operation. That is, if either config has it set to true the result is true. This strikes me as reasonable because the only way it is ever set is directly by a programmer. None of the parse config functions set it. So if it would never be necessary to override a true to a false.

**Comment by sidh** [comment]
@jackc I've submitted PR with proposed fix, can we push it to master?

**Comment by jackc** [comment]
Done.

**Comment by sidh** [comment]
Thanks!
