### ISSUE TITLE
pgtype.JSON/JSONB Get() and Set() are not opposites

### ISSUE THREAD

**Issue by veger** [jackc/pgx#527]
We are having some issues with setting and getting JSON strings.

```
value := pgtype.JSONB{}
value.Set(`"test"`)  // store JSON string "test"
value.Get()            // returns test (without quotes, which is not even valid JSON)
```

When looking at the `Set()` and `Get()` it is clear that [setting a string](https://github.com/jackc/pgx/blob/master/pgtype/json.go#L23) directly stores the string in a byte array. While [getting the value](https://github.com/jackc/pgx/blob/master/pgtype/json.go#L60) calls `json.Unmarshal()` before returning the value.

So the (string) value never gets marshalled, and unmarshalling results in a modified value (compared to the original).

I would expect that `Set()` and `Get()` are opposites: what you put in you will get out!

But I seem to be unable to hit the [`default` branch](https://github.com/jackc/pgx/blob/master/pgtype/json.go#L45) on the `Set()` when I input a string, which would marshal the value (counteracting the unmarshal of `Get()`)

Can you give an example how I can solve this issue? Or is it a bug in the JSON type?

**Comment by jackc** [comment]
The issue is how  `Set` can decide whether a string is containing JSON or that it should be marshalled into JSON. There's no way to determine between those based on just on a string argument.

I had to decide one way or another and I decided to consider a string to be pre-encoded JSON.

If instead a string was marshalled automatically then we lose the ability to (easily) pass in a `string` of pre-encoded JSON. In addition, there is a further footgun that would cause. If someone did pass in a `string` of JSON it would be silently munged into a single JSON string the database. Whereas the error case in the present would be caught by the database because a raw string would not be valid JSON.

To `Set` a JSON string you would need to pre-encode the value.

As far as `Set` and `Get` being symmetrical, regardless of the above issue, that is impossible. `Set` can encode structs. But `Get` doesn't know what type it was, so it would return a `map[string]interface{}`.

**Comment by jackc** [comment]
Oh, one other option: pgx's type system is very extendible. Look into `*Conn.ConnInfo.RegisterDataType()`. You can entirely replace the backing type of any PostgreSQL type.

**Comment by veger** [comment]
> If instead a string was marshalled automatically then we lose the ability to (easily) pass in a string of pre-encoded JSON

I thought for pre-encoded JSON strings, there is the `[]byte` and `*[]byte` values? Especially since [`json.Marshal()`](https://golang.org/pkg/encoding/json/#Marshal) returns the byte array. If one happens to obtain a pre-encoded JSON string, one could easily use `[]byte(`"json string"`)? And `string` (and other (golang) primitives) are handled as JSON primitives.

But I think your pointer about `*Conn.ConnInfo.RegisterDataType()` could help us out to register our own JSON(B) implementation. So we don't need to pre-encode (which is an issue as we are using `pgtype.Value` and we don't know whether we are using JSON(B) or some other type)

So thank you for this suggestion, it will help us a lot!
