### ISSUE TITLE
[v4] Configurable custom OID's fetching

### ISSUE THREAD

**Issue by furdarius** [jackc/pgx#546]
In _v3_ of pgx driver on connection establishing driver sent [request to fetch OIDs](https://github.com/jackc/pgx/blob/5044e8473ad948114b6cb63f6f30f94fc7834667/conn.go#L398) from DB. In new version (_v4_), known OIDs registered via [pgtype.NewConnInfo()](https://github.com/jackc/pgtype/blob/4ed0de4755e042908ec6b12c68c0f900b7078726/pgtype.go#L175).

Is the list of hardcoded OID's complete enough? In postgres sources, there are more enumerated ids: https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat

Do I understand correctly that without additional OID's fetching, domain types and enums are not available?

Maybe it is worth to make configurable fetching of additional OID's?

In my practice, in _v3_ of pgx driver I prefer to limit or completely disable fetching of additional OID's via [CustomConnInfo](https://github.com/jackc/pgx/blob/5044e8473ad948114b6cb63f6f30f94fc7834667/conn.go#L79), cuz this query heavily loads the database due to locks. This approach (_disable OID's fetching_) works if we set restrictions about the usage of domain types and enums. Otherwise, in certain conditions (OID's fetching on each connection establishing, unlimited connection pool, db under heavy load), this will cause the database to become unavailable. Once this happened to one of our database:

(_This graph shows the number of requests for additional OID's fetching._)
![downtime](https://user-images.githubusercontent.com/2843971/59962938-e36ccc00-94f4-11e9-9217-254c449d3b4b.png)

**Comment by jackc** [comment]
You are correct about the current reasoning regarding enum and domain types. You are also correct that hard-coding the standard OIDs is probably a better approach than querying on every connection. In fact, that change is already in place for v4.

Regarding making the change for v3, I'm open to it if it can be done without breaking backwards compatibility (not sure how plausible that is).

Regarding the performance problem you are seeing, I would not have expected it to be so severe. As I recall, the connection pool caches the OID information and only makes the query on the first connection.

**Comment by furdarius** [comment]
> In fact, that change is already in place for v4.

In v4, as I see, there is no fetching of additional OID's. I suggest to make it configurable (disabled by default).

And, by the way, maybe the list of hardcoded OID's should be extended? In postgres sources, there are more OID's: https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat
 
> Regarding the performance problem you are seeing, I would not have expected it to be so severe. As I recall, the connection pool caches the OID information and only makes the query on the first connection.

Ye, but if db is under heavy load and latency increases then conn pool will be exhausted and new connections will be created with a high rate.

**Comment by jackc** [comment]
I'm not opposed to expanding the list of hard-coded OIDs or to adding back the optional fetching of additional OIDs -- but I'd have to be convinced. In `v4` every unknown OID is treated as `pgtype.GenericText` which is the same thing that would happen if we had the OID for the extra type. It still works to use a custom type that implements the encoding and decoding interfaces as a query argument or scan argument without registering the type.

The only case I can think of that would behave differently is assigning a type as the default encoder / decoder for an OID (and I think this would be very rare case). The user would need to first query the OID of the type name themselves before setting the default.

Back to the performance issue in `v3`, the built-in `ConnPool` should only ever make one OID query regardless of how many connections are created. It should copy ConnInfo to each connection after the first instead of requerying. See https://github.com/jackc/pgx/blob/master/conn_pool.go#L300 and https://github.com/jackc/pgx/blob/master/conn.go#L382.

**Comment by furdarius** [comment]
> In v4 every unknown OID is treated as pgtype.GenericText which is the same thing that would happen if we had the OID for the extra type.

Ah, got it! Then any kind of additional request are not necessary) Issue can be closed.

About `v3` issues, I'll try to recheck behavior and create another issue if will find any problems.

Thank you!
