### ISSUE TITLE
blocking query

### ISSUE THREAD

**Issue by jney** [jackc/pgx#593]
Hi.

I've got the following code (approximatively):

```go
conf, _ := pgx.ParseConnectionString(url)
db, _ := pgx.NewConnPool(pgx.ConnPoolConfig{ConnConfig: conf, MaxConnections: 16})

var myQuery = `
insert into items (campaign_id, data, price)
values ($1, $2, $3)
returning row_to_json(items.*), (select row_to_json(c.*) from campaigns c where id = items.campaign_id)`

func (i *Item) create() error {
	var c *campaign
	if err := db.QueryRow(myQuery, i.CampaignId, i.Data, i.Price).Scan(&i, &c); err != nil {
		return err
	}
	l.Campaign = c
	return nil
}
```

locally I can run `i.create()` as much as i want. but running it on aws' rds using postgres v11, I can only run the number of the connections in the pool (16 in the previous example).

Any idea why the connections are not reused?

**Comment by jney** [comment]
more informations:
- after simplifying the query, the problem seems to be related to the insert.
- I run locally postgres 11.5 and rds 11.4

**Comment by jney** [comment]
another point. I don't reproduce the issue using `v4`

**Comment by jackc** [comment]
That's really strange. I'm not really sure what would be different between RDS and a local PostgreSQL. Maybe TCP vs Unix socket?

`v4` has a significantly different internal structure than `v3`. So it's not surprising that it behaves differently -- but since it is so different it is difficult to draw any conclusions of what specifically is causing or fixing the problem.

It might narrow the problem down further to see if the problem also exists on a single connection instead of the connection pool. i.e. Check out a single connection, execute the problem query, then try to use that connection again.

**Comment by jney** [comment]
> Maybe TCP vs Unix socket?

The both conf are using tcp, indeed, local run in a separate docker

> Check out a single connection, execute the problem query, then try to use that connection again.

Using a single connection I don't have any trouble

By the way, it seems now I reproduced using `v4`

**Comment by jackc** [comment]
That is really confusing. I can't think of any reason that RDS or running through the pool would cause this behavior. We're practically at the point of needing to run a packet capture to see exactly what is going over the wire differently with RDS and local.

The only unusual part of your query is the returning clause. Maybe try with a simpler `returning id`.
