### ISSUE TITLE
pgx.NullString adding braces and "true"

### ISSUE THREAD

**Issue by nkev** [jackc/pgx#60]
I have a nullable varchar(100) database column called "title" that renders fine with a Go type of "string" using {{.title }} in a standard HTML template via the **github.com/unrolled/render** package. But I need to account for null database values so I thought I should use pgx.NullString (with the native driver) as the model datatype. But then if the data is null, the HTML template renders the null value as  "{ false }". If the data is not null (e.g. "my title") it renders "{my title true}" including the braces.

**Comment by jackc** [comment]
I believe this would be because pgx.Null* types do not define String(), so template is basically doing a Printf with the %v format argument.

There are several possible solutions to this.

The most obvious would be to update pgx to define String() for the pgx.Null* types. However, that presents a problem as to what the correct return for String() on a null value would be. Probably "" or "NULL". However, this has the downside of making the null value and a non-null string indistinguishable from each other when output normally.

The next solution would be create a new type is simply the pgx.Null* with String defined for what makes sense for your application. See https://github.com/jackc/pgx/blob/master/conn.go#L73 for an example from pgx of making a new type from an existing one and adding new behavior. The Go docs describing the behavior are here: https://golang.org/ref/spec#Type_declarations.

Another solution would be to use different variable for the display value and to conditionally assign the correct string. This has the advantage of letting null be displayed differently in different contexts. For example, null may best be displayed as "", "0", "0.0", "empty", "unknown", or "null" depending on what exactly it is.

**Comment by anaxagoras** [comment]
One other solution to consider is adding String() , but having it panic when attempting to stringify a NULL. I know avoiding panic is a best practice, but the user really should be checking any potentially-null types anyway, as this is the nature of the beast when dealing with nullable columns from a strongly-typed language.

**Comment by nkev** [comment]
I worked out that the [pgx.NullString struct](https://github.com/jackc/pgx/blob/master/values.go#L195) has two parameters, "Valid" and String" so if I change my HTML template from {{ .Title }} to below, it works correctly. My title is only rendered if it is not null in the database: 

```Go
  {{ if .Title.Valid }}
  	<h3>{{ .Title.String }}</h3>
  {{ end }}
``` 

Similarly, my [pgx.NullHstore](https://github.com/jackc/pgx/blob/master/values.go#L493) "Specs" column also works too:

```Go
{{ if .Specs.Valid }}
	{{with .Specs.Hstore }}
	  <p>
		{{ range $key, $value := . }}
		   <strong>{{ $key }}</strong>: {{ $value }} <br/>
		{{ end }}
	  </p>
	{{end}}
{{ end }}
```

**Comment by nkev** [comment]
Actually, in that last code snippet, the $value variable is rendering with start and end braces. Any idea why that might happen?

**Comment by nkev** [comment]
Aha! it's the same issue... The $value variable is a pgx.NullString so you need to check for validity. The final working code to render a pgx.NullHstore in a template is:

```Go
{{ if .Specs.Valid }}
	{{with .Specs.Hstore }}
	  <p>
		{{ range $key, $value := . }}
		   <strong>{{ $key }}</strong>: 
			{{ if $value.Valid }}
		   		{{ $value.String }} <br/>
			{{ end }}
		{{ end }}
	  </p>
	{{end}}
{{ end }}
```
