### ISSUE TITLE
v4 tx.Rollback with canceled ctx

### ISSUE THREAD

**Issue by ldelossa** [jackc/pgx#609]
Hello,

It seems like there is a bug around starting a tx with a context. If the context is canceled before the tx is committed or rolled back it looks like the tx will not be rolledback. Is this the case ? 

example: 
https://play.golang.org/p/ye5LIxgJU-S

**Comment by jackc** [comment]
If you are referring to the `Rollback` not occurring when the context is cancelled -- the entire connection is closed in that case which causes the server to roll it back. This is done because if the context is canceled we need to return to the immediately. 

I've added some docs to make this a bit more clear: 67a09e3a1fa49ce1f7af12d24527abbe399d5ed4.

If you are referring to that fact that the context passed to `Begin` only affects sending the `begin` statement -- that is the documented behavior for `Begin`.

https://godoc.org/github.com/jackc/pgx#Conn.Begin

> Begin starts a transaction. Unlike database/sql, the context only affects the begin command. i.e. there is no auto-rollback on context cancelation.
