### ISSUE TITLE
Cannot assign to custom uuid like type [v3]

### ISSUE THREAD

**Issue by mvrhov** [jackc/pgx#612]
I have a struct, that embeds a uuid like type (in db is stored in uuid type) e.g

```go
type UUID struct {
    data [16]bytes
}

type MyID struct {
    UUID 
}

func (me *MyID ) Scan(value interface{}) error {
}

```

Then I have a struct that represents a DB row

```go
type DBRow struct {
    ID *MyID
}

z := &DBRow{}

r.Scan(&z.ID)
```

When I scan a row the column in the DB might be null then everything works as expected.. however when the row returns a result I get `cannot assign &{{16 bytes of data} 2} into *MyID`

The MyID does implement the Scanner interface but the method is not called as at the time your code checks for that the `d variable` in your code is still nil

P.S.

I know there is a workaround below. But that's a lot of boilerplate in a lot of functions... And I'd like to know if there is a better way.
```go
	f := pgtype.UUID{}
	r.Scan(&f)

	if f.Status == pgtype.Present {
		z.ID = &MyID{}
		z.ID .Scan(pf.Bytes)
	} else {
		z.ID = nil
	}
```

**Comment by jaltavilla** [comment]
We ran into something similar to this with arrays of uuids from another library. We were able to solve it by creating a type that implements the pgtype.Value interface. https://github.com/jackc/pgtype/blob/d3b475212c250949fca8b1336bc38911e5cef2ed/pgtype.go#L112, and registering that type with the ConnInfo on the connection. If you are using the pgx/pool package, you can do so in the AfterConnect function of the pool.

You need to make sure that the `AssignTo` method of the type that implements the Value interface can assign to `MyID`.

There might be a better way, but this seemed to work for us, and is transparent to callers of Scan.

**Comment by jackc** [comment]
> The MyID does implement the Scanner interface but the method is not called as at the time your code checks for that the d variable in your code is still nil

We can't call Scan() on a nil pointer.  Without that check you'd get a panic. Instead we consider scanning into nil an intentional skip of that column.

I'm not sure about the `AssignTo` technique referenced above, but `pgtype` didn't change much interface-wise from `v3` to `v4` so I suspect if it works in `v4` it would also work in `v3`.

You could also consider using it as a value in your DBRow struct instead of a pointer. It would save 8 bytes for the pointer and an allocation. (Of course this requires mapping the zero value to null or disallowing null).
