### ISSUE TITLE
Why Conn and Tx do not export CopyTo from PgConn?

### ISSUE THREAD

**Issue by kingluo** [jackc/pgx#614]
Only `CopyFrom` is exported, why? It breaks the usage if I need to upgrade the pgx from 3.6 to 4.0.

**Comment by jackc** [comment]
> It breaks the usage if I need to upgrade the pgx from 3.6 to 4.0.

Breaking changes are the reason it had to be new major release instead of a minor release -- there are multiple breaking changes.

---

> Only CopyFrom is exported

`CopyTo` hasn't been in pgx since `v2` -- it was removed in `v3` since it actually was misnamed -- it actually implemented `CopyFrom`.

Or are you actually referring to `*Conn.CopyToWriter` in pgx `v3`? That is what `*PgConn.CopyTo` is analogous to.

---

> why?

The difference between copy functionality in pgx and pgconn is as follows. In pgconn it is just a way of using a `io.Reader` or `io.Writer` to read or write data through the copy protocol. But it does no type conversion or anything to build the stream. The pgx layer handles converting types and building the copy stream. pgx only knows how to use the bulk import copy format. That is why only `CopyFrom` is available in pgx. It doesn't know how to read copy data as if it were query results. I suppose it could be done -- though I'm doubtful how much of a performance difference there would be.

**Comment by kingluo** [comment]
Yes, I refer to `*Conn.CopyToWriter` in pgx `v3`.
I need to invoke this method on `Tx`, but no such method in `v4`.

**Comment by jackc** [comment]
My intention in `v4` is that `pgx` handles high level interactions with PostgreSQL and `pgconn` handles low level interactions with PostgreSQL. `pgx` `v4` is less complicated than `v3` because of this separation of concerns. Reading or writing a raw stream of data through the copy protocol seemed to be a low level action.

Rather than `pgx` wrap every low level function of `pgconn` I wanted to expose the `pgconn` handle for use when necessary. Thus we have the `*Conn.PgConn()`.

But what I didn't anticipate was needing access from a `Tx`. Unfortunately, `Tx` is an interface so no methods can be added to it without breaking compatibility. The only way now to add methods is for the implementations of `Tx` to add the method and have the user code type assert its availability...

From application space, the workaround would be to grab the pointer to the `PgConn` before starting the `Tx`. The `PgConn` could be used while the `Tx` is in progress. Not ideal, but it would work.

**Comment by kingluo** [comment]
So is there plan to add `CopyTo` to `Tx`?

**Comment by jackc** [comment]
> So is there plan to add CopyTo to Tx?

No. Copy with a byte stream is a lower level function that belongs in `pgconn` now. If there ever is a `CopyTo` in `pgx` it would be something that uses the type conversion system not just a byte stream.

However, what I have done is added a `Conn()` method to `Tx`. This will allow accessing the `pgconn` copy functionality from a `Tx` via `tx.Conn().PgConn().CopyTo(...)`.
