### ISSUE TITLE
WaitForNotification Returning Nil

### ISSUE THREAD

**Issue by ekasetiawans** [jackc/pgx#618]
I trying to listening notification from `pg_notify` using `WaitForNotification` following `chat example`.
But, I have problem. The result of `WaitForNotification` sometimes returning nil on both returning values.
How to resolve this problem?

**Comment by kyle-johnson** [comment]
Does this happen when re-using the config or when using pgxpool?

pgx within the `connect` method decides whether or not to hook up its handler:
```go
	// Only install pgx notification system if no other callback handler is present.
	if config.Config.OnNotification == nil {
		config.Config.OnNotification = c.bufferNotifications
	} else {
		if c.shouldLog(LogLevelDebug) {
			c.log(ctx, LogLevelDebug, "pgx notification handler disabled by application supplied OnNotification", map[string]interface{}{"host": config.Config.Host})
		}
	}
```

Since `config.Config.OnNotification` gets mutated in the config itself, reusing the config for other connections results in problems: `WaitForNotification` will be triggered, but the value returned will be nil.

Either use `pgx.Connect` (which creates a new config on each connection) or use `pgx.ParseConfig` for each new connection.

_This doesn't work reliably with pgxpool and there's no simple way to recover._

**Comment by ekasetiawans** [comment]
Yes, I using pgxpool. I'll try using pgx.Connect, thanks.

**Comment by ekasetiawans** [comment]
solved using `pgx.Connect`

**Comment by jackc** [comment]
In general notifications should be handled outside of a connection pool context so using pgx.Connect is a good practice. But it is/was a bug to mutate `OnNotication` in `connect`. Fixed.
