### ISSUE TITLE
V3.6.0 returns relation not found from QueryEx 

### ISSUE THREAD

**Issue by dayadev** [jackc/pgx#621]
I am using v3.6.0 and started getting issues with QueryEx saying 
`ERROR: relation \"tablename\" does not exist (SQLSTATE 42P01)`

The same queries were working fine before and below is the query string I am passing to `QueryEx` func
`SELECT * FROM tablename`

Not sure what change is causing this issue

**Comment by jackc** [comment]
That doesn't really give much information to go on. But the error message indicates that the query is being sent to the PostgreSQL server and it is returning an error.

This is unlikely to be a pgx problem. It is likely that something has changed in the environment. I would suggest checking that you are connected to the host, database, and as the user you expect to be. If nothing is obvious there, then check your PostgreSQL `search_path`.

Since you do appear to have a working connection from pgx to the PostgreSQL server you might want to run diagnostic queries like `select * from information_schema.tables where table_schema not in ('information_schema', 'pg_catalog');`.
