### ISSUE TITLE
Deallocate in TX

### ISSUE THREAD

**Issue by MikhailChe** [jackc/pgx#638]
After #147 there is a Prepare function in Tx, which states that it is idempotent. But this line 
https://github.com/jackc/pgx/blob/693ba65a4aeaa63681cb1cfd9b08ed9a5e7268a5/conn.go#L247 may lead to errors on some servers. Here's what I do and what problem I'm facing:

1. create a connection pool
2. get a connection from pool
3. get a transaction from connection
4. prepare some statement "a" with sql "b"
5. use batch with the name of prepare statement "a"
6. commit transaction

Repeat 2-6 once. Now, if I repeat it third time - step 5 fails with "prepared statement "a" does not exist" - server cleaned up this prepared statements, and at step 4 statement is not sent to server, it's just checked to be in a cache of prepared statements.

I've managed to workaround this issue with explicit Deallocate, but for this I have to intermix calls to transaction and connection like this.

**Comment by MikhailChe** [comment]
Seems like a problem with incorrect pgBouncer in front of a database. Still, maybe there is a way to detect how server isolates transactions and prepared statements?

**Comment by jackc** [comment]
As far as I know, PgBouncer is incompatible with prepared statements in transaction pooling mode. So you can't explicitly use prepared statements. But explicit prepared statements are rarely necessary in pgx v4 because it now has built-in automatic statement preparation and caching.

What you want to do is configure your connection with `statement_cache_mode=describe` (https://godoc.org/github.com/jackc/pgx#ParseConfig) and then use pgx *without* explicit prepared statements.

**Comment by MikhailChe** [comment]
Thank you a lot for your answer. That might help.
