### ISSUE TITLE
not seeing performance increase over sqlx

### ISSUE THREAD

**Issue by mgutz** [jackc/pgx#64]
I created a new SQL builder library [mgutz/dat](https://github.com/mgutz/dat/tree/pgx) and created a pgx runner for it. I hoped it would give a boost over sqlx + lib/pq but the benchmarks say they are nearly identical in performance with sqlx usually coming out ahead. The writeup for the benchmark is in the README

The most relevant part is https://github.com/mgutz/dat/blob/pgx/pgx/runner.go  which is responsible
for executing queries and scanning results. It's nearly identical to the sqlx file of same name. 

Here are the benchmarks for dat + sqlx

```
BenchmarkTransactedDat2    10000                     111526   ns/op  832   B/op  21  allocs/op
BenchmarkTransactedDat4    10000                     115365   ns/op  1232  B/op  26  allocs/op
BenchmarkTransactedDat8    10000                     145685   ns/op  1480  B/op  33  allocs/op
BenchmarkBuildExecSQLDat2  5000                      214377   ns/op  832   B/op  21  allocs/op
BenchmarkBuildExecSQLDat4  5000                      223585   ns/op  1232  B/op  26  allocs/op
BenchmarkBuildExecSQLDat8  5000                      251885   ns/op  1480  B/op  33  allocs/op
BenchmarkExecSQLDat2       5000                      208791   ns/op  280   B/op  10  allocs/op
BenchmarkExecSQLDat4       5000                      209814   ns/op  296   B/op  10  allocs/op
```

Here are the benchmarks for dat + pgx

```
BenchmarkTransactedDat2    10000                     113858   ns/op  1208  B/op  28  allocs/op
BenchmarkTransactedDat4    10000                     117697   ns/op  1608  B/op  33  allocs/op
BenchmarkTransactedDat8    10000                     148228   ns/op  1856  B/op  40  allocs/op
BenchmarkBuildExecSQLDat2  5000                      215328   ns/op  1208  B/op  28  allocs/op
BenchmarkBuildExecSQLDat4  5000                      225971   ns/op  1608  B/op  33  allocs/op
BenchmarkBuildExecSQLDat8  5000                      259791   ns/op  1856  B/op  40  allocs/op
BenchmarkExecSQLDat2       10000                     209085   ns/op  656   B/op  17  allocs/op
BenchmarkExecSQLDat4       5000                      212718   ns/op  672   B/op  17  allocs/op
```

Any suggestions on improving the pgx runner?

**Comment by jackc** [comment]
I forked it and wrote a proof of concept for the TransactedDat benchmarks - https://github.com/jackc/dat/tree/pgx-faster

```
jack@hk-2~/dev/go/src/github.com/mgutz/dat/pgx$ go test -bench=TransactedDat
PASS
BenchmarkPgxNativeTransactedDat2           10000            122289 ns/op
BenchmarkPgxNativeTransactedDat4           10000            115939 ns/op
BenchmarkPgxNativeTransactedDat8           10000            132158 ns/op
BenchmarkTransactedDat2    10000            167553 ns/op
BenchmarkTransactedDat4    10000            155742 ns/op
BenchmarkTransactedDat8    10000            196322 ns/op
ok      github.com/mgutz/dat/pgx        9.299s
```

The difference is using prepared statements instead of client side interpolation. pgx *really* is designed to use with prepared statements.

It looks like dat makes a point of doing client-side parameter interpolation. Let me strongly recommend against that strategy. As you've noticed, you sometimes can be substantially faster for one-off queries by avoiding the extra round trip required by a prepare then execute. But once you get past the first invocation of the the query all subsequent invocations will be faster with prepared statements. In addition, it is at a disadvantage in several every other ways.

First, that means that it must use the text protocol instead of the binary protocol for executing the query. This can have a large performance impact for data types such as numbers, dates, times, and bytea. (Especially is this true for pgx -- it's ability to use the binary protocol for more data types is a significant component of its performance edge over database/sql only adapters).

Second, the server saves resources because it does not have to reparse the query. And it possibly will avoid the planner as well.

Last, and certainly not least, is that is is difficult to get client-side escaping correct. There are a number of edge cases such as if the server is using standard conforming strings or not (this bit me before I moved away from client-side escaping).

If you really want to avoid having to deal with prepared queries in client code, it might be interesting to have a caching layer that automatically prepares queries, saves the prepared statement, and automatically reuses it when possible. At its simplest this is basically a map of string to prepared statement. I considered doing this in pgx, but determined the database driver layer was not a good place for it (there are a few edges, such as changing the search_path which would change the meaning of unprepared queries, but not previously prepared queries). The query building library layer might be a good place for this type functionality.

As another aside, I noticed that the benchmark is using the ```money``` type. Use of this type is discouraged in modern versions of PostgreSQL, consider using another number type.

**Comment by mgutz** [comment]
Most queries are one off. I rarely do batch operations which would take advantage of prepared statements when writing web and mobile apis. Maybe I'm misunderstanding but a prepared statement only lives for the lifetime of a connection, which should be released as quickly as possible back to the pool.

The library specifically checks for standard_conforming_string when the global connection is created and panics if the setting is unsafe. The library does not allow any escaping. User's are not allowed to enter C-like escapes.

**Comment by jackc** [comment]
The way you typically would do prepared queries in pgx is to prepare them in the AfterConnect hook of the connection pool. This ensures that whenever you checkout a connection all the prepared statements are available. (See https://github.com/jackc/tpr/blob/master/backend/pgx_repository.go#L399 for an example. All the operations of an RSS aggregator web app boil down to 21 prepared statements). In database/sql it's even easier, because it's prepared statement abstraction is not bound to an individual connection like it is in pgx, so you can create prepared statements at any time and have them available on all connections.

Also, another thing you may want to benchmark is selecting larger amounts of data instead of benchmarking inserts. That is where the binary protocol will make even more of a difference

**Comment by mgutz** [comment]
Is that practical? Seems like unnecessary processing to prepare all statements on each acquired connection when only a few will be invoked. Wouldn't it make more sense to use stored procedures at that point?

Selects wouldn't be affected too much by client interpolation as all scanning is handled by driver. I will add test for large data inserts.

Thanks for your insights.
