### ISSUE TITLE
4.1.2  Can't query with with PGBouncer?

### ISSUE THREAD

**Issue by relistan** [jackc/pgx#650]
Connecting to PGBouncer, without SSL, and attempting to run any query fails with:

```
ERROR: unsupported pkt type: 80 (SQLSTATE 08P01)
```

I also tried 4.0.0 and it seems that this error is not new. Looks quite similar to #512. I attempted both the `sql.DB` interface and the native `pgx` interface to no avail.

*Versions*:
* PGBouncer 1.11.0
* pgx 4.0.0, 4.1.2

**Comment by jackc** [comment]
There are a few restrictions when using PgBouncer. One is that you cannot use prepared statements. So if you have any explicit prepared statement usage that would be a problem. But also pgx automatically uses prepared statements internally. So that needs to be disabled for pgx to work with pgbouncer.

There are two ways of doing that:

1. Set the statement cache to describe mode (include `statement_cache_mode=describe` in your connection string is the simplest way to set this)
2. Set `PreferSimpleProtocol` to `true` in your pgx.ConnConfig

**Comment by glebwell** [comment]
I tried to use `PreferSimpleProtocol = true`, but it didn't work in postgresql 10. It returns `Database error: unused argument: 0`.
I also tried to set `statement_cache_mode=describe` via connection string. I've done it using `pgx.ParseConnectionString("postgresql://user:user@ip:port/db?statement_cache_mode=describe&sslmode=disable")`. But function returned: `unrecognized configuration parameter "statement_cache_mode" (SQLSTATE 42704)`.
I used pgx version 3.6.0.
@jackc, could you please help me sharing the code showing how to set `statement_cache_mode` parameter?

**Comment by jackc** [comment]
@glebwell `statement_cache_mode` is only needed / supported in `v4`. `PreferSimpleProtocol` _should_ be sufficient in `v3`. 

I don't recognize the error `Database error: unused argument: 0`. Are you using something else besides pgx like an ORM?

**Comment by glebwell** [comment]
@jackc, thanks for quick reply. I figured out that the error `Database error: unused argument: 0` occured because of `sqlx` library. When I made sql requests using only pgx (with `PreferSimpleProtocol true`), the error's gone. Maybe simple protocol affects badly on structure mapping feature of sqlx.
I also tried to set `statement_cache_mode=describe` via connection string like `postgres://user:password@ip:port/db?statement_cache_mode=describe`. And it's been parsed without errors by pgxpool.ParseConfig (pgx v4). Just one question, is it safe to use both settings in the same time:  `statement_cache_mode=describe` and `PreferSimpleProtocol=true`?

**Comment by jackc** [comment]
> is it safe to use both settings in the same time: statement_cache_mode=describe and PreferSimpleProtocol=true

It is safe -- as in nothing should break -- but the functionality is mutually exclusive. The statement cache is only used with the extended protocol. So when `PreferSimpleProtocol=true` the statement cache will not be used. In most cases either one should work fine, but in `v4` `statement_cache_mode=describe` _may_ give better performance in some circumstances.

**Comment by glebwell** [comment]
@jackc, thanks for good explanation.

**Comment by voodoo-dn** [comment]
@jackc We are use PgBouncer with session mode and use **binary_parameters=yes** connection option, because we need to send parameters with prepared statement. But on connect, we received `unrecognized configuration parameter "binary_parameters" (SQLSTATE 42704)`.  Could we use pgbouncer or we need direct connection to Postgres?

**Comment by jackc** [comment]
Is `binary_parameters` a leftover in the connection string from `lib/pq`? That's not a valid PostgreSQL setting and I don't _think_ it is a PgBouncer setting either.

With pgx and PgBouncer you will want to use either `statement_cache_mode=describe` or `PreferSimpleProtocol=true`. Prefer `statement_cache_mode=describe` as long as you aren't doing schema changes while your application is running.

**Comment by mescam** [comment]
> Is `binary_parameters` a leftover in the connection string from `lib/pq`? That's not a valid PostgreSQL setting and I don't _think_ it is a PgBouncer setting either.
> 
> With pgx and PgBouncer you will want to use either `statement_cache_mode=describe` or `PreferSimpleProtocol=true`. Prefer `statement_cache_mode=describe` as long as you aren't doing schema changes while your application is running.

Could you please explain what kind of issues we might encounter during schema changes on live application with describe mode?

**Comment by pavelpatrin** [comment]
Thank you guys for this thread, it helps a lot. I have one more question about v4.

@jackc, why `ParseConfig()` knows nothing about `prefer_simple_protocol` DSN option?

**Comment by jackc** [comment]
> @jackc, why ParseConfig() knows nothing about prefer_simple_protocol DSN option?

No reason. Just never implemented. It's on master now.

**Comment by pavelpatrin** [comment]
@jackc thank you very much!

**Comment by pavelpatrin** [comment]
Error for search engines.

```
FATAL: unrecognized configuration parameter "prefer_simple_protocol" (SQLSTATE 42704)
```

**Comment by relistan** [comment]
@pavelpatrin thanks for that

**Comment by artbred** [comment]
Can someone please explain we why `default_query_exec_mode=cache_describe` doubled the latency? Maybe I am doing something wrong, I am using sqlx on top of pgx

**Comment by CodaBool** [comment]
wasn't super clear to me but this effectively means changing the connection string from 

```
postgres://postgres:PASSWORD@HOST:6543/postgres?statement_cache_mode=describe
```
### into
```
postgres://postgres:PASSWORD@HOST:6543/postgres?default_query_exec_mode=simple_protocol
```

> default_query_exec_mode can be any of these values: "cache_statement", "cache_describe", "describe_exec", "exec", and "simple_protocol"


## Or adding to the query itself
`db.Query(context.Background(), "select stars, description from repo", pgx.QueryExecModeSimpleProtocol)`

**Comment by darkframemaster** [comment]
@jackc Will there still be these restrictions when using pgbouncer now? I have encountered similar errors during use, but they are not stable and reproducible. Most of the time, it works normally, but the same errors will occur every few days, and the time interval is uncertain. The error on the PostgreSQL side seems to be related to SSL. I have provided more information on [StackOverFlow](https://stackoverflow.com/questions/79378045/received-unencrypted-data-after-ssl-request-while-ssl-is-off?noredirect=1#comment139983816_79378045), could you please help confirm if it is the same issue. Thank you in advance.
