### ISSUE TITLE
prepared statements for ConnPool

### ISSUE THREAD

**Issue by alvarolm** [jackc/pgx#68]
why ConnPool doesn't implement prepared statements ?

**Comment by jackc** [comment]
Short answer: it's hard. It's in my long-term plans, but there are a few edges I haven't figured out good solutions for yet.

Unlike database/sql pgx does not try to hide the explicit concept of a connection from the developer. This lower level interface has some advantages, but in this case it can make life more difficult.

For example, for ConnPool to implement prepared statements it would have to guarantee that any connections checked out had that prepared statement available. ConnPool can't prepare the statement on all connections when prepare is called, because some may already be checked out. So it would have to do some work on Acquire or Release to actually send the prepare to PostgreSQL. The same issue occurs on Deallocate.

I don't think there are any unsolvable issues, I just haven't had the chance to tackle them yet.
