### ISSUE TITLE
Should i defer pool.close() a conn pool?

### ISSUE THREAD

**Issue by GAZ082** [jackc/pgx#685]
Hi. From the test cases I see Jack closes the pool in every test. Is this because how the test work and I actually do not need to do it in a program or the pool does not handle the closure of connections automatically? Isnt t his supposed be half the work of a pool, the other half is opening connections on demand?

Thanks!

**Comment by jackc** [comment]
In the case of a program that opens a connection pool at start and uses it until the end you don't technically need to close it. It's kind of like leaving open files when exiting the program. You can rely on the OS to clean up for you. But personally I would consider it better technique to clean up after oneself.

As far as the tests go, we definitely need to clean up explicitly because otherwise the connections from each test would remain open until the test suite concluded. This would likely exhaust the max open connections on the PostgreSQL server.

**Comment by GAZ082** [comment]
Got It. Thanks for replying so fast.
