### ISSUE TITLE
Can not scan to custom types

### ISSUE THREAD

**Issue by samtech09** [jackc/pgx#686]
Hi, trying to scan into customtype, but pgx is giving following error 
`can't scan into dest[2]: unable to assignto datatypes.OnlyTime`

However `pg` is able to scan into that.  Here are full test result

```
TestOnlyTime-pgx ***
--- FAIL: TestOnlyTimePgx (0.03s)
    pgx_test.go:73: Scan failed. can't scan into dest[2]: failed to scan OnlyTime


TestOnlyTime-SQLx ***
tstamp:  17:25:02
FAIL
FAIL    github.com/samtech09/datatypes  0.056s
FAIL
```

Documentation says

> pgx also includes support for custom types implementing the database/sql.Scanner and database/sql/driver.Valuer interfaces. 

I implemented both `sql.Scanner` and `sql.Valuer` but still it cannot scan into that.

Code is here at [github.com/samtech09/datatypes](https://github.com/samtech09/datatypes)

**Comment by jackc** [comment]
Your custom scan function *is* being called. It is returning an error.

https://github.com/samtech09/datatypes/blob/83670198be9b7de3be0d6c8539a24c8d4eb1ff30/onlytime.go#L33

Your Scan function is expecting a `time.Time`.  `pgx` is passing a `string`.

`pq` appears to be incorrectly converting a PostgreSQL `time without time zone` into a Go `time.Time`. This is incorrect because `24:00:00` is a valid PostgreSQL `time without time zone`. But Go `time.Time` will convert this into `00:00:00` on the following day. i.e. Data loss can occur.

For a `Scan` function to work with both `pgx` and `pq` it would need to accept `string` and `time.Time` (and accept the potential data loss with accepting `time.Time` from `pq`).

See https://github.com/jackc/pgtype/blob/55a56add235573da4358e3fd52ad4a35b30c92eb/time.go#L203 for a time type that does this.

**Comment by samtech09** [comment]
Thanks for the explanation @jackc 
Added case to parse from string, now it is working as expected.

Thanks a lot.
