### ISSUE TITLE
Using a custom type with stdlib

### ISSUE THREAD

**Issue by tschaub** [jackc/pgx#689]
I was encouraged to see that I could easily implement a custom `Geometry` type that implements the `pgtype.BinaryDecoder` and `pgtype.BinaryEncoder` interfaces.  I was uncertain how to properly "register" this type, but it looks like this works when I have a `*pgx.Conn`:

```go
	conn.ConnInfo().RegisterDataType(pgtype.DataType{
		Value: &Geometry{},
		Name:  "geometry",
		OID:   17976,
	})
```

My next challenge is to get things working with packages that expect an interface closer to `database/sql.DB`.  I thought I might be able to get what I need with the `stdlib` package by registering my type after connecting with `OptionAfterConnect`:

```go
	afterConnect := pgxstdlib.OptionAfterConnect(func(ctx context.Context, conn *pgx.Conn) error {
		conn.ConnInfo().RegisterDataType(pgtype.DataType{
			Value: &Geometry{},
			Name:  "geometry",
			OID:   17976,
		})
		return nil
	})

	db := pgxstdlib.OpenDB(*config, afterConnect)
```

However, it doesn't look like my decoder is getting called when I try to scan a row into a `Geometry` struct:

```go
	row := db.QueryRow("select 'POINT(0 0)'::geometry as geometry")
	point := &Geometry{}
	log.Fatal(row.Scan(point))
```

This fails with `sql: Scan error on column index 0, name "geometry": unsupported Scan, storing driver.Value type string into type *Geometry`.

The same succeeds with `conn.QueryRow(ctx, query).Scan(point)`.  But this doesn't feel like an option to me since I'm using [a package](https://github.com/kyleconroy/sqlc) that expects to work with an interface like this:

```go
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}
```

Thanks for this great package.

**Comment by jackc** [comment]
Sadly, most of the `pgtype` functionality is not directly accessible when accessed through the standard `database/sql` interface. You'll need to implement `Scan` and `Value`. Fortunately, they can be implemented in terms of the pgtype interfaces. See https://github.com/jackc/pgtype/blob/9e700ff067212a8c0d4a2020825a219f045b7571/line.go#L128 for an example.

**Comment by tschaub** [comment]
Thanks for the reply, @jackc.  I was hoping to make use of the binary encoding/decoding.  As with the [`Line` example](https://github.com/jackc/pgtype/blob/9e700ff067212a8c0d4a2020825a219f045b7571/line.go#L128), I've found that I'm forced to use text results when I implement my own scanner.  I was hoping to make use of the result and param formats that are set by `conn.ExecParams`.

Do you think there is any way to use `pgx` to implement an interface like the `DBTX` one above and use binary results/params?

**Comment by jackc** [comment]
Having to work with the `database/sql.Scanner` interface makes things difficult.

The format is chosen when the query is sent, but we only know the type that it will be scanned into when reading the results (i.e. when it's to late to change anything). This is handled in non-database/sql pgx by registering data types and by optional arguments to Query/QueryRow/Exec that control the format. It's also made simpler because pgtype implements both formats for all types (with the exception of a few types that PostgreSQL only implements one format or the other in a useful manner).

Second, the database/sql Scan interface doesn't reveal whether whether the scanner is expecting the text or binary format. pgx handles this by having separate methods to decode the text and binary formats.

`pgx/stdlib` uses a whitelist of types that it definitely can handle with the binary format and forces everything else to text. This helps ensure that Scanners that work with `lib/pq` also work with `pgx`.

I suppose something to register types in the stdlib as binary capable would be possible. Then the Scan function would be passed a `[]byte` instead of a `string`.

**Comment by tschaub** [comment]
@jackc - curious to hear your thoughts on this approach: https://github.com/tschaub/pgx/commit/ed9c65f89cf4b757a9cb1c1080fde69104dba322

With that change, it looks like I can register my own type that implements these interfaces:
 * `pgtype.BinaryEncoder`
 * `pgtype.BinaryDecoder`
 * `pgtype.Value`
 * `sql.Scanner`
 * `driver.Valuer`

Then I can do:
```go
	pgxstdlib.RegisterDataType(pgtype.DataType{
		Name:  "geometry",
		OID:   17976,
		Value: &geo.Geometry{},
	})
```

And then issue queries like the one above with the standard `database/sql.DB`.

It looks like there is an extra decode/encode trip.  For example, the `row.Scan` in the code below results in calls to `point.DecodeBinary`, `point.EncodeBinary`, and then `point.DecodeBinary` again.

```go
	row := db.QueryRow("select 'POINT(2 5)'::geometry")
	
	point := &geo.Geometry{}
	row.Scan(point)
```
I only expected one call to `point.DecodeBinary` above.  But maybe this is necessary.

If you think this is a decent approach, I could take a stab at writing tests.  Also open to other suggestions.

**Comment by tschaub** [comment]
I notice that in some cases I also have to use `OptionAfterConnect` to register my custom type after connect.  Ideally this could be handled with one call to register the type.

**Comment by jackc** [comment]
I'd be concerned that introducing a reflect into every value that is scanned would have a significant negative performance impact -- though we'd need a benchmark to tell for sure.

Also, that extra decode and encode would probably negate the performance advantage of using the binary format. Definitely need to get rid of that.

I think a slightly different approach would improve on this. The whole idea of registering a data type in pgx is to support to two features.

1. `Rows.Values()` -- this gets values without scanning so pgx needs to have a default type. This isn't applicable to `database/sql`.
2. Scanning into native types like `int32` and `string` since we can't add methods to them. `database/sql` handles this itself.

All we really need is to signal to pgx to use the binary format. I would picture a stdlib registration that only took an OID to mark as okay for binary. Then in `stdlib.Rows.Next()` we would check in the default branch for that flag. If yes we use `pgtype.GenericBinary` instead of `pgtype.GenericText`.

**Comment by tschaub** [comment]
@jackc - I tried to reuse the existing `databaseSQLResultFormats` lookup in https://github.com/tschaub/pgx/commit/84bae73bac069b696576b1ff5bd92ce95a36d2ca.  This works for scanning a row from a simple query without any parameters.

For example, with the change above, if `*Geometry` implements `sql.Scanner`, this now works:

```go
	stdlib.RegisterBinaryType(17976)

	query := "select 'POINT(1 2)'::geometry as geometry"
	row := db.QueryRow(query)

	result := &Geometry{}
	if err := row.Scan(result); err != nil
		log.Fatal(err)
	}

	fmt.Printf("result: %#v\n", result)
}
```

However, if I try to pass a parameter that needs to be encoded, I get an error.  For example, if `*Geometry` implements `driver.Valuer`, I get `Cannot encode []uint8 into oid 17976 - []uint8 must implement Encoder or be converted to a string`:

```go
	query := "select $1::geometry as geometry"
	point := &Geometry{orb.Point{1, 2}}
	row := db.QueryRow(query, point)

	result := &Geometry{}

	if err := row.Scan(result); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("result: %#v\n", result)
```

This happens because my `Value` function is called by sql's `db.QueryRow` and then pgx tries to encode it again in [`extendedQueryBuilder.AppendParam`](https://github.com/jackc/pgx/blob/576f99a35e6fbaee12c601d0c09ab0f1eac46836/extended_query_builder.go#L20).

If https://github.com/tschaub/pgx/commit/84bae73bac069b696576b1ff5bd92ce95a36d2ca looks like it is going in the right direction, two remaining issues are that:
 * [`chooseParameterFormatCode`](https://github.com/jackc/pgx/blob/576f99a35e6fbaee12c601d0c09ab0f1eac46836/values.go#L212-L221) returns 0 because it is passed my already encoded `[]uint8` and doesn't know about the `oid`, and
 * [`eqb.encodeExtendedParamValue`](https://github.com/jackc/pgx/blob/576f99a35e6fbaee12c601d0c09ab0f1eac46836/extended_query_builder.go#L65) tries to re-encode my already encoded value.

**Comment by jackc** [comment]
I think this is going the correct direction. Though now I worry a bit about `databaseSQLResultFormats` being global and mutable via `RegisterBinaryType`. Depending on usage I could see a race condition existing there. It would be nice if it was per `database/sql.DB`. But it might be difficult to fight through the interposing `database/sql` layer to establish that mapping.

For encoding, I think the solution would be for `Value` to return self instead of doing any encoding. Then when it got to native pgx it would use EncodeBinary directly. And `Scan` would probably be a similar delegation to `DecodeText` or `DecodeBinary`.

Of course this means these types are only usable with pgx (which implies the question of maybe using the native pgx interface directly...).

**Comment by tschaub** [comment]
@bfontaine - for clarification, has there been any change related to this issue?  I understand if the issue is old and will not be supported.  Just wanting to check if there were any changes related to binary encoding/decoding.

We are running on a fork of pgx and would like to come back to this package if things have changed.

**Comment by bfontaine** [comment]
@tschaub To be honest I don’t know, I just assumed from @jackc’s comments above that it didn’t make sense to keep this issue open. Feel free to reopen it if you think it’s a mistake.

**Comment by jackc** [comment]
There have been some small changes in v5 toward binary support with database/sql and custom types. And lib/pq compatibility is no longer an issue.

As far as a planned feature goes, it's not planned in that I don't know of anyone planning on working on it. But it's not rejected either. If someone wants to tackle it and can figure out a way to do it without the issues the above attempts encountered I think it would be worth having in pgx.
