### ISSUE TITLE
Allow NullTime to encode into timestamp without time zone (oid 1114)

### ISSUE THREAD

**Issue by silviucm** [jackc/pgx#69]
Hi Jack,

Great project. I really appreciate your efforts to provide a fast way of communicating with Postgresql.

This is just a minor issue. For nullable "timestamp without timezone" data types I can't seem to be able to use pgx.NullTime to insert data (getting a NullTime.Encode cannot encode into OID 1114).

Without looking too much it may go down to a too restrictive of a condition  condition in values.go, the Encode method associated with NullTime (I don't know the actual Postgresql data type implications).

I can certainly use "timestamp with timezone" instead, if too much of a hassle. 

(I can play a bit with it in my own fork of your project but just wanted to bring this to your attention).

Regards
Silviu

**Comment by jackc** [comment]
I would strongly suggest using timestamp with time zone -- there are rarely situations where not having the time zone is preferable. 

That said, since PostgreSQL does support it, it makes sense for pgx to as well. Added support for timestamp in fc484ab5fdcc41ba5b9eb42901d1c7276e129901.

Also added binary encoding for timestamp as well -- should give a performance improvement.
