### ISSUE TITLE
having trouble installing -->  invalid version: go.mod has post-v0 module path "github.com/jackc/pgx/v4" at revision 576f99a35e6f

### ISSUE THREAD

**Issue by ORESoftware** [jackc/pgx#691]
I am getting this:

```bash
go: finding github.com/jackc/pgx 576f99a35e6fbaee12c601d0c09ab0f1eac46836
go get github.com/jackc/pgx@576f99a35e6fbaee12c601d0c09ab0f1eac46836: github.com/jackc/pgx@v0.0.0-20200307193217-576f99a35e6f: invalid version: go.mod has post-v0 module path "github.com/jackc/pgx/v4" at revision 576f99a35e6f
```

the error is:

> invalid version: go.mod has post-v0 module path "github.com/jackc/pgx/v4" at revision 576f99a35e6f

**Comment by jackc** [comment]
Somehow you have an import path that is for the pre-modules `github.com/jackc/pgx` but the specific commit you are requesting is the latest `v4` modules version. You need to use `github.com/jackc/pgx/v4` as the import path.

**Comment by AddictArts** [comment]
+1

```
go get github.com/jackc/pgx/v4
```

Doesn't work, yes I found an issue that said something about modules, but there isn't info on how to install the module.

**Comment by jackc** [comment]
You shouldn't need to use go get or install it manually. It should automatically install when you reference it. Here's an example.

```
jack@glados ~/dev » mkdir example
jack@glados ~/dev » cd example
jack@glados ~/dev/example » go mod init example.com/your/pkg/path/example
go: creating new go.mod: module example.com/your/pkg/path/example
jack@glados ~/dev/example » cat > main.go
package main

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v4"
)

func main() {
	conn, err := pgx.Connect(context.Background(), "")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer conn.Close(context.Background())

	var n int
	err = conn.QueryRow(context.Background(), "select 42").Scan(&n)
	if err != nil {
		fmt.Printf("QueryRow failed: %v\n", err)
		return
	}

	fmt.Println(n)
}
jack@glados ~/dev/example » go run main.go
go: finding module for package github.com/jackc/pgx/v4
go: found github.com/jackc/pgx/v4 in github.com/jackc/pgx/v4 v4.5.0
42
jack@glados ~/dev/example »
```

**Comment by AddictArts** [comment]
Thanks @jackc 

The issue for someone new is this line right here, or it was for me.

`go mod init example.com/your/pkg/path/example`

I don't own example.com, or have a website / server there. It makes a newbee think they need a github.com repo or some server at some dot com address. In fact almost all examples when you Google make this assumption. It really made me question golang. That is not pgx's issue. But wow, I thought all modules needed to be hosted at some URL and you couldn't do local dev.

Now I have since learned that you can do

```sh
go mod init
# or
go mod init example
```

I don't completly know the difference with `go mod init` and no name or the second. I used the second. I also had working project and once I did the `go mod init ...` it broke my local packages that were working using `import "./mypackage"`.

I have also seen `GO11DISABLEMOD` env or something close to that with a `go get`. Yet another way, which would be nice to acknowledge in the README for newbees. Either say don't use it or you can.

**Comment by AddictArts** [comment]
For me this issue is resolved and pgx is really good and greatly appreciated. Thanks for taking the time to give an example and for considering my comments.

**Comment by jackc** [comment]
As you discovered, your first experiences with modules can be frustrating. I didn't even know about running `go mod init` without the package name. I think it might be for creating projects in the `GOPATH`. I always use `go mod init packagename`.

> it broke my local packages that were working using import "./mypackage"

Relative imports basically aren't a thing in Go. I'm surprised it worked even before using modules.

I would like to make it easier for new users, but I'm not really sure what would be a good explanation. https://github.com/golang/go/wiki/Modules#quick-start is probably the canonical introduction. But it has the same issue you mentioned that it doesn't make clear that the module name is just an arbitrary URL that doesn't even have to exist. And its also part of a giant page with an overwhelming amount of details.
