### ISSUE TITLE
Postgres Microsecond accuracy vs golang nanosecond accuracy

### ISSUE THREAD

**Issue by anicoll** [jackc/pgx#699]
Currently Postgres only supports microsecond accuracy
https://www.postgresql.org/docs/current/datatype-datetime.html

The pgx library uses `time.Format` to format a timestamp which is to accurate for Postgres and this behaviour is undefined in Postgres documentation.

The proposed solution would be to truncate (NOT ROUND) the time just before it gets sanitized for postgres insert in order to be as accurate as possible.

**The current issue with over accurate data in Postgres**
---
`postgres-database=# select '2021-03-21T23:59:59.9999999Z'::timestamptz;
      timestamptz
------------------------
 2021-03-22 00:00:00+00`

**The proposed solution**
---
`postgres-database=# select '2021-03-21T23:59:59.999999Z'::timestamptz;
          timestamptz
-------------------------------
 2021-03-21 23:59:59.999999+00`

**Comment by anicoll** [comment]
Pull request
https://github.com/jackc/pgx/pull/700

**Comment by heedson** [comment]
The example that we ran into was with https://github.com/jinzhu/now and using the `EndOfDay()` of a time. It would give the exact moment before the end of a day.

Inserting that into postgres, then reading it back out (with the rounding on insert), then the output will claim it was `00:00:00...` of the next day - not the same day.

**Comment by jackc** [comment]
Merged #700 

I'm guessing you are using the simple protocol since you changed the sanitization code. I checked the normal encoding path for `pgtype.Timestamp` and `pgtype.Timestamptz` and found that the binary format was effectively truncating while the text format was exhibiting the rounding behavior. This is now resolved in https://github.com/jackc/pgtype/commit/523cdad66f0568602919000c3ef92b0746cc2d03.
