### ISSUE TITLE
Check error on tx.Rollback

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#719]
Is it safe to just call tx.Rollback() as you showed in this [example](https://godoc.org/github.com/jackc/pgx#hdr-Transactions) And don't check the error that it can return?

**Comment by jackc** [comment]
Yes.

If the entire block of code is successful the `tx.Rollback()` is a no-op.

If an error did occur somewhere in the block of code then the original underlying error is returned.

**Comment by georgysavva** [comment]
So if transaction failed `.Rollback()` returns exactly the same error as the operation that failed and we don't need to handle the error it twice. It transaction was successful `.Rollback()` returns nil, since it doesn't do anything. right?

**Comment by jackc** [comment]
Not exactly.

If transaction was successful `tx.Rollback()` returns `ErrTxClosed` -- but that can be safely ignored on the success path.

If the transaction was not committed then the defer is either executing during a panic or an error was already returned.

If it was a panic there is nothing we can do if the Rollback fails. If we are already returning an error then that original error should be returned instead of any failure of the rollback.

In any case, there is no behavior change that can / should be made if that rollback fails. The only thing that possibly would make sense is to log the situation.

**Comment by georgysavva** [comment]
Yeah exactly, the only thing that we could possible do on `tx.Rollback()` error is to log it. And the question is: should we log the `tx.Rollback()` error? (if any, and not the `ErrTxClosed`) Or it usually redundant and don't contain any helpful information?

**Comment by jackc** [comment]
Personally, I don't bother with it. Something else had to have already gone wrong to get there.

**Comment by georgysavva** [comment]
Got it. Thanks! Closing the issue.
