### ISSUE TITLE
Pass transaction options into Batch

### ISSUE THREAD

**Issue by apechimp** [jackc/pgx#722]
I'm migrating from v3 to v4 and I'm running a batch in a read only transaction. In v3, `Batch.Send` accepted `TxOptions` which could be used to set the transaction the batch runs in as read only. In v4, I don't appear to be able to either set `TxOptions` on a `Batch` or to pass in `TxOptions` to `pgxpool.Pool.SendBatch`. Was this omission intentional in the v4 API change? Would you accept a pull request that'd allow for setting `TxOptions` on a `Batch`?

**Comment by jackc** [comment]
It was intentional, though the impact on your use case was unforeseen.

In `v3`, batches were explicitly wrapped in `begin` and `commit`. But in most cases, that was superfluous. In the extended protocol there an implicit transaction around grouped queries. So in `v4`, the explicit transaction was removed as unnecessary. Also, it is unclear how that would interact with `v4`'s feature of simulating nested transactions with savepoints.

Unfortunately, that does remove the ability to set a transaction options directly on a batch execution. However, there are still two (slightly less convenient) ways to do what you want.

1. Begin a transaction and call `SendBatch` on that transaction. This will incur an extra round trip for the `begin` and for the `commit`, but presumably if you are going to the effort of using batched queries you have enough of them that the effect of `begin` and `commit` would be nominal.
2. There is nothing to prevent you from directly using `Batch.Queue` to execute transaction control SQL. Add `begin` and `commit` statements to your `Batch`. This would save the two round trips for transaction control.

**Comment by apechimp** [comment]
Thanks for the work-around ideas. Those are fine for me.
