### ISSUE TITLE
Should uninitalizated map translate to "null" or nil?

### ISSUE THREAD

**Issue by Streppel** [jackc/pgx#726]
Given table 

```sql
CREATE TABLE test (
    id serial PRIMARY KEY,  
    myjson jsonb NOT NULL
);
```

when we do
```go
db, _ := sql.Open("postgres", "pg addr")
var args map[string]interface{}
_, err = db.Exec(`INSERT INTO test (myjson) values ($1)`, args)
```

the following row is added to the database

```
 id |                  myjson                  
----+------------------------------------------
  1 | null
```

Passing nil throws returns an not-null constraint violation error. So does  passing an uninitializated pointer to struct. But an uninitializated map ends up being translated to the string "null".

The same operation using ```"github.com/lib/pq"``` returns an error

```sql: converting argument $1 type: unsupported type map[string]interface {}, a map```

Is this expected behavior?

---

I've tracked down the place where I believe the distinction between an uninitialized pointer to struct and a uninitialized map happens. ```argIsPtr``` is false at this point.

https://github.com/jackc/pgx/blob/e92a2daef2bb20aa743cf384a20df9c5a8dac34a/extended_query_builder.go#L73

**Comment by jackc** [comment]
The problem is there are multiple ambiguous or overlapping concepts and behaviors.

1. One ambiguity is between SQL `NULL` and JSON `null`. They are not the same thing. `null` is valid JSON value. 
2. There is further ambiguity on the Go side due to the distinction between an entirely `nil` interface and a typed `nil` interface.
3. pgx automatically converts to and from a `nil` pointer and SQL `NULL`. pgx also automatically uses `json.Marshal()` and `json.Unmarshal()` to convert from any Go value to SQL `json(b)`. 

Ultimately, what is happening it the `nil` `map[string]interface{}` is being passed to `json.Marshal()` and the JSON `null` is returned.

`encodeExtendedParamValue()` could be changed to also consider a `nil` map as a SQL `NULL`, but I'm not sure if that would have any side effects.

**Comment by Streppel** [comment]
@jackc Thanks for taking the time to reply. Changing this behavior may be more trouble than what it's worth as this is not strictly incorrect behavior, and working on ambiguities is no good. I believe we can close this issue, then.
