### ISSUE TITLE
Get RowsAffected and last id of insert

### ISSUE THREAD

**Issue by lpvm** [jackc/pgx#727]
For a function like:

```
func (dbm *DbModel) insertCategory(conn *pgx.Conn, c Category) (lastID int64) {
	debug("insertCategory")
	timeNow := time.Now().UTC().Format(time.RFC3339)
	c.InsertTs, c.UpdateTs = timeNow, timeNow
	params := []interface{}{c.Code, c.Description, c.InsertTs, c.UpdateTs}
	commandTag, err := conn.Exec(context.Background(),
		"INSERT INTO categories (code, description, insertTs, updateTs) VALUES ($1, $2, $3, $4) RETURNING id;",
		params...)
	checkError(err)
	log.Printf("Insert category: ID = %d\n", lastID)
	log.Println("insertCategory rows affeted: ", commandTag.RowsAffected())
}
```
lastID could be obtained adding `.Scan(&lastID)` to the end of the `conn.Exec` command, but it generates an error.
How to return `commandTag.RowsAffected()` and also lastID?

**Comment by jackc** [comment]
You need a `returning` clause on your insert statement. That causes it to return a result set. That also means you would use `Query()` or `QueryRow()` instead of `Exec()`. The number of rows returned would tell you how many rows were affected, but the command tag is also available on the `Rows` interface returned from `Query()`.

**Comment by lpvm** [comment]
Thank you
