### ISSUE TITLE
ColumnType.DatabaseTypeName() is empty for "time with time zone" column

### ISSUE THREAD

**Issue by germm** [jackc/pgx#759]
When quering a database column with type "time with time zone", the result's ColumnType.DatabaseTypeName() is empty.

I created a Table with the following columns and inserted a record:
```
CREATE TABLE postgres_types(
  c13_time time without time zone,
  c14_timetz time with time zone
);

INSERT INTO postgres_types VALUES(
  now(),now()
);
```
If I execute a `select * from postgres_types` and try to read the ColumnType from the returned rows, then 

- `columnTypes[0].DatabaseTypeName()` returns `"TIME"`

- `columnTypes[1].DatabaseTypeName() `returns `""`

IMHO, the DatabaseTypeName for "time with time zone" should also be "TIME"

Best Regards

**Comment by jackc** [comment]
In the PostgreSQL wire protocol the response types are returned as OIDs instead of names. So pgx can only return the name for types that it specifically knows how to handle.

At the moment pgx / pgtype doesn't have explicit handling for the `time with time zone` type so it is treated as unknown text. I suppose it might make sense to return the OID instead of an empty string for an unknown type.

It's possible to add support, but given that the PostgreSQL docs discourage using that type I've never been motivated enough to do so.

From https://www.postgresql.org/docs/current/datatype-datetime.html#id-1.5.7.13.20.2

> We do not recommend using the type time with time zone (though it is supported by PostgreSQL for legacy applications and for compliance with the SQL standard).

**Comment by germm** [comment]
Many thanks for your reply. It would be helpful if pgx / pgtype would return the OID instead of an empty string if the type is unknown.

**Comment by jackc** [comment]
The OID is now returned for unknown types.
