### ISSUE TITLE
Question about rows.Values()

### ISSUE THREAD

**Issue by braindev** [jackc/pgx#765]
This is slightly related to #417 since I'm attempting to serialize row data from queries where I don't know before hand the fields and types.

I have a table with this schema:

```
                     Table "public.t1"
 Column │  Type  │ Collation │ Nullable │      Default
════════╪════════╪═══════════╪══════════╪═══════════════════
 id     │ uuid   │           │ not null │ gen_random_uuid()
 tags   │ text[] │           │          │
Indexes:
    "t1_pkey" PRIMARY KEY, btree (id)
```

The table has the follow values (¤ is null):

```
# select * from t1;
                  id                  │ tags
══════════════════════════════════════╪═══════
 7d77d033-1511-4148-9adf-68c97f2a2214 │ ¤
 10d36355-eca5-47c2-9b43-c65685cb6416 │ {}
 139bc46d-68d5-4aad-8481-31ca5e96ef8a │ {a,b}
```

Now I have the following code:

```go
	rows, err := db.Query(ctx, "select * from t1")
	if err != nil {
		panic(err)
	}
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			panic(err)
		}
		fmt.Printf("%#v\n", vals)
	}
```

I get the following output

```
[]interface {}{[16]uint8{0x7d, 0x77, 0xd0, 0x33, 0x15, 0x11, 0x41, 0x48, 0x9a, 0xdf, 0x68, 0xc9, 0x7f, 0x2a, 0x22, 0x14}, inte
rface {}(nil)}
[]interface {}{[16]uint8{0x10, 0xd3, 0x63, 0x55, 0xec, 0xa5, 0x47, 0xc2, 0x9b, 0x43, 0xc6, 0x56, 0x85, 0xcb, 0x64, 0x16}, pgty
pe.TextArray{Elements:[]pgtype.Text(nil), Dimensions:[]pgtype.ArrayDimension(nil), Status:0x2}}
[]interface {}{[16]uint8{0x13, 0x9b, 0xc4, 0x6d, 0x68, 0xd5, 0x4a, 0xad, 0x84, 0x81, 0x31, 0xca, 0x5e, 0x96, 0xef, 0x8a}, pgty
pe.TextArray{Elements:[]pgtype.Text{pgtype.Text{String:"a", Status:0x2}, pgtype.Text{String:"b", Status:0x2}}, Dimensions:[]pg
type.ArrayDimension{pgtype.ArrayDimension{Length:2, LowerBound:1}}, Status:0x2}}
```

- Is it to be expected that a field of type `uuid` would be returned as the type `[16]uint8` as opposed to `pgtype.UUID`?
- I can see that an field of the postgresql type `[]text` is returned as `interface {}(nil)` when null and `pgtype.TextArray{Elements:[]pgtype.Text(nil), Dimensions:[]pgtype.ArrayDimension(nil), Status:0x2}}` when the text array is empty.  Is that to be expected?  I thought a null value for the text array might be represented as `pgtype.TextArray{Elements:[]pgtype.Text(nil), Dimensions:[]pgtype.ArrayDimension(nil), Status:0x2}}` and an empty text array might be `pgtype.TextArray{Elements:[]pgtype.Text{}, Dimensions:[]pgtype.ArrayDimension(nil), Status:0x2}}`

There's probably some good reasons for `rows.Values()` to return those two types the way it does but I thought I'd ask about it just in case.

Thank you for your wonderful library.

**Comment by jackc** [comment]
`Values()` will return the result of of calling `Get()` on the registered `pgtype.Value` that corresponds with the type returned from the server.

`Get()` returns the simplest and most meaningful representation of the value. In the case of a database `null` a Go `nil` is the simplest representation.

Arrays are a little trickier in that the array elements could have been `null`.

Go does not have a standard library UUID type. So pgx represents them as `[16]byte` by default. See https://github.com/jackc/pgx/wiki/UUID-Support for instructions on how to use a 3rd party UUID package. 

In general, the goal of `Values()` is to give a best effort of meaningful values. However, if you are using `Values()` instead of `Scan` that presumably means that you don't know how many columns are what type of values to expect. That means you are unlikely to do any processing on the results other than displaying / outputing them in some manner. In this case you may want to consider using a `QueryResultFormats` format argument to your query to request the results in the text format. Then you could use `RawValues()` to get the text data (and convert them to `string` if necessary).

**Comment by braindev** [comment]
Thanks for the explanation.  That makes sense.
