### ISSUE TITLE
context as a parameter in Log() for v3

### ISSUE THREAD

**Issue by chichunhua** [jackc/pgx#772]
I saw `context` is used as a parameter in` Log()` and `pgxPool` for v4, is it possible for ` Log()` and `connPool` in v3 too?

It will be very helpful.

**Comment by jackc** [comment]
Unfortunately, that would be a breaking change. Adding those features was one of the reasons that a major version bump was necessary.

**Comment by chichunhua** [comment]
I see. Thanks for your reply soon. May I ask one more thing, is there any specific reason to change connPool in v4?

**Comment by jackc** [comment]
You mean why was `v3` `ConnPool` replaced with `pgxpool.Pool` in `v4`? It was to decouple connections and the connection pool. In `v3` it was nearly impossible for someone to replace the connection pool because of dependencies between `Conn` and `ConnPool`. In `v4` it is possible. This opens the door different pool types that have application specific retry logic on network failure, load balancing between read replicas, and other less common functionality.
