### ISSUE TITLE
Connection closed after unsuccessful transaction

### ISSUE THREAD

**Issue by wozuo** [jackc/pgx#780]
Hi everyone, great project!

I stumbled upon a problem when executing multiple transactions concurrently. Once in a while I get an error when I commit the transaction with the message: `could not serialize access due to read/write dependencies among transactions`. This is not a problem, since I'm just going to rollback and retry this transaction until it succeeds. But it seems PGX closes the connection. Is this intended behavior? Because sometimes I get this same error on SendBatch() and then calling Close() on the result and there it doesn't close the connection and I can try again with the same one without problems.

Best regards
Marc

**Comment by jackc** [comment]
That was not intended.

Some error types are sometimes recoverable and sometimes unrecoverable (e.g. timeouts can be recoverable or fatal depending on exactly when they occur). pgx has a philosophy of always closing the connection when encountering these errors rather than attempt a tricky recovery process.

In this case that logic was a bit overaggressive. Should be fixed now.

**Comment by wozuo** [comment]
Hey @jackc this is great, thanks a lot for the quick fix!
