### ISSUE TITLE
library to extend pgx scanning abilities

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#788]
Hi. I think pgx is amazing, I like working with it directly without `database/sql` middleman. It provides great features and performance.
 
One thing that I thought can be added to pgx is the ability to scan data from rows into Go structs. 
It's really convenient and allows developers to not bother with rows iteration/closing. Such thing already exists for `database/sql` and it's pretty popular: [sqlx](https://github.com/jmoiron/sqlx) 

I decided to implement similar functionality for pgx and created this library: https://github.com/georgysavva/scany.
Essentially it just accepts `pgx.Rows` and uses reflection to scan into the right struct fields. 
Here is an example of how it works:
```go
	type User struct {
		UserID string
		Name   string
		Email  string
		Age    int
	}
	db, _ := pgxpool.Connect(ctx, "example-connection-url")
	// Use Query to query multiple records.
	var users []*User
	pgxscan.Query(ctx, &users, db, `SELECT user_id, name, email, age FROM users`)
	// users variable now contains data from all rows.
```
It's very flexible and feature-rich, well tested and documented. I think most of pgx users will benefit from this library. 

I am happy to hear any feedback from you about this. If you like it, I would kindly ask you if it's possible to mention this library somewhere in pgx readme, so potential pgx users would know that such a library exists and could reach it. Thank you!

BTW, During the development, I realized that it's quite easy to make it work not only with pgx, but also with `database/sql` to become a competitor to `sqlx`. So I introduced 3 packages: 

1. `pgxscan` - to work with pgx
2. `sqlscan` - to work with database/sql
3. `dbscan` - to work with abstract rows and make it possible to use `scany` with any database library.  Both `pgxscan` and `sqlscan` are just thin adapters for `dbscan`.

**Comment by jackc** [comment]
> I am happy to hear any feedback from you about this.

Looks good to me. The lack of something like this has been one of the biggest downsides to using the pgx native interface. It'll be nice to have something like this.

>  If you like it, I would kindly ask you if it's possible to mention this library somewhere in pgx readme, so potential pgx users would know that such a library exists and could reach it.

Done. I used the "About" line from your repo is that description. Make a PR if you want the description reworded.

I'm not sure if you want to go beyond scanning to general utility functions but if so you might want to check out https://pkg.go.dev/github.com/jackc/pgxutil?tab=doc. It's my personal helper library for pgx. I haven't promoted it because I don't want to take on any more open source responsibilities at the moment. But there are a lot of little helpers that I use a lot. Feel free to take any (or none) of them as you see fit.

**Comment by georgysavva** [comment]
Thank you! The wording is perfect. I will check the util package you referenced.
