### ISSUE TITLE
Timezone inconsistent with connection string parameter

### ISSUE THREAD

**Issue by adam-debkowski** [jackc/pgx#789]
### Version
`jackc/pgx` - v4.7.1
`golang` - go version go1.14.4 linux/amd64

### What is wrong
So I'm having an issue after migrating from `lib/pq` to `jackc/pgx`. Even though I set the desired timezone via `timezone` connection string parameter while connecting to my local Postgres instance, all of the values read from `timestamp with time zone` column come with local timezone.

Example: 
After connecting with `timezone=UTC` I read timezone from the database with

```
	var timezone string
	err = db.QueryRow("SHOW timezone").Scan(&timezone)
	if err != nil {
		panic(err)
	}

	fmt.Println(timezone) //UTC

```

Then when I query for a column with a type `timestamp with time zone`:
```
	rows, err := db.Query("select time_column from my_table")
	if err != nil {
		panic(err)
	}

	for rows.Next() {
		var (
			inBytes    []byte // just to make sure i get data directly from Postgres
		)

		err = rows.Scan(&inBytes)
		if err != nil {
			panic(err)
		}

		fmt.Println(string(inBytes)) // 2020-06-01T17:00:00+02:00
	}

```

I got a time in the CEST timezone, which is my local one.

In the meantime, I connect to the database with the use of psql, set the proper timezone, and execute:

```
show timezone;
-- TimeZone 
------------
-- UTC
--(1 row)

select time_column from my_table;
--       time_column       
--------------------------
-- 2020-06-01 15:00:00+00
--(1 row)
```

Which is an expected representation of time based on the configured timezone.

### What I expected

I expect the time read from the database to be returned in the timezone configured for my session with the database. Instead, I get time in my local timezone. 

The problem is solved when I add an env variable before running my tests: `TZ=UTC`, which sets default timezone for variables initialized without a timezone (like for `time.Now()`). I expected this to not be required, since clearly postgres can return time in the proper timezone.

Also, this problem did not occur while using `lib/pq`. Time was always returned in the timezone set for database session.

**Comment by jackc** [comment]
I can see why that would be confusing.

The primary reason for this is the pgx uses the binary format for timestamptz by default. This binary format is simply the offset in μs from `2000-01-01 00:00:00 UTC`. i.e. The session time zone has no effect and is not included.

But even if using the text format it is a somewhat lossy operation. An actual location / time zone cannot be determined by just a offset from UTC (e.g. `+02:00`). `time.Parse()` synthesizes a location / time zone in this case. That means that if you were to perform a `(*time.Time).Add()` that crossed a daylight savings time change the operation would be incorrect.

IMO, the correct place to convert times to the time zone desired by the application is in the application, not the driver or database server.

But even if these problems were to be overcome, I would be very reluctant to change the default behavior and risk breaking any code relying on the current behavior.

However, the pgx type system is completely pluggable. If this behavior is vital to you `pgtype.Timestamptz` can be replaced as the default `timestamptz` handler with your own handler.

**Comment by adam-debkowski** [comment]
I'm not well into the database drivers so I'd like to understand the problem better. AFAIK Postgres allows specifying a timezone parameter in order for it to return the stored timestamp in a proper timezone, which seems to be the preferred way for the user to get the timezone he wants. How do the pgx works then if it ignores it? Does it not use the timezone parameter from connection string while opening the connection with the database (which would result in Postgres returning timestamp in proper timezone)? Or is it a Postgres thing, that it returns timestamp in UTC no matter what, and it is on the user side to properly format the timestamp using provided timezone setting (which pgx just skips)?

**Comment by jackc** [comment]
> AFAIK Postgres allows specifying a timezone parameter in order for it to return the stored timestamp in a proper timezone, which seems to be the preferred way for the user to get the timezone he wants.

I have rarely used the PostgreSQL session time zone in application development. When you have users in multiple time zones you have to do the conversion application side anyway.

> Does it not use the timezone parameter from connection string while opening the connection with the database

pgx does send the parameter. But...

> Or is it a Postgres thing, that it returns timestamp in UTC no matter what

This is the way it works in the binary format (which pgx uses by default). If you execute a query that returns a `timestamptz`, then change the session time zone, then execute the same query again, the exact same bytes will be returned from PostgreSQL.

> and it is on the user side to properly format the timestamp using provided timezone setting (which pgx just skips)?

Correct. I suppose it would be possible for pgx to remember what the session time zone is and convert it automatically. But it would need to handle the case where the server has time zones that the client does not. A quick experiment connecting to a PG 12 server on Ubuntu from a MacOS client found 622 time zone names that PostgreSQL recognized that Go `time.LoadLocation` didn't (about 600 were matched).

I'm not totally opposed to using session time zone when available, because it could be viewed as a bug fix. But I'm also concerned about this breaking code that relies on always getting a UTC time back. This would affect more than just people who explicitly set session time zone, because the correct way to do this would use the session time zone regardless of how it was set. e.g. server default or a `set time zone ...;`

**Comment by mvrhov** [comment]
Another option is then to set TZ in pool or somewhere else pgx has access to and then set a proper one when converting to the go's time.Time (Or  even better to query/transaction if one wants to have it different per the query)
