### ISSUE TITLE
Example for using prepared statements with pgx

### ISSUE THREAD

**Issue by danvixent** [jackc/pgx#791]
I'm a new user of the pgx library and can't find any good resources on how to use prepared statements with the library.
It really isn't clear and if someone could explain it wholly with examples...i'd be grateful.

**Comment by jackc** [comment]
pgx automatically prepares and caches statements by default. So unless you have a very specific and unusual use case you should not explicitly prepare statements. But if you do see this test for an example: https://github.com/jackc/pgx/blob/4ebf1d2e0baa87ab6afbbf6a0947c9fb8a30e9d4/conn_test.go#L384

**Comment by danvixent** [comment]
Yes, I'm talking about it's prepared statements feature. I am not explicitly preparing them, i wish to use library's own.
But i can't find any good explanation on how to use this.

**Comment by jackc** [comment]
Well, it's pretty automatic. You don't have to do anything. There's not even much that you can configure. But what configuration there is is documented with [pgx.ParseConfig](https://pkg.go.dev/github.com/jackc/pgx/v4?tab=doc#ParseConfig).

**Comment by danvixent** [comment]
Okay..so i just dived a bit deeper...and i found out that the statements can only be prepared on bare connections.
Is that right?

**Comment by jackc** [comment]
> Okay..so i just dived a bit deeper...and i found out that the statements can only be prepared on bare connections.
Is that right?

Yes... But that's still missing the point. Unless you have very unusual requirements you should forget that prepared statements even exist. pgx will do the right thing and use them under the hood.

**Comment by danvixent** [comment]
But i use *pool.Pool. Not connections directly.
And i need to use prepared statements at some point.

**Comment by jackc** [comment]
If you're using `pgxpool` then you can use `AfterConnect` to prepare statements. That will ensure that they are available on every connection. Otherwise you will have to acquire a connection from the pool manually and prepare it there before use.

**Comment by danvixent** [comment]
Yup...I've read through and through.
That's what i'm going to do...Thank you very much.

**Comment by MattShippo** [comment]
@jackc I am curious, why does the `pgx` API expose the ability to manually prepare a statement at all? When would this be recommend over relying on the default automatic caching?

**Comment by jackc** [comment]
> @jackc I am curious, why does the pgx API expose the ability to manually prepare a statement at all? When would this be recommend over relying on the default automatic caching?

In most cases the automatic statement preparation and caching is preferable. However, in certain rare cases it may be desirable to only prepare certain statements or to ensure certain statements are always prepared.

> I am still using version 4 of pgx, but noticed that 'schema must not change for cached prepared statement' error does not clear the cache when you manually Prepare a statement, but it does when you rely on the automatic cache. Are they two entirely seperate caches?

Only the automatic statement preparation is managed as a cache. Manually prepared statements are not a cache.

**Comment by MattShippo** [comment]
@jackc Thanks for the reply. We just upgraded from the last V3 version to latest V4 version. In the v3 version, were prepared statements managed as a cache?

**Comment by jackc** [comment]
v3 was a long time ago... but as far as I recall the that was added in v4.

**Comment by WickedBrat** [comment]
@jackc I think I understand the usage of prepared statements in pgxpool but just to get a clear understand, I'll reiterate my understanding.

Statements are in general prepared and then executed when using a single connection to the database. 

- [ ] When we're using a connection pool, it's doesn't happen so? There we need to explicitly add the prepared statements by using `AfterConnect()` method, so that it's available to us.
- [ ] Statements are prepared before being queried even when there's a pool connection. If if we still want to prepare them, (let's say define that at the start of the service), we can do that using the  `AfterConnect()` method.

**Comment by jackc** [comment]
@WickedBrat Not sure I understand the difference between your two options. If you are using pgxpool and explicitly prepared statements then the simplest thing to do is to prepare them in the `AfterConnect()` hook.

But as I mentioned above, you usually can rely on the statement cache and not manage statements explicitly.

**Comment by templatedop** [comment]
Hey! Thanks for clarification.

How to deal with cache when connection is established through pgbouncer.

Also how to  find size of cache. This helps me to increase cache capacity using config.

**Comment by jackc** [comment]
Historically, the cached prepared statement mode was incompatible with PgBouncer. They've recently added partial support, but I don't know if it is sufficient for pgx. See https://pkg.go.dev/github.com/jackc/pgx/v5#hdr-PgBouncer and https://pkg.go.dev/github.com/jackc/pgx/v5#QueryExecMode.

pgx does not expose cache statistics, but you can inspect the `pg_prepared_statements` view for statements with a name that starts with "stmtcache_".

**Comment by michalk-k** [comment]
> Historically, the cached prepared statement mode was incompatible with PgBouncer. They've recently added partial support, but I don't know if it is sufficient for pgx. See https://pkg.go.dev/github.com/jackc/pgx/v5#hdr-PgBouncer and https://pkg.go.dev/github.com/jackc/pgx/v5#QueryExecMode.
> 
> 
> 
> pgx does not expose cache statistics, but you can inspect the `pg_prepared_statements` view for statements with a name that starts with "stmtcache_".

Hello.
New pgbouncer renames prepared statements encoding normalized query into them. The prep statements by default get names like pgbouncer_x where x is an integer.

It works like this for CacheStatement mode only which I believe is best choice. This way pgbouncer is able to prepare prepared in all connections in the pool.

**Comment by templatedop** [comment]
Have you tested pgx v5 with pgbouncer or it is tested only with pgbouncer.

**Comment by michalk-k** [comment]
Not sure what you mean.
But let me show off our success with pgxpool v5 and the PgBouncer. We use them in production in transaction pooling mode with great success. It's the game-changer, really. we have dozens of apps, opening in total about 15k connections to pgbouncer. Generating traffic about 10k transactions per sec.

For pgxpool v5, the best mode is `QueryExecModeCacheStatement` (it's the default one). It's the only mode the prepared statement can be hijacked by PgBouncer, to maintain the prepared statements across connections from the pool.
You confirm that behavior by looking into PgBouncer and pg logs seeing that prepared statements are renamed to PGBOUCER_XXX where XXX is the number. 

I assume other modes can be used too, once a prepared statement is called inside a transaction. Moreover the `QueryExecModeSimpleProtocol` results in generating plain SQL queries by the pgxpool meaning no prepared statement is used at all.  But those miss the point of using prepared statements. 

Another thing to keep in mind is query timeout. Its implementation with timed context is prone to incorrect disconnection from PgBouncer (because query cancelation takes some time and is not guaranteed). It leads to prep. statements cache invalidation in pgbouncer. Thus should be avoided. We set `statement_timeout` in a database for a selected role, then set context timeout to a way higher value (like 3s and 30s respectively - but those numbers are arbitrary - tune them up to your needs)

Hope it will help.

**Comment by templatedop** [comment]
Thank You Very Much
