### ISSUE TITLE
pgxpool.Close() blocks indefinitely

### ISSUE THREAD

**Issue by bojanz** [jackc/pgx#802]
I am trying to migrate from database/sql and running into an issue that is probably a PEBKAC.

I have an Application struct which connects to the db in New():
```
func New(cfg *Config, logger *zerolog.Logger) (*Application, error) {
	db, err := pgxpool.Connect(context.Background(), cfg.Database.URL)
	if err != nil {
		return nil, err
	}
	app := &Application{
		cfg:    cfg,
		logger: logger,
		db:     db,
	}

       return app, nil
}
```

I also have a Shutdown() function called when SIGINT or SIGTERM are received, which shuts down http servers and other resources. and then calls app.db.Close().

I then introduced a Migrate() function which is supposed to run jackc/tern and migrate the database:
```
// Migrate migrates the db schema to the latest version.
func (app *Application) Migrate() error {
	ctx := context.Background()
	conn, err := app.db.Acquire(ctx)
	if err != nil {
		return err
	}
	defer conn.Conn().Close(ctx)

	migrator, err := migrate.NewMigrator(ctx, conn.Conn(), "schema")
	if err != nil {
		return err
	}
	err = migrator.LoadMigrations("migrations")
	if err != nil {
		return err
	}
	latestVersion := len(migrator.Migrations)
	currentVersion, err := migrator.GetCurrentVersion(ctx)
	if err != nil {
		return err
	}
	app.logger.Info().Msgf("Migrate: %v %v", currentVersion, latestVersion)
}
```

My main() then calls New() -> Migrate() -> Shutdown(). However, the app.db.Close() call now blocks indefinitely, preventing a clean shutdown. Ideally I'd either give it a context.WithTimeout() like I do with net/http.Server.Shutdown() and let it error out after a few seconds, or just do a force close since I know no requests are running anymore.
I'd also love to be able to initialize the migrator in New() and not have to care about conn.Close() at all (by adding a Migrator.Shutdown() func to tern?).

Am I making a mistake by calling app.db.Close() in the first place? Or is the mistake in not having a timeout on the ctx? Since every method call requires a ctx, it made me unsure if a timeout should be given to one, some, or all of them (and the examples I saw online don't seem to have any).

**Comment by jackc** [comment]
At a real quick glance I thing this line in `Migrate()` is the problem:

```go
defer conn.Conn().Close(ctx)
```

That is closing the underlying connection, but it never releases it back to the pool. So the reason the pool close is blocked is because it is waiting for all connections to be released which will never happen.

Try this instead. 

```go
defer conn.Release()
```

**Comment by bojanz** [comment]
Thank you for the quick reply, appreciated. 

You were right, that did the trick.

What would be the best way to protect against these kinds of errors? I'd like to ensure Shutdown() succeeds even if a defer was buggy or missing.

**Comment by jackc** [comment]
You could exit the program without closing the pool. It's not as polite to the PG server to just disappear without sending a `Terminate` message. But the PG server has to handle dropped connections anyway so it's not the end of the world.

Ideally, you don't want to be leaking connections through... As for how to prevent that -- it was only a subtle bug here because it only is one leak per program execution. If you were leaking connections in any regularly used path you would quickly experience a deadlock because of the pool being exhausted. Also, in normal cases you don't need to `Acquire` a connection manually, you call the query methods on the pool directly. Then you don't have to worry about releasing the connection (only about closing `Rows`).

**Comment by bojanz** [comment]
Understood. Thank you for the help, and thank you for your work on pgx and tern!
