### ISSUE TITLE
RowsAffected is 0 for DDL statements

### ISSUE THREAD

**Issue by pontuspalmenas** [jackc/pgx#818]
I want to know if the `Exec()` of  a conditional DDL statement (e.g. `create table if not exists`, `drop table if exists foo`) resulted in any change.

Example:
```
ct, err := Exec(ctx, "drop table if exists foo")
if ct.RowsAffected() > 0 {
    log.Info("DROP TABLE foo")
}
```

Unfortunately, `RowsAffected` here is always 0.

**Comment by jackc** [comment]
The PostgreSQL protocol doesn't expose that information in the command result. i.e. There is no way to have that result exposed in `RowsAffected()`.

However, PostgreSQL does emit a `notice` if the table didn't exist -- and you can supply pgx a callback function to run whenever a `notice` is received. See the `OnNotice` config option -- https://github.com/jackc/pgconn/blob/5db484908cf74895bb9e03414d1ba022a24e11bd/config.go#L57

**Comment by pontuspalmenas** [comment]
Thanks Jack. From my understanding, this would be triggered on a global level, so there wouldn't be a way to know that it was my previous call that resulted in the notice.

In my case, I need to log if the DDL statement resulted in a change to the database. And I want to log that specific statement, ideally (pseudo-code):
```
s := "drop table if exists foo"
if Exec(s) > 0 {
  log.Info(s)
}
```

**Comment by jackc** [comment]
Unfortunately, whether or not the table existed is not exposed in the PostgreSQL query protocol.

The notice callback includes the connection that the notice came from so with a bit of gymnastics you could get the info you need. Otherwise, you could look into PostgreSQL event triggers or possibly acting as a replication client. But notice callback is probably the easiest of these 3.

Practically speaking, the real solution is likely to be don't use `if exists`. Instead inspect the PostgreSQL catalog manually and only drop the table if it exists (probably want to do both steps in a transaction).
