### ISSUE TITLE
Query returning nil error for SQL errors caused by invalid query parameters

### ISSUE THREAD

**Issue by deelawn** [jackc/pgx#820]
Running pgx v4.8.0

I'm struggling to understand why failures are reported differently depending on whether values are parameterized or not.  See the following examples:

```
sql := `
    with times_table as (
        select
	    to_timestamp('asdf') as err_time
    )
    select
        tt.err_time 
    from
        times_table tt
`
rows, err := db.Query(ctx, sql)
```

The above query will fail due to the to_timestamp arg and err will be non nil and contain the error message from postgres

```
sql := `
    with times_table as (
        select
	    to_timestamp($1) as err_time
    )
    select
        tt.err_time 
    from
        times_table tt
`
rows, err := db.Query(ctx, sql, 'asdf')
```
But the result of the above query with the parameter is different; err will be returned as nil. After calling rows.Next() the error is visible by calling rows.Err().

Is this the expected behavior?  If so, what is the justification?  My understanding was that rows.Err() returns an error encountered when trying to read a row in the result set, but in this case it seems like the query never executed and there should be no rows in the result set.

**Comment by jackc** [comment]
The short answer is that `rows.Err()` will always have any error that occurs during the query, but whether or not the error is also returned from `db.Query` is an implementation detail and should not be relied upon. In fact the only reason Query returns an error at all is because `Query`, `QueryRow`, and `Exec` are designed to be closely match `database/sql`. It is superfluous compared to checking `rows.Err()` (which is always required).

The long answer is that multiple implementation details combine to produce this particular behavior.

1. `Query` only returns an error if there is a problem *sending* the query. It doesn't wait for any response.
2. pgx uses the extended protocol by default in most circumstances. This basically means it is using prepared statements.
3. When PostgreSQL prepares a statement with a constant expression it evaluates it at prepare time *not* execution time.

So in your first example the prepare stage of `Query` fails. In your second, The prepare succeeds and the query is successfully sent. The error is only detected when rows reads the results.

You can see this behavior demonstrated in `psql`.

```
jack@[local]:5432 pgx_test=# prepare s as select to_timestamp($1);
PREPARE
jack@[local]:5432 pgx_test=# prepare s2 as select to_timestamp('asdf');
ERROR:  invalid input syntax for type double precision: "asdf"
LINE 1: prepare s2 as select to_timestamp('asdf');
```

**Comment by deelawn** [comment]
Thanks for the detailed explanation
