### ISSUE TITLE
Question: Handling Postgres infinity/-infinity time

### ISSUE THREAD

**Issue by sterlingdeng** [jackc/pgx#830]
Is there a feature similar to the function in the pq library `pq.EnableInfinityTs()` (see below) in the `stdlib` library where I can set a `time.Time` that a postgres `infinity` and `-infinity` maps to? I'm currently using the `stdlib` with sqlx.

https://godoc.org/github.com/lib/pq#EnableInfinityTs

**Comment by jackc** [comment]
pgx does not contain a direct analog to that feature.

pgx's native [pgtype.Timestamptz](https://pkg.go.dev/github.com/jackc/pgtype?tab=doc#Timestamptz) type directly represents infinity instead of mapping it to an arbitrary `time.Time`.

Also, pgx's type conversion system is extremely extensible. You can replace the standard `Timestamptz` handler with one of your own that implements this feature. See https://github.com/jackc/pgx/wiki/UUID-Support for an example of overriding the builtin UUID type. You could do the same type thing with `Timestamptz`.

**Comment by sterlingdeng** [comment]
thank you sir
