### ISSUE TITLE
pgx_test package?

### ISSUE THREAD

**Issue by jonasi** [jackc/pgx#85]
Any particular reason why the test files have a different package (`pgx_test`) than the rest of the files? 

I ask because it makes forking and testing this package a bit more tedious.  Test files now need to import `github.com/jackc/pgx`, which means that contributors would need to manually change all those references to `github.com/{contrib}/pgx` in their fork while in development, and then revert those references back before a PR.

I'd be happy to send a PR to clean all that up, but I just want to make sure that would be preferable.

**Comment by jackc** [comment]
For the normal tests, I think it was just to ensure testing of the external interface. I hadn't thought about the problems it would cause forks. I think that is a reasonable change to make forks easier.

The only place it might be sticky is in examples. Fully qualified package names are used there so that the examples are directly usable (see https://github.com/jackc/pgx/blob/master/example_custom_type_test.go). Not sure if there is a workaround for that. But there are only a few examples to worry about. Most forks would never need to touch them. So even if they stayed in a different package it shouldn't affect most people.

:+1:

**Comment by alaska** [comment]
This is actually pretty common. It's how you are sure you're testing out the external package interface without access to anything you shouldn't.

You mention "cleaning all that up", may I ask what the alternative is? And please don't say relative import paths. :)

If you want to fork with the eventual intent of merging, there are a couple ways you can handle this.  The "best" way might be to:

1) fork
2) go get github.com/jackc/pgx
3) git remote add myfork git@github.com:you/pgx.git
4) do stuff
5) git push myfork

But you can also be lazy and 
1) fork
2) git clone git@github.com/you/pgx.git
3) rm -rf go/src/github.com/jackc/pgx
4) ln -s wherever/you/put/your/pgx go/src/github.com/jackc/pgx

Or you can unnecessarily use a rewriter and then back again for merging, which I don't recommend as it clogs the commit logs.

**Comment by jonasi** [comment]
@alaska the alternative would have been to migrate all the _test.go files to `package pgx`.

Option 1 works better though.

**Comment by alaska** [comment]
It's been a little while since I looked in the test code, but it might be worth considering an audit to do some tests in a separate package and some not. There are certainly benefits to both.  Generally, I tend to assume that the "higher-level" tests should be in a separate framework that deliberately does not have access to the unexported values and methods, but that unit tests can live in the base package.  I've seen it mixed before into, basically, the equivalent of `whitebox_test.go` and `blackbox_test.go`.  If ALL of the tests are under pgx_test, it could be beneficial to split them up (or not), but that's author preference.  In any case, I generally prefer to use one of the two methods above to avoid re-writing unless I intend for my fork to be semi-permanent.
