### ISSUE TITLE
Difficult to compare time.Time fields

### ISSUE THREAD

**Issue by thequailman** [jackc/pgx#863]
Hello, when using pgx, I'm seeing odd behavior when comparing time.Time fields of structs read from the database vs set in Go.  I think it's related to https://github.com/golang/go/issues/19486, as I'm using the `TZ=UTC` trick to resolve #789 .  This makes my timezones created in Go have a nil time.loc value (pgx has a non-nil time.loc pointing to UTC), causing the comparison to fail even though they're the same times.

I would appreciate it if you can follow through on your proposal to honor the timezone DSN setting (timezone=UTC).

**Comment by thequailman** [comment]
I ended up resolving this in my own by removing a UTC setting in my code, but I still would rather have the timezone DSN setting honored vs setting an environment variable with possible side effects.

**Comment by thequailman** [comment]
The ends up being the time.Unix parsing of binary time data.  It will set time.loc to UTC (even though Go's `.UTC()` does not, it's nil) and make the time.Time objects not match.  The problem here becomes working with these values with other libraries, like go-redis, which parses times as UTC with a nil time.loc and makes the values not match.

I'm not sure what the best way to fix this is.  I'm using the stdlib adapter, so I can't override this behavior I think, and I don't want to do a custom time.Time type everywhere (though I probably will have to).

**Comment by jackc** [comment]
Are you using [Time.Equal](https://golang.org/pkg/time/#Time.Equal)?

**Comment by thequailman** [comment]
Yes, time.Equal works fine, but when I compare structs using reflect.DeepEqual I get the comparison failures.

**Comment by jackc** [comment]
That's why `Time.Equal` exists, there can be multiple internal representations of the same instant. From the official Go docs:

> See the documentation on the Time type for the pitfalls of using == with Time values; most code should use Equal instead.

**Comment by thequailman** [comment]
I understand, but I can't use that when comparing structs using reflect.

**Comment by torkelrogstad** [comment]
This is a major issue for me in trying to migrate from lib/pq to pgx. I extensively use https://github.com/stretchr/testify throughout my test suite, where we compare structs using `assert.Equal`. This again calls `reflect.DeepEqual`, and my assertions fail. Would a solution be to not set `time.loc` when the time zone is UTC, or optionally expose some sort of option for doing this?

**Comment by jalandis** [comment]
This is blocking my switch to pgx due to a large number of tests requiring re-writing, 1000's of assertions would need to break up structs for comparison in odd ways.

I understand that `time.Equal` is the preferred method for comparison when different representations of the same date may exist.  However in test assertions, this is often not ideal for large structs with one date field. The representation is controlled in that situation and its a reasonable expectation that underlying fields would match in `time.Time` values.

There may also be a benefit in memory and/or performance in using nil to represent the very common UTC case. I assume thats why it is done in the time package anyway.

Appreciate all the work that goes into the project and I am looking forward to the switch whenever I can solve my test issues.  Thanks!

```
-    loc: (*time.Location)(<nil>)
+    loc: (*time.Location)({
+     name: (string) (len=3) "UTC",
+     zone: ([]time.zone) <nil>,
+     tx: ([]time.zoneTrans) <nil>,
+     extend: (string) "",
+     cacheStart: (int64) 0,
+     cacheEnd: (int64) 0,
+     cacheZone: (*time.zone)(<nil>)
+    })
```
