### ISSUE TITLE
Question: Encoding error using query result as CopyFromSource

### ISSUE THREAD

**Issue by pasqualino** [jackc/pgx#867]
Hi,

I'm trying to use the `CopyFrom` function to duplicate the data from some tables, using the result from a SELECT query as the `pgx.CopyFromSource` input.

Everything works fine, unless I try to write any of these column types: `geography`, `geography[]` and `jsonb[]`, where I get encoding errors:

```golang
func TestCopyFrom(t *testing.T) {
	ctx := context.Background()

	readConn, err := pgx.Connect(ctx,  os.Getenv("DATABASE_URL"))
	require.NoError(t, err)
	defer readConn.Close(ctx)

	writeConn, err := pgx.Connect(ctx, dbURL)
	require.NoError(t, err)
	defer writeConn.Close(ctx)

	_, err = readConn.Exec(ctx,
		`create temporary table test_copy_from(
			geo        geography,
			geo_array  geography[],
			json_array jsonb[]
		);`)
	require.NoError(t, err)

	_, err = readConn.Exec(ctx,
		`insert into test_copy_from(geo, geo_array, json_array) 
		values(
			ST_GeographyFromText('POINT(-77.0092 38.889588)'), 
			array[ ST_GeographyFromText('POINT(-77.0092 38.889588)'), ST_GeographyFromText('POINT(-77.0092 38.889588)')]::geography[],
			array['{"r":253, "g":226, "b":79, "a": 255}', '{"r":253, "g":226, "b":79, "a": 127}']::json[]
		)`)
	require.NoError(t, err)

	_, err = writeConn.Exec(ctx,
		`create temporary table test_copy_to(
			geo        geography,
			geo_array  geography[],
			json_array jsonb[]
		);`)
	require.NoError(t, err)

	rows, err := readConn.Query(ctx, `select geo, geo_array, json_array from test_copy_from`,
		pgx.QueryResultFormats{pgx.BinaryFormatCode, pgx.BinaryFormatCode, pgx.BinaryFormatCode},
	)
	require.NoError(t, err)

	n, err := writeConn.CopyFrom(ctx, pgx.Identifier{"test_copy_to"}, []string{"geo", "geo_array", "json_array"}, rows)
	require.NoError(t, err)
	require.Equal(t, int64(1), n)
}
```

I get these errors:

```
geo:        ERROR: COPY from stdin failed: Cannot encode []uint8 into oid 18634 - []uint8 must implement Encoder or be converted to a string (SQLSTATE 57014)
geo_array:  ERROR: COPY from stdin failed: Cannot encode []uint8 into oid 18640 - []uint8 must implement Encoder or be converted to a string (SQLSTATE 57014)
json_array: ERROR: COPY from stdin failed: Cannot encode []uint8 into oid 3807 - []uint8 must implement Encoder or be converted to a string (SQLSTATE 57014)
```

Also tried using the default TextFormat, converting the the geography to text (`ST_AsText`) and casting to text (`::text). In all these cases I get:
```
ERROR: Invalid endian flag value encountered. (SQLSTATE XX000)
```

What am I doing wrong here? Should I implement a custom decoder for these specific types?

Thanks

**Comment by jackc** [comment]
Wow, that's actually pretty crazy. I never intentionally designed `CopyFromSource` to have a compatible interface with `Rows`. It's cool that it _almost_ works anyway.

I think the problem is that the PostGIS types aren't understood by pgx so it is being returned from `Values` as ` []byte`. But the destination isn't a `bytea` so it fails.

The simplest change would be to add an intermediate step where you `Scan` into `pgtype.GenericBinary` and use those as the source for `CopyFrom`.

But there might be an even better way. I'm guessing that your goal is to copy data from one server to the other -- otherwise you would do it all server side. If that is the case, then I recommend looking into going down to the lower level `*pgconn.PgConn` connection that underlies pgx. That has lower level `CopyTo` and `CopyFrom` methods that use `io.Reader` and `io.Writer`. I _think_ you could wire them directly into each other and copy the data without your application having to decode and encode the data at all. Haven't tried it myself -- but I think it should work.

**Comment by pasqualino** [comment]
Thanks a lot for the answer! I used the lower level `CopyTo` and `CopyFrom` methods and it worked quite well 👍
