### ISSUE TITLE
How to use ORDER BY with a variable input

### ISSUE THREAD

**Issue by carste98** [jackc/pgx#885]
Hi!

I'm trying to do a SELECT statement to fetch some rows for my website from the database. The rows should be sorted on a variable sent from the frontend. 

I've tried doing:

`orderBy = "publishedtime" // is a string, the quotations are not part of the string`
`rows, err = DB.query(context.Background(), SELECT * FROM article JOIN users ON (article.user_id = users.id) ORDER BY $1 LIMIT $2, orderBy, amount)`

`orderBy` is a valid attribute in the database but still my rows won't return in the correct order. I've tried executing the same statement in to the database using sql shell
`SELECT * FROM article JOIN users ON (article.user_id = users.id) ORDER BY "publishedtime" LIMIT 30;`
and there it works just fine getting them in the correct order. 

What is a way to fix this? I haven't found any examples of how to use ORDER BY with variable input in pgx.

Thankful for any help

**Comment by jackc** [comment]
The difference is with pgx you are executing `ORDER BY 'publishedtime'` and with psql you are executing `ORDER BY "publishedtime"`. i.e. with pgx you are sorting by a literal string instead of a column reference. The PostgreSQL wire protocol does not support bind variables that are column references. You will need to (safely and carefully) build SQL with that value interpolated into it.

When I need to do something like this I validate the input against a whitelist of allowed sort expressions before interpolating into the SQL string.

**Comment by carste98** [comment]
Oh,  okay thanks, will have to do that then.

**Comment by kunKun-tx** [comment]
Just got bit by this. Do you think we shall put it in the FAQ?
