### ISSUE TITLE
pgx ignores error "ERROR: numeric field overflow (SQLSTATE 22003)"

### ISSUE THREAD

**Issue by swelf19** [jackc/pgx#888]
installed pgx - github.com/jackc/pgx/v4 v4.10.0

what i got: no errors in err variable, but errors in logs
> INFO[0000] Dialing PostgreSQL server                     host=localhost
> rows error:  <nil> <nil>
> ERRO[0000] Query                                         args="[]" err="ERROR: numeric field overflow (SQLSTATE 22003)" pid=844 sql="select v1::decimal(1,1) from (values (1.0),(1000.0)) as f(v1)"
> 

expected: some errors returned from pool.Query or rows.Scan methods.

code to reproduce
```golang
package main

import (
	"context"
	"fmt"

	log "github.com/sirupsen/logrus"

	"github.com/jackc/pgx/v4/log/logrusadapter"
	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	config, err := pgxpool.ParseConfig("postgresql://localhost:5432/database?user=postgres&password=12345")
	if err != nil {
		log.Fatalln(err)
	}
	logger := log.New()
	logger.Level = log.TraceLevel
	config.ConnConfig.Logger = logrusadapter.NewLogger(logger)
	pool, _ := pgxpool.ConnectConfig(context.Background(), config)

	var f float64
	rows, err := pool.Query(context.Background(), "select v1::decimal(1,1) from (values (1.0),(1000.0)) as f(v1)")
	fmt.Println("rows error: ", err, rows.Err())
	for rows.Next() {
		fmt.Println("before scan")
		err = rows.Scan(&f)
		fmt.Printf("after scan error: %v, value %f\n", err, f)
	}
}
```

**Comment by jackc** [comment]
Check `rows.Err()` at the end.

**Comment by swelf19** [comment]
Thank u for quick feedback.
yes, rows.Err() returns an error after a loop, but error processing like this not  very clear. why do we need error from pool.Query and rows.Scan if we do not use it in this case?
same time QueryRow retuns an error itself
```golang
err = pool.QueryRow(context.Background(), "select v1::decimal(1,1) from (values (1.0),(1000.0)) as f(v1)").Scan(&f)
fmt.Println("queryRow error: ", err)
```
queryRow error:  ERROR: numeric field overflow (SQLSTATE 22003)

**Comment by jackc** [comment]
> why do we need error from pool.Query and rows.Scan if we do not use it in this case?

A combination of following precedent from `database/sql` and how *exactly* the PostgreSQL server and protocol handle this exact case.

The query is successfully sent and the PostgreSQL server parses and sends back the `RowDescription`. This is why `Query` does not return an error.

The next message would normally be `DataRow`. But there is an error instead. This means `Next()` returns false. So your `Scan` is never run at all.

Here is a dump of the messages sent and received when executing that SQL through psql.

```
F {"Type":"Query","String":"select v1::decimal(1,1) from (values (1.0),(1000.0)) as f(v1);"}
B {"Type":"RowDescription","Fields":[{"Name":"v1","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":1700,"DataTypeSize":-1,"TypeModifier":65541,"Format":0}]}
B {"Severity":"ERROR","Code":"22003","Message":"numeric field overflow","Detail":"A field with precision 1, scale 1 must round to an absolute value less than 1.","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"numeric.c","Line":6612,"Routine":"apply_typmod","UnknownFields":{"86":"ERROR"}}
B {"Type":"ReadyForQuery","TxStatus":"I"}
```

`QueryRow` returns an error because it correctly checks `rows.Err()` internally.

 I proposed a new `QueryFunc` method that would remove this issue and simply querying in #821. But it received little response.
