### ISSUE TITLE
support for citext[]

### ISSUE THREAD

**Issue by kfirufk** [jackc/pgx#898]
Hi
I started using citext for case insensitive matching, the problem is that when I run a query that receives citext[], I get it as a string. for example I have only one item there called foo, so I will Receive 
"{Foo}" as a string. of course if I change the citext back to text[] it works properly.
 
so reproduce just "create extension citext" and select a query that returns an array and cast it as citext[], you will that in go you receive it as a string instead of array, cast it as text[] and it works.

**Comment by jackc** [comment]
That's because pgx understands types based on their `oid`. Types built into core PostgreSQL have fixed oids. e.g. `text[]` is `1009`. But `citext` is created by an extension. This means the `oid` is varies between databases. So to pgx it is just an unknown type and the only thing it can do is treat it as a string.

You can resolve this by scanning into `pgtype.TextArray` or by registering a data type for citext (see https://github.com/jackc/pgx/wiki/UUID-Support for an example of registering a data type).
