### ISSUE TITLE
Question around placeholders

### ISSUE THREAD

**Issue by samstride** [jackc/pgx#909]
Hi,

Thanks for maintaining this library.

I am using Cockroach DB + pgx

How do I safely parameterise CRDB `decimal(precision, scale)` (equivalent to Postgres `numeric(precision, scale)`)

Example:

```sql
 SELECT (($1::decimal / $2::decimal)::decimal($3,$4))::string;
```

The above query will work on a tool like DBeaver (but won't work on CRDB's sql client as expected)

I am doing something like this in Go (using a connection pool):

```go
var result string
const query = `SELECT (($1::decimal / $2::decimal)::decimal($3,$4))::string`
err := dbpool.QueryRow(ctx, query, "2", "2.2", "20", "15").Scan(&result)
if err != nil {
  fmt.Println(err)
}
```

I am getting this error as expected:

```sh
ERROR: at or near "3": syntax error (SQLSTATE 42601)
```

Whats the most secure way to parameterise in this case and I can't trust inputs?

**Comment by jackc** [comment]
The problem is that the most secure way to execute a query is with a prepared statement, but you cannot use a placeholder as part of a type modifier.

For example, observe what happens when running this in `psql`.

```
jack@[local]:5432 jack=# prepare s as SELECT (($1::decimal / $2::decimal)::decimal($3,$4))::text;
ERROR:  type modifiers must be simple constants or identifiers
LINE 1: prepare s as SELECT (($1::decimal / $2::decimal)::decimal($3...
```

But it works with the values inlined.

```
jack@[local]:5432 jack=# prepare s as SELECT (($1::decimal / $2::decimal)::decimal(20, 15))::text;
PREPARE
```

It only will work for clients that use the simple protocol -- which means you are relying on the client library / application to do parameter sanitization. Presumably this is what "DBeaver" is doing. You _can_ tell pgx to use the simple protocol and handle sanitization itself if you really want to. But that seems like an awfully big hammer to use on this problem.

In this case the only acceptable values for your `$3` and `$4` are integers. I would manually validate that they are integers and interpolate them into the SQL string.

**Comment by samstride** [comment]
Cheers for the guidance.
