### ISSUE TITLE
Deferred constraint triggers are not working properly with sql.QueryRow

### ISSUE THREAD

**Issue by torkelrogstad** [jackc/pgx#958]
For a small-ish reproduction of this, see my fork of pgx: https://github.com/torkelrogstad/pgx/commit/2042e2855597de6fcc2a45e93247c7506aea22d0

I have a table with a deferred constraint trigger on it. I expect it to be impossible to insert a row with `n=4` into the table. When I do a non-returning `INSERT`, that works fine. However, when I do `INSERT ... RETURNING id`, and `QueryRow` from the `sql` standard library package, I don't get an error. 

From fooling around in the Goland debugger, it seems like there's a `row.Next` call or two missing somewhere.

**Comment by jackc** [comment]
I adapted your test and fixed the underlying issue.

But the test had a few issues worth clarifying.

It is not valid to check the error of `Row` before calling `Scan`. From the docs:

> Errors are deferred until Row's Scan method is called.

When a deferred error occurs `Scan` will now return the error, but the arguments to `Scan` will still be updated. This is because the server sends back the results before the error occurs. The first row has already been scanned.

**Comment by torkelrogstad** [comment]
Thanks for fixing the issue, and also thanks for clarifying!
