### ISSUE TITLE
bigint[] only accept pgtype.EnumArray, why?

### ISSUE THREAD

**Issue by enverbisevac** [jackc/pgx#979]
I have one ``CREATE DOMAIN public.id AS bigint;`` and in my table I have field: ``exclude_branches public.id[] NOT NULL DEFAULT '{}'`` and I want to map it in the code as pgtype.Int(X)Array but it accept only EnumArray. Do you have any suggestion?

**Comment by jackc** [comment]
I don't know why `EnumArray` would be in the picture at all. You might have better luck with `pgtype.ArrayType`.

pgx uses the binary format by default. Unfortunately, this can make things tricky when using custom types or domains. Especially when combined with arrays because the binary format of array includes the OID of the element type.

**Comment by enverbisevac** [comment]
I tried everything but right now only works with EnumArray
